'****************************************************************************************
'Generated By  : Kim Tae Ho 
'시스템구분    : RMS/PD/Server Control Class
'실행   환경   : COM+ Service Server Package
'프로그램명    : ccPDCOPREESTSUB.vb
'기         능 : - 상세견적관리
'특이  사항    : - CE 단 Query 복사 기능
'                -
'----------------------------------------------------------------------------------------
'HISTORY    :1) 2009.10.19 Kim Tae Ho
'            2) 
'****************************************************************************************
Imports System.Xml                  ' XML처리
Imports SCGLControl                 ' ControlClass의 Base Class
Imports SCGLUtil.cbSCGLConfig       ' ConfigurationClass
Imports SCGLUtil.cbSCGLErr          '오류처리 클래스
Imports SCGLUtil.cbSCGLXml          'XML처리 클래스
Imports SCGLUtil.cbSCGLUtil         '기타유틸리티 클래스
Imports ePDCO
Public Class ccPDCOCREPART
    Inherits ccControl
#Region "GROUP BLOCK : 전역 또는 모듈레벨의 변수/상수 선언"
    Private CLASS_NAME = "ccPDCOCFINPUT"                  '자신의 클래스명
    Private mobjcePD_OUTLIST_MST As ePDCO.cePD_OUTLIST_MST            '견적헤더 SqlExe
#End Region

#Region "GROUP BLOCK : Function Section"
    ' =============== 매체분류 관리 조회
    Public Function SelectRtn(ByVal strInfoXML As String, _
                              ByRef intRowCnt As Integer, _
                              ByRef intColCnt As Integer, _
                              ByVal strCLASSCODE As String) As Object

        Dim strCols As String         '컬럼변수
        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)

        Dim Con1 As String


        If strCLASSCODE <> "" Then Con1 = String.Format(" AND (ATTR01 = '{0}')", strCLASSCODE)

        strWhere = BuildFields(" ", Con1)

        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            strFormat = " SELECT  "
            strFormat = strFormat & "CLASS_CODE,CODE,'MC' SC_BU_CODE,CODE_NAME,SORT_SEQ,USE_YN,UPDATE_YN,ATTR02,DEBTOR,ACCOUNT,ATTR01,'N' INSERTYN "
            strFormat = strFormat & "FROM SC_CODE WHERE ATTR02 = 'K' AND LEN(ATTR01) = 4 {0} ORDER BY ATTR01,SORT_SEQ "

            strSQL = String.Format(strFormat, strWhere)

            Try

                .mobjSCGLSql.SQLConnect(.DBConnStr)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function
    '매체분류 관리 저장
    '============== 청구요청 하단그리드 작성 저장
    Public Function ProcessRtn(ByVal strInfoXML As String, _
                               ByVal vntData As Object) As Integer '데이터 INSERT/UPDATE
        Dim intRtn As Integer
        Dim i, intColCnt, intRows As Integer
        '입력 변수
        Dim strCLASS_CODE As String
        Dim strCODE As String
        Dim strCODE_NAME As String
        Dim dblSORT_SEQ As Double
        Dim strATTR01 As String
        Dim strDEBTOR As String
        Dim strACCOUNT As String

        Dim strSQL As String



        'CLASS_CODE|CODE|SC_BU_CODE = MC |CODE_NAME|SORT_SEQ|USE_YN = "Y" |UPDATE_YN = "N" |ATTR02 = "K" |DEBTOR|ACCOUNT|ATTR01
        SetConfig(strInfoXML)
        With mobjSCGLConfig
            Try
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                .mobjSCGLSql.SQLBeginTrans()

                If IsArray(vntData) Then
                    '''사용할 Entity 개체생성(Config 정보를 넘겨생성)
                    mobjcePD_OUTLIST_MST = New cePD_OUTLIST_MST(mobjSCGLConfig)
                    '''vntData의 컬럼수, 로우수를 변수입력
                    intColCnt = UBound(vntData, 1) : intRows = UBound(vntData, 2)

                    For i = 1 To intRows
                        '인서트
                        strCLASS_CODE = GetElement(vntData, "CLASS_CODE", intColCnt, i)
                        strCODE_NAME = GetElement(vntData, "CODE_NAME", intColCnt, i)
                        strATTR01 = GetElement(vntData, "ATTR01", intColCnt, i)
                        strDEBTOR = GetElement(vntData, "DEBTOR", intColCnt, i)
                        strACCOUNT = GetElement(vntData, "ACCOUNT", intColCnt, i)
                        strCODE = SelectRtn_CODE(strATTR01)
                        dblSORT_SEQ = SelectRtn_SORT(strATTR01)
                        If GetElement(vntData, "INSERTYN", intColCnt, i) = "Y" Then

                            strSQL = "INSERT INTO SC_CODE (CLASS_CODE,CODE,SC_BU_CODE,CODE_NAME,SORT_SEQ,USE_YN,UPDATE_YN,ATTR02,DEBTOR,ACCOUNT,ATTR01) "
                            strSQL = strSQL & " VALUES('" & strCLASS_CODE & "','" & strCODE & "','MC','" & strCODE_NAME & "'," & dblSORT_SEQ & ",'Y','N','K','" & strDEBTOR & "','" & strACCOUNT & "','" & strATTR01 & "')"

                            intRtn = mobjcePD_OUTLIST_MST.SqlExe(strSQL)

                        End If
                    Next
                End If


                .mobjSCGLSql.SQLCommitTrans()
                Return intRtn
            Catch err As Exception
                .mobjSCGLSql.SQLRollbackTrans()
                Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn")
            Finally
                .mobjSCGLSql.SQLDisconnect()
                mobjcePD_OUTLIST_MST.Dispose()
            End Try
        End With
    End Function

    '============== 제작매체분류 코드 생성
    Public Function SelectRtn_CODE(ByVal strCODE As String) As String
        '여기부터 단순조회
        Dim strSQL, strFormat, strRtn As String
        'SetConfig(strInfoXML) '기본정보 Setting

        Dim strPRECODE As String

        If strCODE = "PA01" Then
            strPRECODE = "PG"
        ElseIf strCODE = "PA02" Then
            strPRECODE = "PC"
        ElseIf strCODE = "PA05" Then
            strPRECODE = "PS"
        ElseIf strCODE = "PA07" Then
            strPRECODE = "PI"
        ElseIf strCODE = "PA08" Then
            strPRECODE = "PO"
        End If
        With mobjSCGLConfig '기본정보 Config 개체

            Try

                strSQL = "SELECT '" & strPRECODE & "'+DBO.LPAD(CAST(CAST(SUBSTRING(MAX(CODE),3,2) AS NUMERIC)+1 AS VARCHAR(2)),2,'0') FROM SC_CODE WHERE ATTR01 = '" & strCODE & "' AND ATTR02 = 'K' AND LEN(ATTR01) = 4 AND SUBSTRING(CODE,1,2) = '" & strPRECODE & "' "
                strRtn = .mobjSCGLSql.SQLSelectOneScalar(strSQL)
                Return strRtn
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_SEQNO")
            Finally
            End Try
        End With
        '여기까지 단순조회
    End Function
    '============== 제작매체분류 코드 생성
    Public Function SelectRtn_SORT(ByVal strCODE As String) As String
        '여기부터 단순조회
        Dim strSQL, strFormat, strRtn As String
        'SetConfig(strInfoXML) '기본정보 Setting


        With mobjSCGLConfig '기본정보 Config 개체

            Try

                strSQL = "SELECT MAX(SORT_SEQ) +1 FROM SC_CODE WHERE ATTR01 = '" & strCODE & "' AND LEN(ATTR01) = 4"
                strRtn = .mobjSCGLSql.SQLSelectOneScalar(strSQL)
                Return strRtn
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_SEQNO")
            Finally
            End Try
        End With
        '여기까지 단순조회
    End Function

    '콤보타입가져오기
    Public Function GetDataType(ByVal strInfoXML As String, _
                                ByRef intRowCnt As Integer, _
                                ByRef intColCnt As Integer, _
                                ByVal strCombo As String) As Object



        Dim strSQL, strFormat, strSelFields As String
        Dim vntData As Object
        Dim strWhere
        'Combo 구분자 [strCombo] --------------------------------
        'JOBGUBN : 좝구분, JOBBASE : 청구기준, CREGUBN : 제작구분, CREPART : 제작종류, 
        Select Case strCombo
            Case ("JOBGUBN")
                strWhere = "PD_JOBKIND"
            Case ("JOBBASE")
                strWhere = "PD_JOBBASE"
            Case ("CREGUBN")
                strWhere = "PD_CREGUBN"
            Case ("CREPART")
                strWhere = "CREPART"
            Case ("ENDFLAG")
                strWhere = "PD_ENDFLAG"
            Case ("PONOGUBN")
                strWhere = "PD_PONOGROUP"
        End Select


        SetConfig(strInfoXML)   '기본정보 설정

        '조회 필드 설정
        strSelFields = "CODE,CODE_NAME"

        'SQL문 생성
        If strWhere = "CREPART" Then
            strFormat = "SELECT {0} " & _
                   "FROM SC_CODE " & _
                   "WHERE ATTR02 = 'K' AND LEN(ATTR01) > 3 AND USE_YN = 'Y' ORDER BY CLASS_CODE,SORT_SEQ"

        Else
            strFormat = "SELECT {0} " & _
                               "FROM SC_CODE " & _
                               "WHERE CLASS_CODE = '" & strWhere & "' AND USE_YN = 'Y' " & _
                               "ORDER BY SORT_SEQ "
        End If


        With mobjSCGLConfig
            strSQL = String.Format(strFormat, strSelFields)

            ''데이터 조회
            Try
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt)
                Return vntData
            Catch err As Exception
                Throw RaiseSysErr(err, CLASS_NAME & ".GetDataType")
            Finally
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

    Public Function GetDataType_class(ByVal strInfoXML As String, _
                                      ByRef intRowCnt As Integer, _
                                      ByRef intColCnt As Integer) As Object

        Dim strSQL As String
        Dim vntData As Object


        SetConfig(strInfoXML)   '기본정보 설정

        '조회 필드 설정



        With mobjSCGLConfig
            strSQL = " SELECT  CLASS_CODE, "
            strSQL = strSQL & "CASE CLASS_CODE  "
            strSQL = strSQL & "WHEN 'PD_GRAPHICKIND' THEN '인쇄' "
            strSQL = strSQL & "WHEN 'PD_ELECKIND' THEN 'CF' "
            strSQL = strSQL & "WHEN 'PD_PROMOTIONKIND' THEN '프로모션' "
            strSQL = strSQL & "WHEN 'PD_INTERNETKIND' THEN '인터넷' "
            strSQL = strSQL & "WHEN 'PD_OTHERSKIND' THEN '기타' END AS CLASS_CODENAME "
            strSQL = strSQL & "FROM SC_CODE WHERE ATTR02 = 'K' AND LEN(ATTR01) = 4 "
            strSQL = strSQL & "GROUP BY CLASS_CODE,ATTR01 "
            strSQL = strSQL & "ORDER BY ATTR01 "


            ''데이터 조회
            Try
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt)
                Return vntData
            Catch err As Exception
                Throw RaiseSysErr(err, CLASS_NAME & ".GetDataType_class")
            Finally
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

    Public Function GetDataType_debtor(ByVal strInfoXML As String, _
                                       ByRef intRowCnt As Integer, _
                                       ByRef intColCnt As Integer) As Object

        Dim strSQL As String
        Dim vntData As Object


        SetConfig(strInfoXML)   '기본정보 설정

        '조회 필드 설정



        With mobjSCGLConfig
            strSQL = "SELECT DEBTOR,'('+DEBTOR+') '+DEBTORNAME FROM SC_DEBTOR"

            ''데이터 조회
            Try
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt)
                Return vntData
            Catch err As Exception
                Throw RaiseSysErr(err, CLASS_NAME & ".GetDataType_debtor")
            Finally
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

    Public Function GetDataType_account(ByVal strInfoXML As String, _
                                        ByRef intRowCnt As Integer, _
                                        ByRef intColCnt As Integer) As Object
        Dim strSQL As String
        Dim vntData As Object


        SetConfig(strInfoXML)   '기본정보 설정

        '조회 필드 설정



        With mobjSCGLConfig
            strSQL = "SELECT ACCOUNT,'('+ACCOUNT+') '+ACCOUNTNAME FROM SC_ACCOUNT"

            ''데이터 조회
            Try
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt)
                Return vntData
            Catch err As Exception
                Throw RaiseSysErr(err, CLASS_NAME & ".GetDataType_account")
            Finally
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

#End Region

#Region "GROUP BLOCK : Entity Function Section"
    'strDATE,strMEETINGDATE,strSHOOTDATE 
   

#End Region
End Class
