'****************************************************************************************
'Generated By  : Kim Tae Ho 
'시스템구분    : RMS/PD/Server Control Class
'실행   환경   : COM+ Service Server Package
'프로그램명    : ccPDCMSEARCH.vb
'기         능 : - 조회모듈
'특이  사항    : - 
'                -
'----------------------------------------------------------------------------------------
'HISTORY    :1) 2008.12.11 Kim Tae Ho
'            2) 
'****************************************************************************************

Imports System.Xml                  ' XML처리
Imports SCGLControl                 ' ControlClass의 Base Class
Imports SCGLUtil.cbSCGLConfig       ' ConfigurationClass
Imports SCGLUtil.cbSCGLErr          '오류처리 클래스
Imports SCGLUtil.cbSCGLXml          'XML처리 클래스
Imports SCGLUtil.cbSCGLUtil         '기타유틸리티 클래스
Imports ePDCO                       '엔터티 추가

' 엔티티 클래스 사용시 해당 엔티티 클래스의 프로젝트를 참조한 후 Imports 하십시요. 
' Imports 엔티티프로젝트
Public Class ccPDCOSEARCH
    Inherits ccControl
#Region "GROUP BLOCK : 전역 또는 모듈레벨의 변수/상수 선언"
    Private CLASS_NAME = "ccPDCOSEARCH"                  '자신의 클래스명
    'Private Const .DBConnStr = "Provider=SQLOLEDB;Data Source=10.110.10.86;Initial Catalog=MCDEV;DSN=MCDEV;UID=devadmin;Pwd=password"
#End Region

#Region "GROUP BLOCK : Function Section"
    '===================================== 외주비 사용내역
    Function SelectRtn_PDCMOUTSLISTSEARCH(ByVal strInfoXML As String, _
                                          ByRef intRowCnt As Integer, _
                                          ByRef intColCnt As Integer, _
                                          ByVal strFrom As String, _
                                          ByVal strTo As String, _
                                          ByVal strPOPUPTYPE As String, _
                                          ByVal strCONFIRMFLAG As String, _
                                          ByVal strOUTSCODE As String, _
                                          ByVal strOUTSNAME As String) As Object

        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2, Con3, Con4 As String



        If strPOPUPTYPE <> "" Then

            If strPOPUPTYPE = "REG" Then '외주처 등록날짜조회
                If strFrom <> "" And strTo <> "" Then
                    Con1 = String.Format(" AND (B.REGDATE BETWEEN '{0}' AND  '{1}')", strFrom, strTo)
                End If
                If strFrom <> "" And strTo = "" Then
                    Con1 = String.Format(" AND (B.REGDATE >= '{0}')", strFrom)
                End If
                If strFrom = "" And strTo <> "" Then
                    Con1 = String.Format(" AND (B.REGDATE <= '{0}')", strTo)
                End If

            Else '전표날짜조회
                If strFrom <> "" And strTo <> "" Then
                    Con1 = String.Format(" AND (B.ADJDAY BETWEEN '{0}' AND  '{1}')", strFrom, strTo)
                End If
                If strFrom <> "" And strTo = "" Then
                    Con1 = String.Format(" AND (B.ADJDAY >= '{0}')", strFrom)
                End If
                If strFrom = "" And strTo <> "" Then
                    Con1 = String.Format(" AND (B.ADJDAY <= '{0}')", strTo)
                End If

            End If
        End If


        If strCONFIRMFLAG <> "" Then
            If strCONFIRMFLAG = "T" Then '승인
                Con2 = " AND (ISNULL(B.VOCHNO,'') <> '') "
            Else '미승인
                Con2 = " AND (ISNULL(B.VOCHNO,'') = '') "
            End If
        End If


        If strOUTSCODE <> "" Then Con3 = String.Format(" AND B.OUTSCODE = '{0}'", strOUTSCODE)
        If strOUTSNAME <> "" Then Con4 = String.Format(" AND DBO.SC_GET_HIGHCUSTNAME_FUN(B.OUTSCODE) like '%{0}%'", strOUTSNAME)

        strWhere = BuildFields(" ", Con1, Con2, Con3, Con4)
        strFormat = " SELECT "
        strFormat = strFormat & " 1 GBN,"
        strFormat = strFormat & " B.OUTSCODE,"
        strFormat = strFormat & " DBO.SC_GET_CUSTNAME_FUN(B.OUTSCODE) OUTSNAME,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(A.CLIENTCODE) CLIENTNAME,"
        strFormat = strFormat & " A.JOBNO,"
        strFormat = strFormat & " A.JOBNAME,"
        strFormat = strFormat & " B.ADJDAY,"
        strFormat = strFormat & " B.PURCHASENO,"
        strFormat = strFormat & " B.ADJAMT,"
        strFormat = strFormat & " CASE WHEN (VATCODE = '세금계산서불공제' OR VATCODE = '세금계산서(10%)')  THEN ROUND(B.ADJAMT*0.1,0) ELSE 0 END AS VAT,"
        strFormat = strFormat & " ISNULL(B.VATCODE,'') VATCODE,"
        strFormat = strFormat & " B.ADJAMT + CASE WHEN (VATCODE = '세금계산서영세율' OR VATCODE = '계산서' OR VATCODE = 'INVOICE')  THEN 0 ELSE ROUND(B.ADJAMT*0.1,0) END AS SUMAMT,"
        strFormat = strFormat & " B.CONTRACTNO,"
        strFormat = strFormat & " CASE C.CONFIRMFLAG WHEN '1' THEN '확인' ELSE '미확인' END AS CONFIRMFLAG"
        strFormat = strFormat & " FROM V_JOBNO A,PD_EXE_DTL B LEFT JOIN PD_CONTRACT_MST C ON B.CONTRACTNO = C.CONTRACTNO "
        strFormat = strFormat & " WHERE A.JOBNO = B.JOBNO {0}"

        strFormat = strFormat & " UNION ALL"

        strFormat = strFormat & " SELECT"
        strFormat = strFormat & " 2 GBN,"
        strFormat = strFormat & " OUTSCODE,"
        strFormat = strFormat & " '외주 소계' OUTSNAME,"
        strFormat = strFormat & " '' CLIENTNAME,"
        strFormat = strFormat & " '' JOBNO,"
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " '' ADJDAY,"
        strFormat = strFormat & " '' PURCHASENO,"
        strFormat = strFormat & " SUM(ADJAMT),"
        strFormat = strFormat & " SUM(VAT),"
        strFormat = strFormat & " VATCODE,"
        strFormat = strFormat & " SUM(SUMAMT),"
        strFormat = strFormat & " '' CONTRACTNO,"
        strFormat = strFormat & " '' CONFIRMFLAG"
        strFormat = strFormat & " FROM"
        strFormat = strFormat & " ("
        strFormat = strFormat & " 	SELECT"
        strFormat = strFormat & " 	B.OUTSCODE,"
        strFormat = strFormat & " 	DBO.SC_GET_CUSTNAME_FUN(B.OUTSCODE)+ ' 소계' OUTSNAME,"
        strFormat = strFormat & " 	SUM(B.ADJAMT) ADJAMT,"
        strFormat = strFormat & " 	CASE WHEN (VATCODE = '세금계산서영세율' OR VATCODE = '계산서' OR VATCODE = 'INVOICE')  THEN 0 ELSE SUM(ROUND(B.ADJAMT*0.1,0)) END AS VAT,"
        strFormat = strFormat & " 	'' VATCODE,"
        strFormat = strFormat & " 	SUM(B.ADJAMT) + CASE WHEN (VATCODE = '세금계산서영세율' OR VATCODE = '계산서' OR VATCODE = 'INVOICE')  THEN 0 ELSE SUM(ROUND(B.ADJAMT*0.1,0)) END AS SUMAMT"
        strFormat = strFormat & " 	FROM V_JOBNO A,PD_EXE_DTL B"
        strFormat = strFormat & " 	WHERE A.JOBNO = B.JOBNO {0}"
        strFormat = strFormat & " 	GROUP BY B.OUTSCODE,VATCODE"
        strFormat = strFormat & " ) SUBDATA"
        strFormat = strFormat & " GROUP BY OUTSCODE,VATCODE"

        strFormat = strFormat & " UNION ALL"

        strFormat = strFormat & " SELECT"
        strFormat = strFormat & " 3 GBN,"
        strFormat = strFormat & " 'ZZZZZZ' OUTSCODE,"
        strFormat = strFormat & " '합계' OUTSNAME,"
        strFormat = strFormat & " '' CLIENTNAME,"
        strFormat = strFormat & " '' JOBNO,"
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " '' ADJDAY,"
        strFormat = strFormat & " '' PURCHASENO,"
        strFormat = strFormat & " SUM(ADJAMT),"
        strFormat = strFormat & " SUM(VAT),"
        strFormat = strFormat & " '' VATCODE,"
        strFormat = strFormat & " SUM(SUMAMT),"
        strFormat = strFormat & " '' CONTRACTNO,"
        strFormat = strFormat & " '' CONFIRMFLAG"
        strFormat = strFormat & " FROM"
        strFormat = strFormat & " ("
        strFormat = strFormat & " 	SELECT"
        strFormat = strFormat & " 	B.OUTSCODE,"
        strFormat = strFormat & " 	DBO.SC_GET_CUSTNAME_FUN(B.OUTSCODE)+ ' 소계' OUTSNAME,"
        strFormat = strFormat & " 	SUM(B.ADJAMT) ADJAMT,"
        strFormat = strFormat & " 	CASE WHEN (VATCODE = '세금계산서영세율' OR VATCODE = '계산서' OR VATCODE = 'INVOICE')  THEN 0 ELSE SUM(ROUND(B.ADJAMT*0.1,0)) END AS VAT,"
        strFormat = strFormat & " 	'' VATCODE,"
        strFormat = strFormat & " 	SUM(B.ADJAMT) + CASE WHEN (VATCODE = '세금계산서영세율' OR VATCODE = '계산서' OR VATCODE = 'INVOICE')  THEN 0 ELSE SUM(ROUND(B.ADJAMT*0.1,0)) END AS SUMAMT"
        strFormat = strFormat & " 	FROM V_JOBNO A,PD_EXE_DTL B"
        strFormat = strFormat & " 	WHERE A.JOBNO = B.JOBNO {0}"
        strFormat = strFormat & " 	GROUP BY B.OUTSCODE,VATCODE"
        strFormat = strFormat & "  ) SUBDATA"
        strFormat = strFormat & " ORDER BY 2,1"

        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            strSQL = String.Format(strFormat, strWhere)
            Try
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
                ' ------ XML 데이터 조회
                'strXMLData = .mobjSCGLSql.SQLSelectXml(strSQL, intRowCnt, intColCnt)
                'Return strXMLData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_PDCMOUTSLISTSEARCH")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function
    '===================================== 진행비 사용내역
    Function SelectRtn_PDCMACCLISTSEARCH(ByVal strInfoXML As String, _
                                          ByRef intRowCnt As Integer, _
                                          ByRef intColCnt As Integer, _
                                          ByVal strFrom As String, _
                                          ByVal strTo As String) As Object

        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2, Con3 As String


        If strFrom <> "" And strTo <> "" Then
            Con1 = String.Format(" AND (A.ACCDAY BETWEEN '{0}' AND  '{1}')", strFrom, strTo)
        End If
        If strFrom <> "" And strTo = "" Then
            Con1 = String.Format(" AND (A.ACCDAY >= '{0}')", strFrom)
        End If
        If strFrom = "" And strTo <> "" Then
            Con1 = String.Format(" AND (A.ACCDAY <= '{0}')", strTo)
        End If




        strWhere = BuildFields(" ", Con1)

        strFormat = strFormat & " Select "
        strFormat = strFormat & " 1 gbn,"
        strFormat = strFormat & " b.clientcode,"
        strFormat = strFormat & " dbo.SC_GET_HIGHCUSTNAME_FUN(b.clientcode) clientname,"
        strFormat = strFormat & " b.jobno,"
        strFormat = strFormat & " b.jobname,"
        strFormat = strFormat & " dbo.SC_DEPT_NAME_FUN(b.cpdeptcd) deptname,"
        strFormat = strFormat & " dbo.SC_EMPNAME_FUN(b.cpempno) empname,"
        strFormat = strFormat & " a.accday,"
        strFormat = strFormat & " dbo.SC_GET_CUSTNAME_FUN(a.outscode) outsname,"
        strFormat = strFormat & " a.breakdown,"
        strFormat = strFormat & " a.amt,"
        strFormat = strFormat & " dbo.SC_GET_CODENAME_FUN(b.jobgubn) jobgubn"
        strFormat = strFormat & " from pd_acc_mst a, v_jobno b"
        strFormat = strFormat & " where a.jobno = b.jobno {0}"
        strFormat = strFormat & " union all"
        strFormat = strFormat & " Select "
        strFormat = strFormat & " 2 gbn,"
        strFormat = strFormat & " b.clientcode,"
        strFormat = strFormat & " dbo.SC_GET_CODENAME_FUN(b.jobgubn)+ ' 계' clientname,"
        strFormat = strFormat & " '' jobno,"
        strFormat = strFormat & " '' jobname,"
        strFormat = strFormat & " '' deptname,"
        strFormat = strFormat & " '' empname,"
        strFormat = strFormat & " '' accday,"
        strFormat = strFormat & " '' outsname,"
        strFormat = strFormat & " '' breakdown,"
        strFormat = strFormat & " sum(a.amt),"
        strFormat = strFormat & " dbo.SC_GET_CODENAME_FUN(b.jobgubn) jobgubn"
        strFormat = strFormat & " from pd_acc_mst a, v_jobno b"
        strFormat = strFormat & " where a.jobno = b.jobno {0}"
        strFormat = strFormat & " group by b.clientcode,b.jobgubn"
        strFormat = strFormat & " union all"
        strFormat = strFormat & " Select "
        strFormat = strFormat & " 3 gbn,"
        strFormat = strFormat & " b.clientcode,"
        strFormat = strFormat & " dbo.SC_GET_HIGHCUSTNAME_FUN(b.clientcode)+ ' 계' clientname,"
        strFormat = strFormat & " '' jobno,"
        strFormat = strFormat & " '' jobname,"
        strFormat = strFormat & " '' deptname,"
        strFormat = strFormat & " '' empname,"
        strFormat = strFormat & " '' accday,"
        strFormat = strFormat & " '' outsname,"
        strFormat = strFormat & " '' breakdown,"
        strFormat = strFormat & " sum(a.amt),"
        strFormat = strFormat & " 'YYYYYY' jobgubn"
        strFormat = strFormat & " from pd_acc_mst a, v_jobno b"
        strFormat = strFormat & " where a.jobno = b.jobno {0}"
        strFormat = strFormat & " group by b.clientcode"
        strFormat = strFormat & " union all"
        strFormat = strFormat & " Select "
        strFormat = strFormat & " 4 gbn,"
        strFormat = strFormat & " 'ZZZZZZ' clientcode,"
        strFormat = strFormat & " '합계' clientname,"
        strFormat = strFormat & " '' jobno,"
        strFormat = strFormat & " '' jobname,"
        strFormat = strFormat & " '' deptname,"
        strFormat = strFormat & " '' empname,"
        strFormat = strFormat & " '' accday,"
        strFormat = strFormat & " '' outsname,"
        strFormat = strFormat & " '' breakdown,"
        strFormat = strFormat & " sum(a.amt),"
        strFormat = strFormat & " 'ZZZZZZ'"
        strFormat = strFormat & " from pd_acc_mst a, v_jobno b"
        strFormat = strFormat & " where a.jobno = b.jobno {0}"
        strFormat = strFormat & " order by 2,12,1"


        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            strSQL = String.Format(strFormat, strWhere)
            Try
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
                ' ------ XML 데이터 조회
                'strXMLData = .mobjSCGLSql.SQLSelectXml(strSQL, intRowCnt, intColCnt)
                'Return strXMLData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_PDCMACCLISTSEARCH")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function
    '===================================== 광고처별 결산서
    Function SelectRtn_PDCMCUSTSEARCH(ByVal strInfoXML As String, _
                                         ByRef intRowCnt As Integer, _
                                         ByRef intColCnt As Integer, _
                                         ByVal strFrom As String, _
                                         ByVal strTo As String, _
                                         ByVal strCUSTCODE As String, _
                                         ByVal strCUSTNAME As String, _
                                         ByVal strJOBGUBN As String) As Object

        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2, Con3, Con4 As String


        If strFrom <> "" And strTo <> "" Then
            Con1 = String.Format(" AND (A.ENDDAY BETWEEN '{0}' AND  '{1}')", strFrom, strTo)
        End If
        If strFrom <> "" And strTo = "" Then
            Con1 = String.Format(" AND (A.ENDDAY >= '{0}')", strFrom)
        End If
        If strFrom = "" And strTo <> "" Then
            Con1 = String.Format(" AND (A.ENDDAY <= '{0}')", strTo)
        End If

        If strCUSTCODE <> "" Then Con2 = String.Format(" AND C.CLIENTCODE = '{0}'", strCUSTCODE)
        If strCUSTNAME <> "" Then Con3 = String.Format(" AND DBO.SC_GET_HIGHCUSTNAME_FUN(C.CLIENTCODE) like '%{0}%'", strCUSTNAME)
        If strJOBGUBN <> "" Then Con4 = String.Format(" AND C.JOBGUBN = '{0}'", strJOBGUBN)


        strWhere = BuildFields(" ", Con1, Con2, Con3, Con4)

        strFormat = " SELECT "
        strFormat = strFormat & " 1 GBN,"
        strFormat = strFormat & " A.ENDDAY,"
        strFormat = strFormat & " C.CLIENTCODE,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(C.CLIENTCODE) CLIENTNAME,"
        strFormat = strFormat & " DBO.SC_GET_SUBSEQNAME_FUN(C.SUBSEQ) SUBSEQNAME,"
        strFormat = strFormat & " A.JOBNO,"
        strFormat = strFormat & " C.JOBNAME,"
        strFormat = strFormat & " CASE ISNULL(B.DEMANDDAY,'') WHEN '' THEN '' ELSE SUBSTRING(B.DEMANDDAY,1,4)+'-'+SUBSTRING(B.DEMANDDAY,5,2) END AS DEMANDDAY,"
        strFormat = strFormat & " ISNULL(B.AMT,0) TAXAMT,"
        strFormat = strFormat & " ISNULL(A.PAYMENT,0)+ISNULL(A.ACCAMT,0) PAYMENT,"
        strFormat = strFormat & " ISNULL(A.INCOM,0) INCOM,"
        strFormat = strFormat & " ISNULL(A.RATE,0) RATE,"
        strFormat = strFormat & " DBO.SC_EMPNAME_FUN(C.CPEMPNO) EMPNAME,"
        strFormat = strFormat & " DBO.SC_GET_CODENAME_FUN(C.JOBGUBN) JOBGUBN"
        strFormat = strFormat & " FROM PD_EXE_HDR A "
        strFormat = strFormat & " LEFT JOIN (SELECT JOBNO,SUM(AMT) AMT,SUBSTRING(DEMANDDAY,1,6) DEMANDDAY FROM PD_TAX_DTL GROUP BY JOBNO,SUBSTRING(DEMANDDAY,1,6)) B"
        strFormat = strFormat & " ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " LEFT JOIN V_JOBNO C ON A.JOBNO = C.JOBNO"
        strFormat = strFormat & " WHERE ISNULL(A.ENDDAY,'') <> '' {0}"
        strFormat = strFormat & " UNION ALL"
        strFormat = strFormat & " SELECT "
        strFormat = strFormat & " 2 GBN,"
        strFormat = strFormat & " '' ENDDAY,"
        strFormat = strFormat & " C.CLIENTCODE,"
        strFormat = strFormat & " DBO.SC_GET_CODENAME_FUN(C.JOBGUBN)+ ' 소계'  CLIENTNAME,"
        strFormat = strFormat & " '' SUBSEQNAME,"
        strFormat = strFormat & " '' JOBNO,"
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " '' DEMANDDAY,"
        strFormat = strFormat & " ISNULL(SUM(B.AMT),0) TAXAMT,"
        strFormat = strFormat & " SUM(ISNULL(A.PAYMENT,0))+SUM(ISNULL(A.ACCAMT,0)) PAYMENT,"
        strFormat = strFormat & " SUM(ISNULL(A.INCOM,0)) INCOM,"
        strFormat = strFormat & " CASE ISNULL(SUM(B.AMT),0) WHEN 0 THEN 0 ELSE"
        strFormat = strFormat & " Round(((ISNULL(SUM(B.AMT),0)-(SUM(ISNULL(A.PAYMENT,0))+SUM(ISNULL(A.ACCAMT,0))))/ISNULL(SUM(B.AMT),0))*100,2)"
        strFormat = strFormat & " END AS RATE,"
        strFormat = strFormat & " '' EMPNAME,"
        strFormat = strFormat & " DBO.SC_GET_CODENAME_FUN(C.JOBGUBN) JOBGUBN"
        strFormat = strFormat & " FROM PD_EXE_HDR A "
        strFormat = strFormat & " LEFT JOIN (SELECT JOBNO,SUM(AMT) AMT,SUBSTRING(DEMANDDAY,1,6) DEMANDDAY FROM PD_TAX_DTL GROUP BY JOBNO,SUBSTRING(DEMANDDAY,1,6)) B"
        strFormat = strFormat & " ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " LEFT JOIN V_JOBNO C ON A.JOBNO = C.JOBNO"
        strFormat = strFormat & " WHERE ISNULL(A.ENDDAY,'') <> '' {0}"
        strFormat = strFormat & " GROUP BY C.CLIENTCODE,C.JOBGUBN"
        strFormat = strFormat & " UNION ALL"
        strFormat = strFormat & " SELECT "
        strFormat = strFormat & " 3 GBN,"
        strFormat = strFormat & " '' ENDDAY,"
        strFormat = strFormat & " C.CLIENTCODE,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(C.CLIENTCODE)+ ' 소계'  CLIENTNAME,"
        strFormat = strFormat & " '' SUBSEQNAME,"
        strFormat = strFormat & " '' JOBNO,"
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " '' DEMANDDAY,"
        strFormat = strFormat & " ISNULL(SUM(B.AMT),0) TAXAMT,"
        strFormat = strFormat & " SUM(ISNULL(A.PAYMENT,0))+SUM(ISNULL(A.ACCAMT,0)) PAYMENT,"
        strFormat = strFormat & " SUM(ISNULL(A.INCOM,0)) INCOM,"
        strFormat = strFormat & " CASE ISNULL(SUM(B.AMT),0) WHEN 0 THEN 0 ELSE"
        strFormat = strFormat & " Round(((ISNULL(SUM(B.AMT),0)-(SUM(ISNULL(A.PAYMENT,0))+SUM(ISNULL(A.ACCAMT,0))))/ISNULL(SUM(B.AMT),0))*100,2)"
        strFormat = strFormat & " END AS RATE,"
        strFormat = strFormat & " '' EMPNAME,"
        strFormat = strFormat & " 'Y' JOBGUBN"
        strFormat = strFormat & " FROM PD_EXE_HDR A "
        strFormat = strFormat & " LEFT JOIN (SELECT JOBNO,SUM(AMT) AMT,SUBSTRING(DEMANDDAY,1,6) DEMANDDAY FROM PD_TAX_DTL GROUP BY JOBNO,SUBSTRING(DEMANDDAY,1,6)) B"
        strFormat = strFormat & " ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " LEFT JOIN V_JOBNO C ON A.JOBNO = C.JOBNO"
        strFormat = strFormat & " WHERE ISNULL(A.ENDDAY,'') <> '' {0}"
        strFormat = strFormat & " GROUP BY C.CLIENTCODE"
        strFormat = strFormat & " UNION ALL"
        strFormat = strFormat & " SELECT "
        strFormat = strFormat & " 4 GBN,"
        strFormat = strFormat & " '' ENDDAY,"
        strFormat = strFormat & " 'ZZZZZZ' CLIENTCODE,"
        strFormat = strFormat & " '합계'  CLIENTNAME,"
        strFormat = strFormat & " '' SUBSEQNAME,"
        strFormat = strFormat & " '' JOBNO,"
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " '' DEMANDDAY,"
        strFormat = strFormat & " ISNULL(SUM(B.AMT),0) TAXAMT,"
        strFormat = strFormat & " SUM(ISNULL(A.PAYMENT,0))+SUM(ISNULL(A.ACCAMT,0)) PAYMENT,"
        strFormat = strFormat & " SUM(ISNULL(A.INCOM,0)) INCOM,"
        strFormat = strFormat & " CASE ISNULL(SUM(B.AMT),0) WHEN 0 THEN 0 ELSE"
        strFormat = strFormat & " Round(((ISNULL(SUM(B.AMT),0)-(SUM(ISNULL(A.PAYMENT,0))+SUM(ISNULL(A.ACCAMT,0))))/ISNULL(SUM(B.AMT),0))*100,2)"
        strFormat = strFormat & " END AS RATE,"
        strFormat = strFormat & " '' EMPNAME,"
        strFormat = strFormat & " 'Z' JOBGUBN"
        strFormat = strFormat & " FROM PD_EXE_HDR A "
        strFormat = strFormat & " LEFT JOIN (SELECT JOBNO,SUM(AMT) AMT,SUBSTRING(DEMANDDAY,1,6) DEMANDDAY FROM PD_TAX_DTL GROUP BY JOBNO,SUBSTRING(DEMANDDAY,1,6)) B"
        strFormat = strFormat & " ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " LEFT JOIN V_JOBNO C ON A.JOBNO = C.JOBNO"
        strFormat = strFormat & " WHERE ISNULL(A.ENDDAY,'') <> ''"
        strFormat = strFormat & " order by 3,14,1"



        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            strSQL = String.Format(strFormat, strWhere)
            Try
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
                ' ------ XML 데이터 조회
                'strXMLData = .mobjSCGLSql.SQLSelectXml(strSQL, intRowCnt, intColCnt)
                'Return strXMLData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_PDCMCUSTSEARCH")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function
    '===================================== 선청구 누계현황
    Function SelectRtn_PREDEMAND(ByVal strInfoXML As String, _
                                 ByRef intRowCnt As Integer, _
                                 ByRef intColCnt As Integer, _
                                 ByVal strYEARMON As String, _
                                 ByVal strCLIENTCODE As String, _
                                 ByVal strCLIENTNAME As String) As Object

        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2 As String



        If strCLIENTCODE <> "" Then Con1 = String.Format(" AND B.CLIENTCODE = '{0}'", strCLIENTCODE)
        If strCLIENTNAME <> "" Then Con2 = String.Format(" AND DBO.SC_GET_HIGHCUSTNAME_FUN(B.CLIENTCODE) like '%{0}%'", strCLIENTNAME)





        strWhere = BuildFields(" ", Con1, Con2)

        strFormat = "SELECT"
        strFormat = strFormat & " 1 GBN,B.CLIENTCODE,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(B.CLIENTCODE) CLIENTNAME,"
        strFormat = strFormat & " CASE ISNULL(Z.YEARMON,'') WHEN '' THEN '' ELSE SUBSTRING(Z.YEARMON,1,4)+'-'+SUBSTRING(Z.YEARMON,5,2) END AS YEARMON,"
        strFormat = strFormat & " B.JOBNO,"
        strFormat = strFormat & " B.JOBNAME,"
        strFormat = strFormat & " A.ADJAMT,"
        strFormat = strFormat & " DBO.SC_EMPNAME_FUN(B.CPEMPNO) EMPNAME"
        strFormat = strFormat & " FROM "
        strFormat = strFormat & " (SELECT MAX(TAXYEARMON) YEARMON,JOBNO FROM PD_TAX_DTL GROUP BY JOBNO) Z,"
        strFormat = strFormat & " ("
        strFormat = strFormat & " 	SELECT YEARMON,JOBNO,"
        strFormat = strFormat & " 	SUM(ADJAMT) ADJAMT "
        strFormat = strFormat & " 	FROM PD_CLOSING_MST "
        strFormat = strFormat & " 	WHERE DIVFLAG = 'PREDEMANDAMT' "
        strFormat = strFormat & " 	AND YEARMON = '" & strYEARMON & "'"
        strFormat = strFormat & " 	GROUP BY JOBNO,YEARMON"
        strFormat = strFormat & " ) A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " WHERE A.JOBNO = B.JOBNO"
        strFormat = strFormat & " AND Z.JOBNO = B.JOBNO"
        strFormat = strFormat & " AND A.YEARMON = '" & strYEARMON & "' {0} "
        strFormat = strFormat & "  UNION ALL"
        strFormat = strFormat & " SELECT"
        strFormat = strFormat & " 2 GBN,CLIENTCODE,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(CLIENTCODE)+ ' 소계' CLIENTNAME,"
        strFormat = strFormat & " '' YEARMON,"
        strFormat = strFormat & " '' JOBNO,"
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " SUM(ADJAMT) ADJAMT,"
        strFormat = strFormat & " '' EMPNAME"
        strFormat = strFormat & " FROM"
        strFormat = strFormat & " ("
        strFormat = strFormat & " 	SELECT"
        strFormat = strFormat & " 	B.CLIENTCODE,"
        strFormat = strFormat & " 	DBO.SC_GET_HIGHCUSTNAME_FUN(B.CLIENTCODE) CLIENTNAME,"
        strFormat = strFormat & " 	Z.YEARMON,"
        strFormat = strFormat & " 	B.JOBNO,"
        strFormat = strFormat & " 	B.JOBNAME,"
        strFormat = strFormat & " 	A.ADJAMT,"
        strFormat = strFormat & " 	DBO.SC_EMPNAME_FUN(B.CPEMPNO) EMPNAME"
        strFormat = strFormat & " 	FROM "
        strFormat = strFormat & " 	(SELECT MAX(TAXYEARMON) YEARMON,JOBNO FROM PD_TAX_DTL GROUP BY JOBNO) Z,"
        strFormat = strFormat & " 	("
        strFormat = strFormat & " 		SELECT YEARMON,JOBNO,"
        strFormat = strFormat & " 		SUM(ADJAMT) ADJAMT "
        strFormat = strFormat & " 		FROM PD_CLOSING_MST "
        strFormat = strFormat & " 		WHERE DIVFLAG = 'PREDEMANDAMT' "
        strFormat = strFormat & "  		AND YEARMON = '" & strYEARMON & "'"
        strFormat = strFormat & " 		GROUP BY JOBNO,YEARMON"
        strFormat = strFormat & " 	) A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	WHERE A.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	AND Z.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	AND A.YEARMON = '" & strYEARMON & "' {0} "
        strFormat = strFormat & " ) SUBDATA"
        strFormat = strFormat & " GROUP BY CLIENTCODE"
        strFormat = strFormat & " UNION ALL"
        strFormat = strFormat & " SELECT "
        strFormat = strFormat & " 3 GBN,'Z' CLIENTCODE,"
        strFormat = strFormat & " '합계' CLIENTNAME,"
        strFormat = strFormat & " '' YEARMON,"
        strFormat = strFormat & " '' JOBNO,"
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " SUM(ADJAMT) ADJAMT,"
        strFormat = strFormat & " '' EMPNAME"
        strFormat = strFormat & " FROM"
        strFormat = strFormat & " ("
        strFormat = strFormat & " 	SELECT"
        strFormat = strFormat & "  	B.CLIENTCODE,"
        strFormat = strFormat & " 	DBO.SC_GET_HIGHCUSTNAME_FUN(B.CLIENTCODE) CLIENTNAME,"
        strFormat = strFormat & " 	Z.YEARMON,"
        strFormat = strFormat & " 	B.JOBNO,"
        strFormat = strFormat & " 	B.JOBNAME,"
        strFormat = strFormat & " 	A.ADJAMT,"
        strFormat = strFormat & " 	DBO.SC_EMPNAME_FUN(B.CPEMPNO) EMPNAME"
        strFormat = strFormat & " 	FROM "
        strFormat = strFormat & " 	(SELECT MAX(TAXYEARMON) YEARMON,JOBNO FROM PD_TAX_DTL GROUP BY JOBNO) Z,"
        strFormat = strFormat & " 	("
        strFormat = strFormat & " 		SELECT YEARMON,JOBNO,"
        strFormat = strFormat & " 		SUM(ADJAMT) ADJAMT "
        strFormat = strFormat & " 		FROM PD_CLOSING_MST "
        strFormat = strFormat & " 		WHERE DIVFLAG = 'PREDEMANDAMT' "
        strFormat = strFormat & " 		AND YEARMON = '" & strYEARMON & "'"
        strFormat = strFormat & " 		GROUP BY JOBNO,YEARMON"
        strFormat = strFormat & " 	) A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	WHERE A.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	AND Z.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	AND A.YEARMON = '" & strYEARMON & "'  {0} "
        strFormat = strFormat & " ) SUBDATA"



        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            strSQL = String.Format(strFormat, strWhere)
            Try
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
                ' ------ XML 데이터 조회
                'strXMLData = .mobjSCGLSql.SQLSelectXml(strSQL, intRowCnt, intColCnt)
                'Return strXMLData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_PREDEMAND")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function
    '===================================== 선급금 현황
    Function SelectRtn_PREPAYMENT(ByVal strInfoXML As String, _
                                  ByRef intRowCnt As Integer, _
                                  ByRef intColCnt As Integer, _
                                  ByVal strYEARMON As String, _
                                  ByVal strOUTSCODE As String, _
                                  ByVal strOUTSNAME As String) As Object

        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2 As String



        If strOUTSCODE <> "" Then Con1 = String.Format(" AND A.OUTSCODE = '{0}'", strOUTSCODE)
        If strOUTSNAME <> "" Then Con2 = String.Format(" AND DBO.SC_GET_HIGHCUSTNAME_FUN(A.OUTSCODE) like '%{0}%'", strOUTSNAME)





        strWhere = BuildFields(" ", Con1, Con2)

        strFormat = " SELECT "
        strFormat = strFormat & " 1 GBN,"
        strFormat = strFormat & " B.CLIENTCODE,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(B.CLIENTCODE) CLIENTNAME,"
        strFormat = strFormat & " B.SUBSEQ,"
        strFormat = strFormat & " DBO.SC_GET_SUBSEQNAME_FUN(B.SUBSEQ) SUBSEQNAME,"
        strFormat = strFormat & " B.JOBNO,"
        strFormat = strFormat & " B.JOBNAME,"
        strFormat = strFormat & " A.ADJDAY,"
        strFormat = strFormat & " A.PURCHASENO,"
        strFormat = strFormat & " A.OUTSCODE,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(A.OUTSCODE) OUTSNAME,"
        strFormat = strFormat & " A.STD,"
        strFormat = strFormat & " A.ADJAMT,"
        strFormat = strFormat & " DBO.SC_EMPNAME_FUN(B.CPEMPNO) EMPNAME"
        strFormat = strFormat & " FROM PD_CLOSING_MST A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " WHERE A.DIVFLAG = 'PREPAYMENT'"
        strFormat = strFormat & " AND A.YEARMON = '" & strYEARMON & "' {0}"
        strFormat = strFormat & " UNION ALL"
        strFormat = strFormat & " SELECT"
        strFormat = strFormat & " 2 GBN,"
        strFormat = strFormat & " CLIENTCODE,"
        strFormat = strFormat & " DBO.SC_GET_SUBSEQNAME_FUN(SUBSEQ)+' 소계' CLIENTNAME,"
        strFormat = strFormat & " SUBSEQ,"
        strFormat = strFormat & " '' SUBSEQNAME,"
        strFormat = strFormat & " '' JOBNO, "
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " '' ADJDAY,"
        strFormat = strFormat & " '' PURCHASENO,"
        strFormat = strFormat & " '' OUTSCODE,"
        strFormat = strFormat & " '' OUTSNAME,"
        strFormat = strFormat & " '' STD,"
        strFormat = strFormat & " SUM(ADJAMT) ADJAMT,"
        strFormat = strFormat & " '' EMPNAME"
        strFormat = strFormat & " FROM"
        strFormat = strFormat & " ("
        strFormat = strFormat & " 	SELECT "
        strFormat = strFormat & " 	B.CLIENTCODE,"
        strFormat = strFormat & " 	B.SUBSEQ,"
        strFormat = strFormat & " 	B.JOBNO,"
        strFormat = strFormat & " 	B.JOBNAME,"
        strFormat = strFormat & " 	A.ADJDAY,"
        strFormat = strFormat & " 	A.PURCHASENO,"
        strFormat = strFormat & " 	A.OUTSCODE,"
        strFormat = strFormat & " 	DBO.SC_GET_HIGHCUSTNAME_FUN(A.OUTSCODE) OUTSNAME,"
        strFormat = strFormat & " 	A.STD,"
        strFormat = strFormat & " 	A.ADJAMT,"
        strFormat = strFormat & " 	DBO.SC_EMPNAME_FUN(B.CPEMPNO) EMPNAME"
        strFormat = strFormat & " 	FROM PD_CLOSING_MST A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	WHERE A.DIVFLAG = 'PREPAYMENT'"
        strFormat = strFormat & " 	AND A.YEARMON = '" & strYEARMON & "' {0}"
        strFormat = strFormat & " ) SUBDATA"
        strFormat = strFormat & " GROUP BY CLIENTCODE,SUBSEQ"
        strFormat = strFormat & " UNION ALL"
        strFormat = strFormat & " SELECT"
        strFormat = strFormat & " 3 GBN,"
        strFormat = strFormat & " CLIENTCODE,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(CLIENTCODE)+' 소계' CLIENTNAME,"
        strFormat = strFormat & " 'Y' SUBSEQ,"
        strFormat = strFormat & " '' SUBSEQNAME,"
        strFormat = strFormat & " '' JOBNO, "
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " '' ADJDAY,"
        strFormat = strFormat & " '' PURCHASENO,"
        strFormat = strFormat & " '' OUTSCODE,"
        strFormat = strFormat & " '' OUTSNAME,"
        strFormat = strFormat & " '' STD,"
        strFormat = strFormat & " SUM(ADJAMT) ADJAMT,"
        strFormat = strFormat & " '' EMPNAME"
        strFormat = strFormat & " FROM"
        strFormat = strFormat & " ("
        strFormat = strFormat & " 	SELECT "
        strFormat = strFormat & " 	B.CLIENTCODE,"
        strFormat = strFormat & " 	B.SUBSEQ,"
        strFormat = strFormat & " 	B.JOBNO,"
        strFormat = strFormat & " 	B.JOBNAME,"
        strFormat = strFormat & " 	A.ADJDAY,"
        strFormat = strFormat & " 	A.PURCHASENO,"
        strFormat = strFormat & " 	A.OUTSCODE,"
        strFormat = strFormat & " 	DBO.SC_GET_HIGHCUSTNAME_FUN(A.OUTSCODE) OUTSNAME,"
        strFormat = strFormat & " 	A.STD,"
        strFormat = strFormat & " 	A.ADJAMT,"
        strFormat = strFormat & " 	DBO.SC_EMPNAME_FUN(B.CPEMPNO) EMPNAME"
        strFormat = strFormat & " 	FROM PD_CLOSING_MST A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	WHERE A.DIVFLAG = 'PREPAYMENT'"
        strFormat = strFormat & " 	AND A.YEARMON = '" & strYEARMON & "' {0}"
        strFormat = strFormat & " ) SUBDATA"
        strFormat = strFormat & " GROUP BY CLIENTCODE"
        strFormat = strFormat & " UNION ALL"
        strFormat = strFormat & " SELECT"
        strFormat = strFormat & " 4 GBN,"
        strFormat = strFormat & " 'Z' CLIENTCODE,"
        strFormat = strFormat & " '합계' CLIENTNAME,"
        strFormat = strFormat & " 'Z' SUBSEQ,"
        strFormat = strFormat & " '' SUBSEQNAME,"
        strFormat = strFormat & " '' JOBNO, "
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " '' ADJDAY,"
        strFormat = strFormat & " '' PURCHASENO,"
        strFormat = strFormat & " '' OUTSCODE,"
        strFormat = strFormat & " '' OUTSNAME,"
        strFormat = strFormat & " '' STD,"
        strFormat = strFormat & " SUM(ADJAMT) ADJAMT,"
        strFormat = strFormat & " '' EMPNAME"
        strFormat = strFormat & " FROM"
        strFormat = strFormat & " ("
        strFormat = strFormat & " 	SELECT "
        strFormat = strFormat & " 	B.CLIENTCODE,"
        strFormat = strFormat & " 	B.SUBSEQ,"
        strFormat = strFormat & " 	B.JOBNO,"
        strFormat = strFormat & " 	B.JOBNAME,"
        strFormat = strFormat & " 	A.ADJDAY,"
        strFormat = strFormat & " 	A.PURCHASENO,"
        strFormat = strFormat & " 	A.OUTSCODE,"
        strFormat = strFormat & " 	DBO.SC_GET_HIGHCUSTNAME_FUN(A.OUTSCODE) OUTSNAME,"
        strFormat = strFormat & " 	A.STD,"
        strFormat = strFormat & " 	A.ADJAMT,"
        strFormat = strFormat & " 	DBO.SC_EMPNAME_FUN(B.CPEMPNO) EMPNAME"
        strFormat = strFormat & " 	FROM PD_CLOSING_MST A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	WHERE A.DIVFLAG = 'PREPAYMENT'"
        strFormat = strFormat & " 	AND A.YEARMON = '" & strYEARMON & "' {0}"
        strFormat = strFormat & " ) SUBDATA"
        strFormat = strFormat & " ORDER BY 2,4,1"



        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            strSQL = String.Format(strFormat, strWhere)
            Try
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
                ' ------ XML 데이터 조회
                'strXMLData = .mobjSCGLSql.SQLSelectXml(strSQL, intRowCnt, intColCnt)
                'Return strXMLData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_PREPAYMENT")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function
    '===================================== 선급금 현황
    Function SelectRtn_ACCRUED(ByVal strInfoXML As String, _
                               ByRef intRowCnt As Integer, _
                               ByRef intColCnt As Integer, _
                               ByVal strYEARMON As String, _
                               ByVal strOUTSCODE As String, _
                               ByVal strOUTSNAME As String) As Object

        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2 As String



        If strOUTSCODE <> "" Then Con1 = String.Format(" AND A.OUTSCODE = '{0}'", strOUTSCODE)
        If strOUTSNAME <> "" Then Con2 = String.Format(" AND DBO.SC_GET_HIGHCUSTNAME_FUN(A.OUTSCODE) like '%{0}%'", strOUTSNAME)





        strWhere = BuildFields(" ", Con1, Con2)

        strFormat = " SELECT "
        strFormat = strFormat & " 1 GBN,"
        strFormat = strFormat & " A.OUTSCODE,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(A.OUTSCODE) OUTSNAME,"
        strFormat = strFormat & " B.CLIENTCODE,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(B.CLIENTCODE) CLIENTNAME,"
        strFormat = strFormat & " B.JOBNO,"
        strFormat = strFormat & " B.JOBNAME,"
        strFormat = strFormat & " DBO.PD_JOBBUSITYPE_FUN(A.JOBNO) BUSITYPE,"
        strFormat = strFormat & " A.ADJAMT,"
        strFormat = strFormat & " DBO.SC_EMPNAME_FUN(B.CPEMPNO) EMPNAME,"
        strFormat = strFormat & " B.HOPEENDDAY"
        strFormat = strFormat & " FROM PD_CLOSING_MST A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " WHERE A.DIVFLAG = 'ACCRUED'"
        strFormat = strFormat & " AND A.YEARMON = '" & strYEARMON & "' {0}"
        strFormat = strFormat & " UNION ALL"
        strFormat = strFormat & " SELECT"
        strFormat = strFormat & " 2 GBN,"
        strFormat = strFormat & " OUTSCODE,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(CLIENTCODE) +' 소계' OUTSNAME,"
        strFormat = strFormat & " CLIENTCODE,"
        strFormat = strFormat & " '' CLIENTNAME,"
        strFormat = strFormat & " '' JOBNO,"
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " '' BUSITYPE,"
        strFormat = strFormat & " SUM(ADJAMT) ADJAMT,"
        strFormat = strFormat & " '' EMPNAME,"
        strFormat = strFormat & " '' HOPEENDDAY"
        strFormat = strFormat & " FROM"
        strFormat = strFormat & " ("
        strFormat = strFormat & " 	SELECT "
        strFormat = strFormat & " 	A.OUTSCODE,"
        strFormat = strFormat & " 	B.CLIENTCODE,"
        strFormat = strFormat & " 	B.JOBNO,"
        strFormat = strFormat & " 	B.JOBNAME,"
        strFormat = strFormat & " 	DBO.PD_JOBBUSITYPE_FUN(A.JOBNO) BUSITYPE,"
        strFormat = strFormat & " 	A.ADJAMT,"
        strFormat = strFormat & " 	DBO.SC_EMPNAME_FUN(B.CPEMPNO) EMPNAME,"
        strFormat = strFormat & " 	B.HOPEENDDAY"
        strFormat = strFormat & " 	FROM PD_CLOSING_MST A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	WHERE A.DIVFLAG = 'ACCRUED'"
        strFormat = strFormat & " 	AND A.YEARMON = '" & strYEARMON & "' {0}"
        strFormat = strFormat & " ) SUBDATA"
        strFormat = strFormat & " GROUP BY OUTSCODE,CLIENTCODE"
        strFormat = strFormat & " UNION ALL"
        strFormat = strFormat & " SELECT"
        strFormat = strFormat & " 3 GBN,"
        strFormat = strFormat & " OUTSCODE,"
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(OUTSCODE) +' 소계' OUTSNAME,"
        strFormat = strFormat & " 'Y' CLIENTCODE,"
        strFormat = strFormat & " '' CLIENTNAME,"
        strFormat = strFormat & " '' JOBNO,"
        strFormat = strFormat & " '' JOBNAME,"
        strFormat = strFormat & " '' BUSITYPE,"
        strFormat = strFormat & " SUM(ADJAMT) ADJAMT,"
        strFormat = strFormat & " '' EMPNAME,"
        strFormat = strFormat & " '' HOPEENDDAY"
        strFormat = strFormat & " FROM"
        strFormat = strFormat & " ("
        strFormat = strFormat & " 	SELECT "
        strFormat = strFormat & " 	A.OUTSCODE,"
        strFormat = strFormat & " 	B.CLIENTCODE,"
        strFormat = strFormat & " 	B.JOBNO,"
        strFormat = strFormat & " 	B.JOBNAME,"
        strFormat = strFormat & " 	DBO.PD_JOBBUSITYPE_FUN(A.JOBNO) BUSITYPE,"
        strFormat = strFormat & " 	A.ADJAMT,"
        strFormat = strFormat & " 	DBO.SC_EMPNAME_FUN(B.CPEMPNO) EMPNAME,"
        strFormat = strFormat & " 	B.HOPEENDDAY"
        strFormat = strFormat & " 	FROM PD_CLOSING_MST A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	WHERE A.DIVFLAG = 'ACCRUED'"
        strFormat = strFormat & " 	AND A.YEARMON = '" & strYEARMON & "' {0}"
        strFormat = strFormat & " ) SUBDATA"
        strFormat = strFormat & " GROUP BY OUTSCODE"
        strFormat = strFormat & " UNION ALL"
        strFormat = strFormat & " SELECT"
        strFormat = strFormat & " 4 GBN,"
        strFormat = strFormat & " 'Z' OUTSCODE,"
        strFormat = strFormat & " ' 합계' OUTSNAME,"
        strFormat = strFormat & " 'Z' CLIENTCODE,"
        strFormat = strFormat & " '' CLIENTNAME,"
        strFormat = strFormat & " '' JOBNO,"
        strFormat = strFormat & " '' JOBNAME, "
        strFormat = strFormat & " '' BUSITYPE,"
        strFormat = strFormat & " SUM(ADJAMT) ADJAMT,"
        strFormat = strFormat & " '' EMPNAME,"
        strFormat = strFormat & " '' HOPEENDDAY"
        strFormat = strFormat & " FROM"
        strFormat = strFormat & " ("
        strFormat = strFormat & " 	SELECT "
        strFormat = strFormat & " 	A.OUTSCODE,"
        strFormat = strFormat & " 	B.CLIENTCODE,"
        strFormat = strFormat & " 	B.JOBNO,"
        strFormat = strFormat & " 	B.JOBNAME,"
        strFormat = strFormat & " 	DBO.PD_JOBBUSITYPE_FUN(A.JOBNO) BUSITYPE,"
        strFormat = strFormat & " 	A.ADJAMT,"
        strFormat = strFormat & " 	DBO.SC_EMPNAME_FUN(B.CPEMPNO) EMPNAME,"
        strFormat = strFormat & " 	B.HOPEENDDAY"
        strFormat = strFormat & " 	FROM PD_CLOSING_MST A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
        strFormat = strFormat & " 	WHERE A.DIVFLAG = 'ACCRUED'"
        strFormat = strFormat & " 	AND A.YEARMON = '" & strYEARMON & "' {0}"
        strFormat = strFormat & " ) SUBDATA"
        strFormat = strFormat & " ORDER BY 2,4,1"




        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            strSQL = String.Format(strFormat, strWhere)
            Try
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
                ' ------ XML 데이터 조회
                'strXMLData = .mobjSCGLSql.SQLSelectXml(strSQL, intRowCnt, intColCnt)
                'Return strXMLData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_ACCRUED")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function
    '===================================== 제작원가 투입 현황
    Function SelectRtn_TOTAL(ByVal strInfoXML As String, _
                             ByRef intRowCnt As Integer, _
                             ByRef intColCnt As Integer, _
                             ByVal strYEARMON As String) As Object

        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)

        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            strSQL = " SELECT"
            strSQL = strSQL & " SUBDATA1.CLIENTCODE CLIENTCODE,"
            strSQL = strSQL & " DBO.SC_GET_HIGHCUSTNAME_FUN(SUBDATA1.CLIENTCODE) CLIENTNAME,"
            strSQL = strSQL & " SUBDATA1.SUBSEQ SUBSEQ,"
            strSQL = strSQL & " DBO.SC_GET_SUBSEQNAME_FUN(SUBDATA1.SUBSEQ) SUBSEQNAME,"
            strSQL = strSQL & " ISNULL(SUBDATA2.AMT,0) DEMANDAMT,"
            strSQL = strSQL & " ISNULL(SUBDATA1.ADJAMT,0) ADJAMT,"
            strSQL = strSQL & " ISNULL(SUBDATA2.AMT,0) - ISNULL(SUBDATA1.ADJAMT,0) INCOM, "
            strSQL = strSQL & " CASE ISNULL(SUBDATA2.AMT,0) WHEN 0 THEN 0 "
            strSQL = strSQL & " ELSE"
            strSQL = strSQL & " Round(((ISNULL(SUBDATA2.AMT,0)-(ISNULL(SUBDATA1.ADJAMT,0)))/ISNULL(SUBDATA2.AMT,0))*100,2)"
            strSQL = strSQL & " END AS RATE,"
            strSQL = strSQL & " ISNULL(SUBDATA3.ADJAMT,0) PRE_PREPAYMENT,"
            strSQL = strSQL & " ISNULL(SUBDATA4.ADJAMT,0) THIS_PREPAYMENT,"
            strSQL = strSQL & " ISNULL(SUBDATA5.ADJAMT,0) PRE_ACCRUED,"
            strSQL = strSQL & " ISNULL(SUBDATA6.ADJAMT,0) THIS_ACCRUED,"
            strSQL = strSQL & " ISNULL(SUBDATA1.ADJAMT,0) - ISNULL(SUBDATA3.ADJAMT,0) + ISNULL(SUBDATA4.ADJAMT,0) +ISNULL(SUBDATA5.ADJAMT,0) - ISNULL(SUBDATA6.ADJAMT,0) THIS_CHARGE,DENSE_RANK() OVER (ORDER BY SUBDATA1.CLIENTCODE) AS RANKTRANS"
            strSQL = strSQL & " FROM"
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT"
            strSQL = strSQL & " TEMPADATA.CLIENTCODE,"
            strSQL = strSQL & " TEMPADATA.SUBSEQ,"
            strSQL = strSQL & " ISNULL(TEMPADATA.ADJAMT,0)+ISNULL(TEMPBDATA.ACCAMT,0) ADJAMT"
            strSQL = strSQL & " FROM"
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT"
            strSQL = strSQL & " 		CLIENTCODE,"
            strSQL = strSQL & " 		SUBSEQ,"
            strSQL = strSQL & " 		SUM(ADJAMT) ADJAMT"
            strSQL = strSQL & " 		FROM"
            strSQL = strSQL & " 		("
            strSQL = strSQL & " 		SELECT"
            strSQL = strSQL & " 		B.CLIENTCODE,"
            strSQL = strSQL & " 		B.SUBSEQ,"
            strSQL = strSQL & " 		CASE ISNULL(A.ENDDAY,'') WHEN '' THEN 0 ELSE SUM(ISNULL(A.ADJAMT,0)) END ADJAMT"
            strSQL = strSQL & " 		FROM PD_EXE_HDR Z,PD_CLOSING_MST A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
            strSQL = strSQL & " 		AND A.YEARMON = '" & strYEARMON & "'"
            strSQL = strSQL & " 		WHERE Z.JOBNO = A.JOBNO"
            strSQL = strSQL & " 		GROUP BY B.CLIENTCODE,B.SUBSEQ,A.ENDDAY"
            strSQL = strSQL & " 		) SUBDATA"
            strSQL = strSQL & " 	 GROUP BY CLIENTCODE,SUBSEQ"
            strSQL = strSQL & " )  TEMPADATA LEFT JOIN "
            strSQL = strSQL & " (SELECT  SUM(ACCAMT) ACCAMT,CLIENTCODE,SUBSEQ FROM PD_EXE_HDR A,V_JOBNO B WHERE A.JOBNO = B.JOBNO AND ISNULL(A.ENDDAY,'') <> 0 GROUP BY CLIENTCODE,SUBSEQ) TEMPBDATA"
            strSQL = strSQL & " ON TEMPADATA.CLIENTCODE = TEMPBDATA.CLIENTCODE"
            strSQL = strSQL & " AND TEMPADATA.SUBSEQ = TEMPBDATA.SUBSEQ"
            strSQL = strSQL & " ) SUBDATA1 "
            strSQL = strSQL & " LEFT JOIN"
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT "
            strSQL = strSQL & " 	SUM(A.AMT) AMT,"
            strSQL = strSQL & " 	B.CLIENTCODE,"
            strSQL = strSQL & " 	B.SUBSEQ"
            strSQL = strSQL & " 	FROM PD_TAX_DTL A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO "
            strSQL = strSQL & " 	WHERE TAXYEARMON = '" & strYEARMON & "'"
            strSQL = strSQL & " 	GROUP BY B.CLIENTCODE,B.SUBSEQ"
            strSQL = strSQL & " ) SUBDATA2"
            strSQL = strSQL & " ON SUBDATA1.CLIENTCODE = SUBDATA2.CLIENTCODE"
            strSQL = strSQL & " AND SUBDATA1.SUBSEQ = SUBDATA2.SUBSEQ"
            strSQL = strSQL & " LEFT JOIN "
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT "
            strSQL = strSQL & " 	SUM(A.ADJAMT) ADJAMT,"
            strSQL = strSQL & " 	B.CLIENTCODE,"
            strSQL = strSQL & " 	B.SUBSEQ "
            strSQL = strSQL & " 	FROM PD_CLOSING_MST A "
            strSQL = strSQL & " 	LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO "
            strSQL = strSQL & " 	WHERE A.DIVFLAG = 'PREPAYMENT'"
            strSQL = strSQL & " 	AND A.YEARMON =(convert(char(6), DATEADD(MM , -12, convert(smalldatetime,'" & strYEARMON & "'+'01')),112))"
            strSQL = strSQL & " 	GROUP BY B.CLIENTCODE,B.SUBSEQ"
            strSQL = strSQL & " ) SUBDATA3 "
            strSQL = strSQL & " ON SUBDATA1.CLIENTCODE = SUBDATA3.CLIENTCODE"
            strSQL = strSQL & " AND SUBDATA1.SUBSEQ = SUBDATA3.SUBSEQ"
            strSQL = strSQL & " LEFT JOIN "
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT"
            strSQL = strSQL & " 	SUM(ADJAMT) ADJAMT,"
            strSQL = strSQL & " 	CLIENTCODE,"
            strSQL = strSQL & " 	SUBSEQ"
            strSQL = strSQL & " 	FROM"
            strSQL = strSQL & " 	("
            strSQL = strSQL & " 	SELECT "
            strSQL = strSQL & " 	A.JOBNO,"
            strSQL = strSQL & " 	SUM(A.ADJAMT) ADJAMT,"
            strSQL = strSQL & " 	B.CLIENTCODE,"
            strSQL = strSQL & " 	B.SUBSEQ "
            strSQL = strSQL & " 	FROM PD_CLOSING_MST A "
            strSQL = strSQL & " 	LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO "
            strSQL = strSQL & " 	WHERE A.DIVFLAG = 'PREPAYMENT'"
            strSQL = strSQL & " 	AND A.YEARMON = '" & strYEARMON & "'"
            strSQL = strSQL & " 	GROUP BY A.JOBNO,B.CLIENTCODE,B.SUBSEQ"
            strSQL = strSQL & " 	) TEMP GROUP BY CLIENTCODE,SUBSEQ"
            strSQL = strSQL & " ) SUBDATA4"
            strSQL = strSQL & " ON SUBDATA1.CLIENTCODE = SUBDATA4.CLIENTCODE"
            strSQL = strSQL & " AND SUBDATA1.SUBSEQ = SUBDATA4.SUBSEQ"
            strSQL = strSQL & " LEFT JOIN"
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT "
            strSQL = strSQL & " 	SUM(A.ADJAMT) ADJAMT,"
            strSQL = strSQL & " 	B.CLIENTCODE,"
            strSQL = strSQL & " 	B.SUBSEQ "
            strSQL = strSQL & " 	FROM PD_CLOSING_MST A "
            strSQL = strSQL & " 	LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO "
            strSQL = strSQL & " 	WHERE A.DIVFLAG = 'ACCRUED'"
            strSQL = strSQL & " 	AND A.YEARMON = (convert(char(6), DATEADD(MM , -12, convert(smalldatetime,'" & strYEARMON & "'+'01')),112))"
            strSQL = strSQL & " 	GROUP BY B.CLIENTCODE,B.SUBSEQ"
            strSQL = strSQL & " ) SUBDATA5"
            strSQL = strSQL & " ON SUBDATA1.CLIENTCODE = SUBDATA5.CLIENTCODE"
            strSQL = strSQL & " AND SUBDATA1.SUBSEQ = SUBDATA5.SUBSEQ"
            strSQL = strSQL & " LEFT JOIN"
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT "
            strSQL = strSQL & " 	SUM(A.ADJAMT) ADJAMT,"
            strSQL = strSQL & " 	B.CLIENTCODE,"
            strSQL = strSQL & " 	B.SUBSEQ "
            strSQL = strSQL & " 	FROM PD_CLOSING_MST A "
            strSQL = strSQL & " 	LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO "
            strSQL = strSQL & " 	WHERE A.DIVFLAG = 'ACCRUED'"
            strSQL = strSQL & " 	AND A.YEARMON = '" & strYEARMON & "'"
            strSQL = strSQL & " 	GROUP BY B.CLIENTCODE,B.SUBSEQ"
            strSQL = strSQL & " ) SUBDATA6"
            strSQL = strSQL & " ON SUBDATA1.CLIENTCODE = SUBDATA6.CLIENTCODE"
            strSQL = strSQL & " AND SUBDATA1.SUBSEQ = SUBDATA6.SUBSEQ"
            strSQL = strSQL & " UNION ALL"
            strSQL = strSQL & " SELECT"
            strSQL = strSQL & " 'Z' CLIENTCODE,"
            strSQL = strSQL & " '합계' CLIENTNAME,"
            strSQL = strSQL & " '' SUBSEQ,"
            strSQL = strSQL & " '' SUBSEQNAME,"
            strSQL = strSQL & " SUM(ISNULL(SUBDATA2.AMT,0)) DEMANDAMT,"
            strSQL = strSQL & " SUM(ISNULL(SUBDATA1.ADJAMT,0)) ADJAMT,"
            strSQL = strSQL & " SUM(ISNULL(SUBDATA2.AMT,0)) - SUM(ISNULL(SUBDATA1.ADJAMT,0)) INCOM, "
            strSQL = strSQL & " CASE SUM(ISNULL(SUBDATA2.AMT,0)) WHEN 0 THEN 0 "
            strSQL = strSQL & " ELSE"
            strSQL = strSQL & " Round(((SUM(ISNULL(SUBDATA2.AMT,0))-(SUM(ISNULL(SUBDATA1.ADJAMT,0))))/SUM(ISNULL(SUBDATA2.AMT,0)))*100,2)"
            strSQL = strSQL & " END AS RATE,"
            strSQL = strSQL & " SUM(ISNULL(SUBDATA3.ADJAMT,0)) PRE_PREPAYMENT,"
            strSQL = strSQL & " SUM(ISNULL(SUBDATA4.ADJAMT,0)) THIS_PREPAYMENT,"
            strSQL = strSQL & " SUM(ISNULL(SUBDATA5.ADJAMT,0)) PRE_ACCRUED,"
            strSQL = strSQL & " SUM(ISNULL(SUBDATA6.ADJAMT,0)) THIS_ACCRUED,"
            strSQL = strSQL & " SUM(ISNULL(SUBDATA1.ADJAMT,0)) - SUM(ISNULL(SUBDATA3.ADJAMT,0)) + SUM(ISNULL(SUBDATA4.ADJAMT,0)) + SUM(ISNULL(SUBDATA5.ADJAMT,0)) - SUM(ISNULL(SUBDATA6.ADJAMT,0))THIS_CHARGE,999999 AS RANKTRANS"
            strSQL = strSQL & " FROM"
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT"
            strSQL = strSQL & " TEMPADATA.CLIENTCODE,"
            strSQL = strSQL & " TEMPADATA.SUBSEQ,"
            strSQL = strSQL & " ISNULL(TEMPADATA.ADJAMT,0)+ISNULL(TEMPBDATA.ACCAMT,0) ADJAMT"
            strSQL = strSQL & " FROM"
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT"
            strSQL = strSQL & " 		CLIENTCODE,"
            strSQL = strSQL & " 		SUBSEQ,"
            strSQL = strSQL & " 		SUM(ADJAMT) ADJAMT"
            strSQL = strSQL & " 		FROM"
            strSQL = strSQL & " 		("
            strSQL = strSQL & " 		SELECT"
            strSQL = strSQL & " 		B.CLIENTCODE,"
            strSQL = strSQL & " 		B.SUBSEQ,"
            strSQL = strSQL & " 		CASE ISNULL(A.ENDDAY,'') WHEN '' THEN 0 ELSE SUM(ISNULL(A.ADJAMT,0)) END ADJAMT"
            strSQL = strSQL & " 		FROM PD_EXE_HDR Z,PD_CLOSING_MST A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO"
            strSQL = strSQL & " 		AND A.YEARMON = '" & strYEARMON & "'"
            strSQL = strSQL & " 		WHERE Z.JOBNO = A.JOBNO"
            strSQL = strSQL & " 		GROUP BY B.CLIENTCODE,B.SUBSEQ,A.ENDDAY"
            strSQL = strSQL & " 		) SUBDATA"
            strSQL = strSQL & " 	 GROUP BY CLIENTCODE,SUBSEQ"
            strSQL = strSQL & " )  TEMPADATA LEFT JOIN "
            strSQL = strSQL & " (SELECT  SUM(ACCAMT) ACCAMT,CLIENTCODE,SUBSEQ FROM PD_EXE_HDR A,V_JOBNO B WHERE A.JOBNO = B.JOBNO AND ISNULL(A.ENDDAY,'') <> 0 GROUP BY CLIENTCODE,SUBSEQ) TEMPBDATA"
            strSQL = strSQL & " ON TEMPADATA.CLIENTCODE = TEMPBDATA.CLIENTCODE"
            strSQL = strSQL & " AND TEMPADATA.SUBSEQ = TEMPBDATA.SUBSEQ"
            strSQL = strSQL & " ) SUBDATA1 "
            strSQL = strSQL & " LEFT JOIN"
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT "
            strSQL = strSQL & " 	SUM(A.AMT) AMT,"
            strSQL = strSQL & "  	B.CLIENTCODE,"
            strSQL = strSQL & " 	B.SUBSEQ"
            strSQL = strSQL & " 	FROM PD_TAX_DTL A LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO "
            strSQL = strSQL & " 	WHERE TAXYEARMON = '" & strYEARMON & "'"
            strSQL = strSQL & " 	GROUP BY B.CLIENTCODE,B.SUBSEQ"
            strSQL = strSQL & " ) SUBDATA2"
            strSQL = strSQL & " ON SUBDATA1.CLIENTCODE = SUBDATA2.CLIENTCODE"
            strSQL = strSQL & " AND SUBDATA1.SUBSEQ = SUBDATA2.SUBSEQ"
            strSQL = strSQL & " LEFT JOIN "
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT "
            strSQL = strSQL & " 	SUM(A.ADJAMT) ADJAMT,"
            strSQL = strSQL & " 	B.CLIENTCODE,"
            strSQL = strSQL & " 	B.SUBSEQ "
            strSQL = strSQL & " 	FROM PD_CLOSING_MST A "
            strSQL = strSQL & " 	LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO "
            strSQL = strSQL & " 	WHERE A.DIVFLAG = 'PREPAYMENT'"
            strSQL = strSQL & " 	AND A.YEARMON =(convert(char(6), DATEADD(MM , -12, convert(smalldatetime,'" & strYEARMON & "'+'01')),112))"
            strSQL = strSQL & " 	GROUP BY B.CLIENTCODE,B.SUBSEQ"
            strSQL = strSQL & " ) SUBDATA3 "
            strSQL = strSQL & " ON SUBDATA1.CLIENTCODE = SUBDATA3.CLIENTCODE"
            strSQL = strSQL & " AND SUBDATA1.SUBSEQ = SUBDATA3.SUBSEQ"
            strSQL = strSQL & " LEFT JOIN "
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT"
            strSQL = strSQL & " 	SUM(ADJAMT) ADJAMT,"
            strSQL = strSQL & " 	CLIENTCODE,"
            strSQL = strSQL & " 	SUBSEQ"
            strSQL = strSQL & " 	FROM"
            strSQL = strSQL & " 	("
            strSQL = strSQL & " 	SELECT "
            strSQL = strSQL & " 	A.JOBNO,"
            strSQL = strSQL & " 	SUM(A.ADJAMT) ADJAMT,"
            strSQL = strSQL & " 	B.CLIENTCODE,"
            strSQL = strSQL & " 	B.SUBSEQ "
            strSQL = strSQL & " 	FROM PD_CLOSING_MST A "
            strSQL = strSQL & " 	LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO "
            strSQL = strSQL & " 	WHERE A.DIVFLAG = 'PREPAYMENT'"
            strSQL = strSQL & " 	AND A.YEARMON = '" & strYEARMON & "'"
            strSQL = strSQL & " 	GROUP BY A.JOBNO,B.CLIENTCODE,B.SUBSEQ"
            strSQL = strSQL & " 	) TEMP GROUP BY CLIENTCODE,SUBSEQ"
            strSQL = strSQL & " ) SUBDATA4"
            strSQL = strSQL & " ON SUBDATA1.CLIENTCODE = SUBDATA4.CLIENTCODE"
            strSQL = strSQL & " And SUBDATA1.SUBSEQ = SUBDATA4.SUBSEQ"
            strSQL = strSQL & " LEFT JOIN"
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT "
            strSQL = strSQL & " 	SUM(A.ADJAMT) ADJAMT,"
            strSQL = strSQL & " 	B.CLIENTCODE,"
            strSQL = strSQL & " 	B.SUBSEQ "
            strSQL = strSQL & " 	FROM PD_CLOSING_MST A "
            strSQL = strSQL & " 	LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO "
            strSQL = strSQL & " 	WHERE A.DIVFLAG = 'ACCRUED'"
            strSQL = strSQL & " 	AND A.YEARMON = (convert(char(6), DATEADD(MM , -12, convert(smalldatetime,'" & strYEARMON & "'+'01')),112))"
            strSQL = strSQL & " 	GROUP BY B.CLIENTCODE,B.SUBSEQ"
            strSQL = strSQL & " ) SUBDATA5"
            strSQL = strSQL & " ON SUBDATA1.CLIENTCODE = SUBDATA5.CLIENTCODE"
            strSQL = strSQL & " AND SUBDATA1.SUBSEQ = SUBDATA5.SUBSEQ"
            strSQL = strSQL & " LEFT JOIN"
            strSQL = strSQL & " ("
            strSQL = strSQL & " 	SELECT "
            strSQL = strSQL & " 	SUM(A.ADJAMT) ADJAMT,"
            strSQL = strSQL & " 	B.CLIENTCODE,"
            strSQL = strSQL & " 	B.SUBSEQ "
            strSQL = strSQL & " 	FROM PD_CLOSING_MST A "
            strSQL = strSQL & " 	LEFT JOIN V_JOBNO B ON A.JOBNO = B.JOBNO "
            strSQL = strSQL & " 	WHERE A.DIVFLAG = 'ACCRUED'"
            strSQL = strSQL & " 	AND A.YEARMON = '" & strYEARMON & "'"
            strSQL = strSQL & " 	GROUP BY B.CLIENTCODE,B.SUBSEQ"
            strSQL = strSQL & " ) SUBDATA6"
            strSQL = strSQL & " ON SUBDATA1.CLIENTCODE = SUBDATA6.CLIENTCODE"
            strSQL = strSQL & " AND SUBDATA1.SUBSEQ = SUBDATA6.SUBSEQ"

            Try
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
                ' ------ XML 데이터 조회
                'strXMLData = .mobjSCGLSql.SQLSelectXml(strSQL, intRowCnt, intColCnt)
                'Return strXMLData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_TOTAL")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function
    '===================================== 외주처별 정산현황
    Function SelectRtn_SETTLE(ByVal strInfoXML As String, _
                               ByRef intRowCnt As Integer, _
                               ByRef intColCnt As Integer, _
                               ByVal strPURCHASENO As String, _
                               ByVal strOUTSCODE As String, _
                               ByVal strOUTSNAME As String, _
                               ByVal strGUBN As String, _
                               ByVal strFrom As String, _
                               ByVal strTo As String) As Object

        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2, Con3, Con4 As String


        If strPURCHASENO <> "" Then Con1 = String.Format(" AND PURCHASENO = '{0}'", strPURCHASENO)
        If strOUTSCODE <> "" Then Con2 = String.Format(" AND OUTSCODE = '{0}'", strOUTSCODE)
        If strOUTSNAME <> "" Then Con3 = String.Format(" AND DBO.SC_GET_HIGHCUSTNAME_FUN(OUTSCODE) like '%{0}%'", strOUTSNAME)
        If strFrom <> "" And strTo <> "" Then
            Con4 = String.Format(" AND (ADJDAY BETWEEN '{0}' AND  '{1}')", strFrom, strTo)
        End If
        If strFrom <> "" And strTo = "" Then
            Con4 = String.Format(" AND (ADJDAY > '{0}')", strFrom)
        End If
        If strFrom = "" And strTo <> "" Then
            Con4 = String.Format(" AND (ADJDAY < '{0}')", strTo)
        End If




        strWhere = BuildFields(" ", Con1, Con2, Con3, Con4)
        If strGUBN = "DIV" Then
            strFormat = " SELECT "
            strFormat = strFormat & " 1 GBN, "
            strFormat = strFormat & " PURCHASENO,"
            strFormat = strFormat & " OUTSCODE,"
            strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(OUTSCODE) OUTSNAME,"
            strFormat = strFormat & " DBO.PD_ITEMCODENAME_FUN(ITEMCODE) ITEMNAME,"
            strFormat = strFormat & " JOBNO,"
            strFormat = strFormat & " DBO.PD_JOBNAME_FUN(JOBNO) JOBNAME,"
            strFormat = strFormat & " ADJAMT,"
            strFormat = strFormat & " ADJDAY,DENSE_RANK() OVER (ORDER BY PURCHASENO) AS RANKTRANS,CASE ISNULL(VOCHNO,'') WHEN '' THEN '미완료' WHEN '0' THEN '미완료' WHEN '1' THEN '완료' END AS VOCHNO"
            strFormat = strFormat & " FROM PD_EXE_DTL"
            strFormat = strFormat & " WHERE ISNULL(PURCHASENO,'') <> '' {0}"
            strFormat = strFormat & " UNION ALL"
            strFormat = strFormat & " SELECT  "
            strFormat = strFormat & " 2 GBN,"
            strFormat = strFormat & " PURCHASENO,"
            strFormat = strFormat & " '' OUTSCODE,"
            strFormat = strFormat & " '소계' OUTSNAME,"
            strFormat = strFormat & " '' ITEMNAME,"
            strFormat = strFormat & " '' JOBNO,"
            strFormat = strFormat & " '' JOBNAME,"
            strFormat = strFormat & " SUM(ADJAMT) ADJAMT,"
            strFormat = strFormat & " '' ADJDAY,99999 AS RANKTRANS,'' VOCHNO"
            strFormat = strFormat & " FROM PD_EXE_DTL"
            strFormat = strFormat & " WHERE ISNULL(PURCHASENO,'') <> '' {0}"
            strFormat = strFormat & " GROUP BY PURCHASENO"
            strFormat = strFormat & " ORDER BY 2,1"
        ElseIf strGUBN = "ALL" Then
            strFormat = " SELECT "
            strFormat = strFormat & " 1 GBN, "
            strFormat = strFormat & " PURCHASENO,"
            strFormat = strFormat & " OUTSCODE,"
            strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(OUTSCODE) OUTSNAME,"
            strFormat = strFormat & " DBO.PD_ITEMCODENAME_FUN(ITEMCODE) ITEMNAME,"
            strFormat = strFormat & " JOBNO,"
            strFormat = strFormat & " DBO.PD_JOBNAME_FUN(JOBNO) JOBNAME,"
            strFormat = strFormat & " ADJAMT,"
            strFormat = strFormat & " ADJDAY,DENSE_RANK() OVER (ORDER BY OUTSCODE) AS RANKTRANS,CASE ISNULL(VOCHNO,'') WHEN '' THEN '미완료' WHEN '0' THEN '미완료' WHEN '1' THEN '완료' END AS VOCHNO"
            strFormat = strFormat & " FROM PD_EXE_DTL"
            strFormat = strFormat & " WHERE ISNULL(PURCHASENO,'') <> '' {0}"
            strFormat = strFormat & " UNION ALL"
            strFormat = strFormat & " SELECT  "
            strFormat = strFormat & " 2 GBN,"
            strFormat = strFormat & " PURCHASENO,"
            strFormat = strFormat & " '' OUTSCODE,"
            strFormat = strFormat & " '합계' OUTSNAME,"
            strFormat = strFormat & " '' ITEMNAME,"
            strFormat = strFormat & " '' JOBNO,"
            strFormat = strFormat & " '' JOBNAME,"
            strFormat = strFormat & " SUM(ADJAMT) ADJAMT,"
            strFormat = strFormat & " '' ADJDAY,99999 AS RANKTRANS,'' VOCHNO"
            strFormat = strFormat & " FROM PD_EXE_DTL"
            strFormat = strFormat & " WHERE ISNULL(PURCHASENO,'') <> '' {0}"
            strFormat = strFormat & " GROUP BY PURCHASENO"
            strFormat = strFormat & " ORDER BY 2,1"
        End If



        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            strSQL = String.Format(strFormat, strWhere)
            Try
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
                ' ------ XML 데이터 조회
                'strXMLData = .mobjSCGLSql.SQLSelectXml(strSQL, intRowCnt, intColCnt)
                'Return strXMLData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_SETTLE")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

    '===================================== 배치프로그램 Log 
    Function SelectRtn_BATCH(ByVal strInfoXML As String, _
                             ByRef intRowCnt As Integer, _
                             ByRef intColCnt As Integer, _
                             ByVal strFrom As String, _
                             ByVal strTo As String, _
                             ByVal strERRORFLAG As String, _
                             ByVal strSYSTEMFLAG As String) As Object

        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2, Con3 As String


        If strFrom <> "" And strTo <> "" Then
            Con1 = String.Format(" AND (INPUTLOGDATE BETWEEN '{0}' AND  '{1}')", strFrom, strTo)
        End If
        If strFrom <> "" And strTo = "" Then
            Con1 = String.Format(" AND (INPUTLOGDATE > '{0}')", strFrom)
        End If
        If strFrom = "" And strTo <> "" Then
            Con1 = String.Format(" AND (INPUTLOGDATE < '{0}')", strTo)
        End If
        If strERRORFLAG <> "" Then Con2 = String.Format(" AND ERRORFLAG = '{0}'", strERRORFLAG)
        If strSYSTEMFLAG <> "" Then Con3 = String.Format(" AND SYSTEMFLAG = '{0}'", strSYSTEMFLAG)



        strWhere = BuildFields(" ", Con1, Con2, Con3)

        strFormat = "SELECT INPUTLOGDATE,MASSAGE,CASE ERRORFLAG WHEN 'F' THEN '작업실패' WHEN 'T' THEN '작업성공' END AS ERRORFLAG,"
        strFormat = strFormat & " CASE SYSTEMFLAG WHEN 'TV' THEN '위수탁전표처리' "
        strFormat = strFormat & " WHEN 'SV' THEN '수수료전표처리' "
        strFormat = strFormat & " WHEN 'PV' THEN '제작비전표처리' "
        strFormat = strFormat & " WHEN 'E' THEN '사용자정보처리' "
        strFormat = strFormat & " WHEN 'D' THEN '조직정보처리' "
        strFormat = strFormat & " WHEN 'C' THEN '거래처정보처리' END AS SYSTEMFLAG FROM SC_BATCH_MST WHERE 1=1 {0} order by INPUTLOGDATE"

        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            strSQL = String.Format(strFormat, strWhere)
            Try
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
                ' ------ XML 데이터 조회
                'strXMLData = .mobjSCGLSql.SQLSelectXml(strSQL, intRowCnt, intColCnt)
                'Return strXMLData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_BATCH")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function


    '===================================== 외주비 지급현황
    Function SelectRtn_PAYLIST(ByVal strInfoXML As String, _
                               ByRef intRowCnt As Integer, _
                               ByRef intColCnt As Integer, _
                               ByVal strFrom As String, _
                               ByVal strTo As String, _
                               ByVal strCUSTCODE As String, _
                               ByVal strCUSTNAME As String, _
                               ByVal strOUTSCODE As String, _
                               ByVal strOUTSNAME As String, _
                               ByVal strTAXFLAG As String) As Object

        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2, Con3, Con4, Con5, Con6 As String


        If strFrom <> "" And strTo <> "" Then
            Con1 = String.Format(" AND (ISNULL(REGDATE,'') BETWEEN '{0}' AND  '{1}')", strFrom, strTo)
        End If
        If strFrom <> "" And strTo = "" Then
            Con1 = String.Format(" AND (ISNULL(REGDATE,'') >= '{0}')", strFrom)
        End If
        If strFrom = "" And strTo <> "" Then
            Con1 = String.Format(" AND (ISNULL(REGDATE,'') <= '{0}')", strTo)
        End If

        If strCUSTCODE <> "" Then Con2 = String.Format(" AND DBO.PD_JOBCLIENTCODE_FUN(JOBNO) = '{0}'", strCUSTCODE)
        If strCUSTNAME <> "" Then Con3 = String.Format(" AND DBO.PD_JOBCLIENTNAME_FUN(JOBNO) like '%{0}%'", strCUSTNAME)
        If strOUTSCODE <> "" Then Con4 = String.Format(" AND OUTSCODE = '{0}'", strOUTSCODE)
        If strOUTSNAME <> "" Then Con5 = String.Format(" AND DBO.SC_GET_HIGHCUSTNAME_FUN(OUTSCODE) like '%{0}%'", strOUTSNAME)

        If strTAXFLAG <> "" Then
            If strTAXFLAG = "Y" Then
                Con6 = String.Format(" AND ISNULL(TAXDATE,'') <> '{0}'", strTAXFLAG)
            Else
                Con6 = String.Format(" AND ISNULL(TAXDATE,'') = '{0}'", strTAXFLAG)
            End If
        End If


        strWhere = BuildFields(" ", Con1, Con2, Con3, Con4, Con5, Con6)

        'strFormat = " SELECT 1 GBN,OUTSCODE, "
        'strFormat = strFormat & "DBO.SC_GET_HIGHCUSTNAME_FUN(OUTSCODE) OUTSNAME, "
        'strFormat = strFormat & "JOBNO, "
        'strFormat = strFormat & "DBO.PD_JOBNAME_FUN(JOBNO) JOBNAME, "
        'strFormat = strFormat & "DBO.PD_JOBCLIENTCODE_FUN(JOBNO) CLIENTCODE, "
        'strFormat = strFormat & "DBO.PD_JOBCLIENTNAME_FUN(JOBNO) CLIENTNAME, "
        'strFormat = strFormat & "ISNULL(ADJAMT,0) ADJAMT, "
        'strFormat = strFormat & "ISNULL(CONTRACTNO,'') CONTRACTNO, "
        'strFormat = strFormat & "SUBSTRING(taxdate,1,4) + '-' + SUBSTRING(taxdate,5,2) + '-' + SUBSTRING(taxdate,7,2) taxdate, "
        'strFormat = strFormat & "case when isnull(taxdate,'') = '' then '미발행' else '발행' end taxflag  "
        'strFormat = strFormat & "FROM PD_EXE_DTL WHERE 1=1 {0} "
        'strFormat = strFormat & "UNION ALL "
        'strFormat = strFormat & "SELECT 2 GBN,OUTSCODE, "
        'strFormat = strFormat & "DBO.SC_GET_HIGHCUSTNAME_FUN(OUTSCODE)+' 소계' OUTSNAME, "
        'strFormat = strFormat & "'' JOBNO, "
        'strFormat = strFormat & "'' JOBNAME, "
        'strFormat = strFormat & "'' CLIENTCODE, "
        'strFormat = strFormat & "'' CLIENTNAME, "
        'strFormat = strFormat & "SUM(ISNULL(ADJAMT,0)) ADJAMT, "
        'strFormat = strFormat & "ISNULL(CONTRACTNO,'') CONTRACTNO, "
        'strFormat = strFormat & "'' taxdate, "
        'strFormat = strFormat & "'' taxflag "
        'strFormat = strFormat & "FROM PD_EXE_DTL WHERE 1=1 {0} "
        'strFormat = strFormat & "GROUP BY OUTSCODE,CONTRACTNO "
        'strFormat = strFormat & "ORDER BY OUTSCODE,CONTRACTNO,GBN "



        strFormat = strFormat & " SELECT "
        strFormat = strFormat & " 1 GBN,"
        strFormat = strFormat & " A.OUTSCODE, "
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(A.OUTSCODE) OUTSNAME, "
        strFormat = strFormat & " A.JOBNO, "
        strFormat = strFormat & " DBO.PD_JOBNAME_FUN(A.JOBNO) JOBNAME, "
        strFormat = strFormat & " DBO.PD_JOBCLIENTCODE_FUN(A.JOBNO) CLIENTCODE, "
        strFormat = strFormat & " DBO.PD_JOBCLIENTNAME_FUN(A.JOBNO) CLIENTNAME, "
        strFormat = strFormat & " ISNULL(A.ADJAMT,0) ADJAMT, "
        strFormat = strFormat & " ISNULL(A.CONTRACTNO,'') CONTRACTNO, "
        strFormat = strFormat & " SUBSTRING(A.taxdate,1,4) + '-' + SUBSTRING(A.taxdate,5,2) + '-' + SUBSTRING(A.taxdate,7,2) taxdate, "
        strFormat = strFormat & " case when isnull(taxdate,'') = '' then '미발행' else '발행' end taxflag ,"
        strFormat = strFormat & " ISNULL(A.AMTFLAG,0) AMTFLAG, A.VOCHNO,B.DEMANDDAY,B.DOCUMENTDATE,"
        strFormat = strFormat & " DBO.SC_GET_CODENAME_FUN(B.PAYCODE) PAYCODE"
        strFormat = strFormat & " FROM PD_EXE_DTL A LEFT JOIN PD_VOCH_MST B"
        strFormat = strFormat & " ON A.VOCHNO = B.VOCHNO AND SUBSTRING(A.PURCHASENO,1,6) = B.TAXYEARMON "
        strFormat = strFormat & " AND CAST(SUBSTRING(A.PURCHASENO,7,4) AS INT) = B.TAXNO AND B.GBN = 'B'"
        strFormat = strFormat & " WHERE 1=1 "
        strFormat = strFormat & " {0} "
        strFormat = strFormat & " UNION ALL "
        strFormat = strFormat & " SELECT "
        strFormat = strFormat & " 2 GBN,OUTSCODE, "
        strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(OUTSCODE)+' 소계' OUTSNAME, "
        strFormat = strFormat & " '' JOBNO, "
        strFormat = strFormat & " '' JOBNAME, "
        strFormat = strFormat & " '' CLIENTCODE, "
        strFormat = strFormat & " '' CLIENTNAME, "
        strFormat = strFormat & " SUM(ISNULL(ADJAMT,0)) ADJAMT, "
        strFormat = strFormat & " ISNULL(CONTRACTNO,'') CONTRACTNO, "
        strFormat = strFormat & " '' taxdate, "
        strFormat = strFormat & " '' taxflag ,"
        strFormat = strFormat & " '' AMTFLAG,'' VOCHNO, '' DEMANDDAY,'' DOCUMENTDATE,'' PAYCODE"
        strFormat = strFormat & " FROM PD_EXE_DTL A LEFT JOIN PD_VOCH_MST B"
        strFormat = strFormat & " ON A.VOCHNO = B.VOCHNO AND SUBSTRING(A.PURCHASENO,1,6) = B.TAXYEARMON "
        strFormat = strFormat & " AND CAST(SUBSTRING(A.PURCHASENO,7,4) AS INT) = B.TAXNO AND B.GBN = 'B' "
        strFormat = strFormat & " WHERE 1=1"
        strFormat = strFormat & " {0} "
        strFormat = strFormat & " GROUP BY A.OUTSCODE,A.CONTRACTNO "
        strFormat = strFormat & " ORDER BY OUTSCODE,CONTRACTNO,GBN "


        'AND CAST(SUBSTRING(A.PURCHASENO,7,4) AS INT) = B.TAXNO AND B.GBN = 'B'

        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            strSQL = String.Format(strFormat, strWhere)
            Try
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
                ' ------ XML 데이터 조회
                'strXMLData = .mobjSCGLSql.SQLSelectXml(strSQL, intRowCnt, intColCnt)
                'Return strXMLData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".strFormat")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function
#End Region
    'PROJECTNO,PROJECTNM,CLIENTCODE,CLIENTSUBCODE,SUBSEQ,GROUPGBN,CREDAY,CPDEPTCD,CPEMPNO,MEMO
#Region "GROUP BLOCK : Entity Function Section"

#End Region
End Class

