
'****************************************************************************************
'Generated By  : Kim Tae Ho 
'시스템구분    : RMS/PD/Server Control Class
'실행   환경   : COM+ Service Server Package
'프로그램명    : ccPDCMPREESTLIST.vb
'기         능 : - 가견적관리
'특이  사항    : - CE 단 Query 복사 기능
'                -
'----------------------------------------------------------------------------------------
'HISTORY    :1) 2008.11.12 Kim Tae Ho
'            2) 
'****************************************************************************************

Imports System.Xml                  ' XML처리
Imports SCGLControl                 ' ControlClass의 Base Class
Imports SCGLUtil.cbSCGLConfig       ' ConfigurationClass
Imports SCGLUtil.cbSCGLErr          '오류처리 클래스
Imports SCGLUtil.cbSCGLXml          'XML처리 클래스
Imports SCGLUtil.cbSCGLUtil         '기타유틸리티 클래스
Imports ePDCO                       '엔터티 추가

' 엔티티 클래스 사용시 해당 엔티티 클래스의 프로젝트를 참조한 후 Imports 하십시요. 
' Imports 엔티티프로젝트
Public Class ccPDCOOUTSLIST
    Inherits ccControl
#Region "GROUP BLOCK : 전역 또는 모듈레벨의 변수/상수 선언"
    Private CLASS_NAME = "ccPDCOOUTSLIST"                  '자신의 클래스명
    Private mobjcePD_EXE_HDR As ePDCO.cePD_EXE_HDR            '외주정산 기본내역
    Private mobjcePD_EXE_DTL As ePDCO.cePD_EXE_DTL            '외주정산 상세내역
    Private mobjcePD_ACC_MST As ePDCO.cePD_ACC_MST            '회계진행비 상세내역 투입
    'Private Const .DBConnStr = "Provider=SQLOLEDB;Data Source=10.110.10.86;Initial Catalog=MCDEV;DSN=MCDEV;UID=devadmin;Pwd=password"
#End Region

#Region "GROUP BLOCK : Function Section"
    '=============== 외주처별정산 조회 ==>> 매입집계 조회
    Public Function SelectRtn(ByVal strInfoXML As String, _
                              ByRef intRowCnt As Integer, _
                              ByRef intColCnt As Integer, _
                              ByVal strOUTSCODE As String, _
                              ByVal strOUTSNAME As String, _
                              ByVal strFROM As String, _
                              ByVal strTO As String, _
                              ByVal strGUBN As String, _
                              ByVal strPOPUPTYPE As String) As Object


        Dim strCols As String         '컬럼변수
        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2, Con3, Con4 As String

        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체

            If strOUTSCODE <> "" Then Con1 = String.Format(" AND (C.OUTSCODE = '{0}')", strOUTSCODE)
            If strOUTSNAME <> "" Then Con2 = String.Format(" AND (DBO.SC_GET_HIGHCUSTNAME_FUN(C.OUTSCODE) LIKE '%{0}%')", strOUTSNAME)

            If strPOPUPTYPE = "REG" Then
                If strFROM <> "" And strTO <> "" Then
                    Con3 = String.Format(" AND (C.REGDATE BETWEEN '{0}' AND  '{1}')", strFROM, strTO)
                End If
                If strFROM <> "" And strTO = "" Then
                    Con3 = String.Format(" AND (C.REGDATE >= '{0}')", strFROM)
                End If
                If strFROM = "" And strTO <> "" Then
                    Con3 = String.Format(" AND (C.REGDATE <= '{0}')", strTO)
                End If

            Else
                If strFROM <> "" And strTO <> "" Then
                    Con3 = String.Format(" AND (C.ADJDAY BETWEEN '{0}' AND  '{1}')", strFROM, strTO)
                End If
                If strFROM <> "" And strTO = "" Then
                    Con3 = String.Format(" AND (C.ADJDAY >= '{0}')", strFROM)
                End If
                If strFROM = "" And strTO <> "" Then
                    Con3 = String.Format(" AND (C.ADJDAY <= '{0}')", strTO)
                End If

            End If

            If strGUBN = "T" Or strGUBN = "F" Then
                If strGUBN <> "" Then Con4 = String.Format(" AND (CASE ISNULL(C.PURCHASENO,'') WHEN '' THEN 'F' ELSE 'T' END  = '{0}')", strGUBN)
            ElseIf strGUBN = "V" Then
                If strGUBN <> "" Then Con4 = " AND ISNULL(C.VOCHNO,'') <> ''  AND ISNULL(C.CONFIRMFLAG,'0') = '0' "
            Else
                If strGUBN <> "" Then Con4 = " AND ISNULL(C.VOCHNO,'') <> ''  AND ISNULL(C.CONFIRMFLAG,'0') = '1' "
            End If

            strWhere = BuildFields(" ", Con1, Con2, Con3, Con4)

            'strCols = "0 CHK,"
            'strCols = strCols & " B.PROJECTNM, "
            'strCols = strCols & " A.JOBNAME, "
            'strCols = strCols & " A.JOBNO, "
            'strCols = strCols & " C.SEQ, "
            'strCols = strCols & " DBO.SC_GET_HIGHCUSTNAME_FUN(B.CLIENTCODE) CLIENTNAME, "
            'strCols = strCols & " DBO.SC_GET_HIGHCUSTNAME_FUN(C.OUTSCODE) OUTSNAME, "
            'strCols = strCols & " ISNULL(C.ATTR05,'') ITEMNAME, "
            'strCols = strCols & " ISNULL(C.ADJAMT,0) ADJAMT, "
            'strCols = strCols & " C.PURCHASENO,"
            'strCols = strCols & " A.REQDAY,DBO.PD_JOBNO_DEMANDDAY_FUN(A.JOBNO) DEMANDDAY, C.ADJDAY, C.TAXDATE ,'' ENDDAY,C.VOCHNO,C.CONFIRMFLAG,"
            'strCols = strCols & " DENSE_RANK() OVER (ORDER BY C.JOBNO,C.OUTSCODE,C.ADJDAY,C.VATCODE) AS OUTSRANK"

            'strFormat = "SELECT {0} FROM PD_JOBNO A,PD_PONO B,PD_EXE_DTL C,PD_EXE_HDR D WHERE A.PROJECTNO = B.PROJECTNO AND A.JOBNO = C.JOBNO AND C.JOBNO = D.JOBNO {1} ORDER BY A.JOBNO ,A.REQDAY"

            strFormat = strFormat & " SELECT"
            strFormat = strFormat & " 0 CHK,"
            strFormat = strFormat & " B.PROJECTNM, "
            strFormat = strFormat & " A.JOBNAME, "
            strFormat = strFormat & " A.JOBNO, "
            strFormat = strFormat & " C.SEQ, "
            strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(B.CLIENTCODE) CLIENTNAME, "
            strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(C.OUTSCODE) OUTSNAME, "
            strFormat = strFormat & " C.STD ITEMNAME, "
            strFormat = strFormat & " ISNULL(C.ADJAMT,0) ADJAMT, "
            strFormat = strFormat & " C.PURCHASENO,"
            strFormat = strFormat & " E.POSTINGDATE,"
            strFormat = strFormat & " E.DEMANDDAY DEMANDDATE,"
            strFormat = strFormat & " A.REQDAY,DBO.PD_JOBNO_DEMANDDAY_FUN(A.JOBNO) DEMANDDAY, C.ADJDAY, C.TAXDATE ,'' ENDDAY,C.VOCHNO,C.CONFIRMFLAG,"
            strFormat = strFormat & " DENSE_RANK() OVER (ORDER BY C.JOBNO,C.OUTSCODE,C.ADJDAY,C.VATCODE) AS OUTSRANK"
            strFormat = strFormat & " FROM PD_JOBNO A "
            strFormat = strFormat & " INNER JOIN PD_PONO B ON A.PROJECTNO = B.PROJECTNO  "
            strFormat = strFormat & " INNER JOIN PD_EXE_DTL C ON A.JOBNO = C.JOBNO  "
            strFormat = strFormat & " INNER JOIN PD_EXE_HDR D ON C.JOBNO = D.JOBNO"
            strFormat = strFormat & " LEFT JOIN ("
            strFormat = strFormat & " 	SELECT"
            strFormat = strFormat & " 	POSTINGDATE, DEMANDDAY,TAXYEARMON, TAXNO,VOCHNO, GBN"
            strFormat = strFormat & " 	FROM PD_VOCH_MST"
            strFormat = strFormat & " 	WHERE 1=1"
            strFormat = strFormat & " )E ON SUBSTRING(C.PURCHASENO,1,6) = E.TAXYEARMON AND SUBSTRING(C.PURCHASENO,7,4) = DBO.LPAD(E.TAXNO,4,0) AND C.VOCHNO = E.VOCHNO "
            strFormat = strFormat & " WHERE  1=1"
            strFormat = strFormat & " {0} "
            strFormat = strFormat & " ORDER BY A.JOBNO ,A.REQDAY"


            strSQL = String.Format(strFormat, strWhere)
            Try
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
                ' ------ XML 데이터 조회
                'strXMLData = .mobjSCGLSql.SQLSelectXml(strSQL, intRowCnt, intColCnt)
                'Return strXMLData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function


    '  '매입집계 최초저장처리
    Public Function ProcessRtn(ByVal strInfoXML As String, _
                               ByVal vntData As Object, _
                               ByVal strYEARMON As String, _
                               ByVal intColFlag As Integer) As Integer '데이터 INSERT/UPDATE


        Dim intRtn As Integer '결과값 변수
        Dim i, intColCnt, intRows As Integer '루프, 컬럼Cnt, 로우Cnt 변수
        Dim strPURCHASENO As String
        Dim intCnt As Integer
        Dim strADJDAY As String
        Dim strTAXDATE As String
        Dim strJOBNO As String
        Dim strSEQ As Double
        Dim strSQL As String

        SetConfig(strInfoXML) '기본정보 Setting

        With mobjSCGLConfig '기본정보를 가지고 있는 Config 개체
            Try
                'XML Element 변수 선언 (strMasterXML을 변환)
                Dim xmlRoot As XmlElement

                mobjcePD_EXE_DTL = New cePD_EXE_DTL(mobjSCGLConfig)
                'DB접속 및 트랜잭션 시작
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                .mobjSCGLSql.SQLBeginTrans()

                If IsArray(vntData) Then
                    intColCnt = UBound(vntData, 1) : intRows = UBound(vntData, 2)
                    For intCnt = 1 To intColFlag
                        For i = 1 To intRows
                            '인서트
                            strPURCHASENO = SelectRtn_SEQNO(strYEARMON)
                            If GetElement(vntData, "CHK", intColCnt, i, OPTIONAL_STR) = "1" And GetElement(vntData, "OUTSRANK", intColCnt, i, OPTIONAL_STR) = intCnt Then

                                If GetElement(vntData, "ADJDAY", intColCnt, i, OPTIONAL_STR) <> "" Then strADJDAY = GetElement(vntData, "ADJDAY", intColCnt, i, OPTIONAL_STR).SUBSTRING(0, 4) & GetElement(vntData, "ADJDAY", intColCnt, i, OPTIONAL_STR).SUBSTRING(5, 2) & GetElement(vntData, "ADJDAY", intColCnt, i, OPTIONAL_STR).SUBSTRING(8, 2)
                                If GetElement(vntData, "TAXDATE", intColCnt, i, OPTIONAL_STR) <> "" Then strTAXDATE = GetElement(vntData, "TAXDATE", intColCnt, i, OPTIONAL_STR).SUBSTRING(0, 4) & GetElement(vntData, "TAXDATE", intColCnt, i, OPTIONAL_STR).SUBSTRING(5, 2) & GetElement(vntData, "TAXDATE", intColCnt, i, OPTIONAL_STR).SUBSTRING(8, 2)

                                strJOBNO = GetElement(vntData, "JOBNO", intColCnt, i, OPTIONAL_STR)
                                strSEQ = GetElement(vntData, "SEQ", intColCnt, i, OPTIONAL_NUM, True)

                                '정산년월과 번호 EXEDTL에 업데이트
                                strSQL = "UPDATE PD_EXE_DTL SET PURCHASENO = '" & strPURCHASENO & "',ADJDAY = '" & strADJDAY & "',TAXDATE='" & strTAXDATE & "' WHERE JOBNO = '" & strJOBNO & "' AND SEQ =" & strSEQ
                                intRtn = mobjcePD_EXE_DTL.UpdateRtn_PurchaseNo(strSQL)
                            End If
                        Next
                    Next
                End If
                .mobjSCGLSql.SQLCommitTrans()
                Return intRtn
            Catch err As Exception
                '트랜잭션RollBack 및 오류 전송
                .mobjSCGLSql.SQLRollbackTrans()
                Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn")
            Finally
                'Resource해제
                .mobjSCGLSql.SQLDisconnect()
                mobjcePD_EXE_DTL.Dispose()
            End Try
        End With
    End Function
    '============== 매입집계 내역 처리
    Public Function ProcessRtn_DTL(ByVal vntData As Object, _
                                   ByVal strYEARMON As String) As Integer '데이터 INSERT/UPDATE
        Dim intRtn As Integer
        Dim i, intColCnt, intRows As Integer
        Dim lngSEQ As Double
        Dim strPURCHASENO As String
        Dim strPRECODE As String
        Dim strADJDAY As String
        Dim strGROUPGBN
        Dim strJOBNO As String
        Dim strSEQ As Double
        Dim strSQL As String
        With mobjSCGLConfig
            Try

                If IsArray(vntData) Then
                    '''사용할 Entity 개체생성(Config 정보를 넘겨생성)
                    mobjcePD_EXE_DTL = New cePD_EXE_DTL(mobjSCGLConfig)
                    '''vntData의 컬럼수, 로우수를 변수입력
                    intColCnt = UBound(vntData, 1) : intRows = UBound(vntData, 2)

                    strPURCHASENO = SelectRtn_SEQNO(strYEARMON)

                    For i = 1 To intRows
                        '인서트
                        If GetElement(vntData, "CHK", intColCnt, i, OPTIONAL_STR) = "1" Then
                            If GetElement(vntData, "ADJDAY", intColCnt, i, OPTIONAL_STR) <> "" Then strADJDAY = GetElement(vntData, "ADJDAY", intColCnt, i, OPTIONAL_STR).SUBSTRING(0, 4) & GetElement(vntData, "ADJDAY", intColCnt, i, OPTIONAL_STR).SUBSTRING(5, 2) & GetElement(vntData, "ADJDAY", intColCnt, i, OPTIONAL_STR).SUBSTRING(8, 2)

                            strJOBNO = GetElement(vntData, "JOBNO", intColCnt, i, OPTIONAL_STR)
                            strSEQ = GetElement(vntData, "SEQ", intColCnt, i, OPTIONAL_NUM, True)


                            strSQL = "UPDATE PD_EXE_DTL SET PURCHASENO = '" & strPURCHASENO & "',ADJDAY = '" & strADJDAY & "' WHERE JOBNO = '" & strJOBNO & "' AND SEQ =" & strSEQ
                            intRtn = mobjcePD_EXE_DTL.UpdateRtn_PurchaseNo(strSQL)
                        End If
                    Next
                End If

                Return intRows
            Catch err As Exception

                Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn_DTL")
            Finally

                mobjcePD_EXE_DTL.Dispose()
            End Try
        End With
    End Function
    '매입집계취소 최초저장처리
    Public Function ProcessRtn_Cancel(ByVal strInfoXML As String, _
                                      ByVal vntData As Object, _
                                      ByVal strYEARMON As String) As Integer '데이터 INSERT/UPDATE
        Dim intRtn As Integer '결과값 변수
        Dim i, intColCnt, intRows As Integer '루프, 컬럼Cnt, 로우Cnt 변수

        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보를 가지고 있는 Config 개체
            Try
                'XML Element 변수 선언 (strMasterXML을 변환)
                Dim xmlRoot As XmlElement


                'DB접속 및 트랜잭션 시작
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                .mobjSCGLSql.SQLBeginTrans()
                'Master 데이터 처리


                'Detail 데이터 처리
                If IsArray(vntData) Then
                    intRtn = ProcessRtn_Cancel_DTL(vntData, strYEARMON)
                End If
                .mobjSCGLSql.SQLCommitTrans()
                Return intRtn
            Catch err As Exception
                '트랜잭션RollBack 및 오류 전송
                .mobjSCGLSql.SQLRollbackTrans()
                Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn_Cancel")
            Finally
                'Resource해제
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function


    '============== 매입집계 취소 내역처리 
    Public Function ProcessRtn_Cancel_DTL(ByVal vntData As Object, _
                                   ByVal strYEARMON As String) As Integer '데이터 INSERT/UPDATE
        Dim intRtn As Integer
        Dim i, intColCnt, intRows As Integer
        Dim lngSEQ As Double
        Dim strPURCHASENO As String
        Dim strPRECODE As String
        Dim strADJDAY As String
        Dim strGROUPGBN
        Dim strJOBNO As String
        Dim strSEQ As Double
        Dim strSQL As String
        With mobjSCGLConfig
            Try

                If IsArray(vntData) Then
                    '''사용할 Entity 개체생성(Config 정보를 넘겨생성)
                    mobjcePD_EXE_DTL = New cePD_EXE_DTL(mobjSCGLConfig)
                    '''vntData의 컬럼수, 로우수를 변수입력
                    intColCnt = UBound(vntData, 1) : intRows = UBound(vntData, 2)

                    For i = 1 To intRows
                        '인서트
                        If GetElement(vntData, "CHK", intColCnt, i, OPTIONAL_STR) = "1" Then


                            strJOBNO = GetElement(vntData, "JOBNO", intColCnt, i, OPTIONAL_STR)
                            strSEQ = GetElement(vntData, "SEQ", intColCnt, i, OPTIONAL_NUM, True)


                            strSQL = "UPDATE PD_EXE_DTL SET PURCHASENO = '',ADJDAY = '' WHERE JOBNO = '" & strJOBNO & "' AND SEQ =" & strSEQ
                            intRtn = mobjcePD_EXE_DTL.UpdateRtn_PurchaseNo(strSQL)
                        End If
                    Next
                End If

                Return intRows
            Catch err As Exception

                Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn_Cancel_DTL")
            Finally

                mobjcePD_EXE_DTL.Dispose()
            End Try
        End With
    End Function


    '============== 매입집계 번호 생성
    Public Function SelectRtn_SEQNO(ByVal strYEARMON As String) As String
        '여기부터 단순조회
        Dim strSQL, strFormat, strRtn As String
        'SetConfig(strInfoXML) '기본정보 Setting
        Dim strPRECODE As String
        With mobjSCGLConfig '기본정보 Config 개체

            Try
                strSQL = "Select '" & strYEARMON & "'+isnull(dbo.lpad(cast(cast(substring(max(purchaseno),7,4) as numeric)+1 as varchar(20)),4,0),'0001') from pd_exe_dtl where substring(purchaseno,1,6) = '" & strYEARMON & "'"
                strRtn = .mobjSCGLSql.SQLSelectOneScalar(strSQL)
                Return strRtn
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_SEQNO")
            Finally
            End Try
        End With
        '여기까지 단순조회
    End Function

    '매입전표 - 외주비 정산일 완료 일 경우 매입전표 확정을 하여 SAP 처리가 되었는지 안되어있는지를 구별 할수 있다.
    Public Function ProcessRtn_Voch(ByVal strInfoXML As String, _
                                    ByVal vntData As Object) As Integer '데이터 INSERT/UPDATE
        Dim intRtn As Integer '결과값 변수
        Dim i, intColCnt, intRows As Integer '루프, 컬럼Cnt, 로우Cnt 변수
        Dim strVOCHNO As String
        Dim strJOBNO As String
        Dim strSEQ As String
        Dim strSQL As String
        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보를 가지고 있는 Config 개체
            Try
                'XML Element 변수 선언 (strMasterXML을 변환)
                Dim xmlRoot As XmlElement


                'DB접속 및 트랜잭션 시작
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                .mobjSCGLSql.SQLBeginTrans()
                'Master 데이터 처리


                'Detail 데이터 처리
                If IsArray(vntData) Then
                    mobjcePD_EXE_DTL = New cePD_EXE_DTL(mobjSCGLConfig)
                    intColCnt = UBound(vntData, 1) : intRows = UBound(vntData, 2)

                    For i = 1 To intRows
                        '인서트
                        strVOCHNO = GetElement(vntData, "VOCHNO", intColCnt, i, OPTIONAL_STR)
                        strSEQ = GetElement(vntData, "SEQ", intColCnt, i, OPTIONAL_STR)
                        strJOBNO = GetElement(vntData, "JOBNO", intColCnt, i, OPTIONAL_STR)

                        strSQL = "UPDATE PD_EXE_DTL SET VOCHNO = '" & strVOCHNO & "' WHERE JOBNO = '" & strJOBNO & "' AND SEQ =" & strSEQ
                        intRtn = mobjcePD_EXE_DTL.UpdateRtn_VochNo(strSQL)
                    Next
                End If
                .mobjSCGLSql.SQLCommitTrans()
                Return intRtn
            Catch err As Exception
                '트랜잭션RollBack 및 오류 전송
                .mobjSCGLSql.SQLRollbackTrans()
                Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn_Voch")
            Finally
                'Resource해제
                .mobjSCGLSql.SQLDisconnect()
                mobjcePD_EXE_DTL.Dispose()
            End Try
        End With
    End Function

    '승인 저장로직
    Public Function ProcessRtn_Confirm(ByVal strInfoXML As String, _
                                       ByVal vntData As Object) As Integer '데이터 INSERT/UPDATE
        Dim intRtn As Integer '결과값 변수
        Dim i, intColCnt, intRows As Integer '루프, 컬럼Cnt, 로우Cnt 변수
        Dim strVOCHNO As String
        Dim strJOBNO As String
        Dim strCONFIRMFLAG As String
        Dim strSEQ As String
        Dim strSQL As String

        SetConfig(strInfoXML) '기본정보 Setting

        With mobjSCGLConfig '기본정보를 가지고 있는 Config 개체
            Try
                'DB접속 및 트랜잭션 시작
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                .mobjSCGLSql.SQLBeginTrans()

                If IsArray(vntData) Then
                    mobjcePD_EXE_DTL = New cePD_EXE_DTL(mobjSCGLConfig)
                    intColCnt = UBound(vntData, 1) : intRows = UBound(vntData, 2)

                    For i = 1 To intRows
                        strSEQ = GetElement(vntData, "SEQ", intColCnt, i, OPTIONAL_STR)
                        strJOBNO = GetElement(vntData, "JOBNO", intColCnt, i, OPTIONAL_STR)
                        strCONFIRMFLAG = GetElement(vntData, "CONFIRMFLAG", intColCnt, i, OPTIONAL_STR)

                        strSQL = "UPDATE PD_EXE_DTL SET CONFIRMFLAG = '" & strCONFIRMFLAG & "' WHERE JOBNO = '" & strJOBNO & "' AND SEQ =" & strSEQ
                        intRtn = mobjcePD_EXE_DTL.UpdateRtn_Confirm(strSQL)
                    Next
                End If
                .mobjSCGLSql.SQLCommitTrans()
                Return intRtn
            Catch err As Exception
                '트랜잭션RollBack 및 오류 전송
                .mobjSCGLSql.SQLRollbackTrans()
                Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn_Confirm")
            Finally
                'Resource해제
                .mobjSCGLSql.SQLDisconnect()
                mobjcePD_EXE_DTL.Dispose()
            End Try
        End With
    End Function

    '=============== 최초 슈퍼관리자 여부 체크 (김노연 팀장님 께서 만 처리할수 있는 부분 추가)
    Public Function SelectRtn_USER(ByVal strInfoXML As String, _
                                   ByRef intRowCnt As Integer, _
                                   ByRef intColCnt As Integer) As Object

        Dim strCols As String        '컬럼변수
        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String         'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String     'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1 As String           '조건 String 변수
        Dim strUSER As String



        SetConfig(strInfoXML) '기본정보 Setting

        strUSER = mobjSCGLConfig.WRKUSR
        With mobjSCGLConfig '기본정보 Config 개체

            strSQL = "SELECT CC_CODE,MANAGER FROM SC_EMPLOYEE_MST WHERE EMPNO ='" & strUSER & "' AND  '" & strUSER & "' IN ('radmin','00010305')"
            Try
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData

            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_USER")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function
#End Region

#Region "GROUP BLOCK : Entity Function Section"

    Private Function UpdateRtn_ACCLIST(ByVal vntData As Object, _
                                       ByVal intColCnt As Integer, _
                                       ByVal intRow As Integer, _
                                       ByVal strACCDAY As String) As Integer

        Dim intRtn As Integer
        'JOBNO|SEQ|OUTSCODE|OUTSNAME|AMT|BREAKDOWN|ACCDAY
        intRtn = mobjcePD_ACC_MST.UpdateDo( _
                                       GetElement(vntData, "JOBNO", intColCnt, intRow), _
                                       GetElement(vntData, "SEQ", intColCnt, intRow, NULL_NUM, True), _
                                       GetElement(vntData, "AMT", intColCnt, intRow, NULL_NUM, True), _
                                       GetElement(vntData, "BREAKDOWN", intColCnt, intRow), _
                                       strACCDAY, _
                                       GetElement(vntData, "ATTR01", intColCnt, intRow), _
                                       GetElement(vntData, "ATTR02", intColCnt, intRow), _
                                       GetElement(vntData, "ATTR03", intColCnt, intRow), _
                                       GetElement(vntData, "ATTR04", intColCnt, intRow), _
                                       GetElement(vntData, "ATTR05", intColCnt, intRow), _
                                       GetElement(vntData, "ATTR06", intColCnt, intRow, NULL_NUM, True), _
                                       GetElement(vntData, "ATTR07", intColCnt, intRow, NULL_NUM, True), _
                                       GetElement(vntData, "AT  TR08", intColCnt, intRow, NULL_NUM, True), _
                                       GetElement(vntData, "ATTR09", intColCnt, intRow, NULL_NUM, True), _
                                       GetElement(vntData, "ATTR10", intColCnt, intRow, NULL_NUM, True))
        Return intRtn
    End Function



#End Region
End Class
