'****************************************************************************************
'Generated By  : 황덕수
'시스템구분    : RMS/PD/Server Control Class
'실행   환경   : COM+ Service Server Package
'프로그램명    : ccPDCMJOB.vb
'기         능 : - JOB List 조회
'특이  사항    : - 
'                -
'----------------------------------------------------------------------------------------
'HISTORY    :1) 2009.09.21 황덕수
'            2) 
'****************************************************************************************

Imports System.Xml                  ' XML처리
Imports SCGLControl                 ' ControlClass의 Base Class
Imports SCGLUtil.cbSCGLConfig       ' ConfigurationClass
Imports SCGLUtil.cbSCGLErr          '오류처리 클래스
Imports SCGLUtil.cbSCGLXml          'XML처리 클래스
Imports SCGLUtil.cbSCGLUtil         '기타유틸리티 클래스
Imports ePDCO                       '엔터티 추가

' 엔티티 클래스 사용시 해당 엔티티 클래스의 프로젝트를 참조한 후 Imports 하십시요. 
' Imports 엔티티프로젝트
Public Class ccPDCOJOB
    Inherits ccControl
#Region "GROUP BLOCK : 전역 또는 모듈레벨의 변수/상수 선언"
    Private CLASS_NAME = "ccPDCOJOBNO"                  '자신의 클래스명
    Private mobjcePD_JOBNO As ePDCO.cePD_JOBNO             '사용할 Entity 변수 선언
    Private mobjcePD_DIVAMT As ePDCO.cePD_DIVAMT
    'Private Const .DBConnStr = "Provider=SQLOLEDB;Data Source=10.110.10.86;Initial Catalog=MCDEV;DSN=MCDEV;UID=devadmin;Pwd=password"
#End Region

#Region "GROUP BLOCK : Function Section"
    '콤보타입가져오기
    Public Function GetDataType(ByVal strInfoXML As String, _
                                ByRef intRowCnt As Integer, _
                                ByRef intColCnt As Integer, _
                                ByVal strCombo As String) As Object



        Dim strSQL, strFormat, strSelFields As String
        Dim vntData As Object
        Dim strWhere
        Dim strSubWhere
        'Combo 구분자 [strCombo] --------------------------------
        'JOBGUBN : 좝구분, JOBBASE : 청구기준, CREGUBN : 제작구분, CREPART : 제작종류, 
        Select Case strCombo
            Case ("JOBGUBN")
                strWhere = "PD_JOBKIND"
            Case ("JOBBASE")
                strWhere = "PD_JOBBASE"
            Case ("CREGUBN")
                strWhere = "PD_CREGUBN"
            Case ("CREPART")
                strWhere = "PD_GRAPHICKIND"
            Case ("ENDFLAG")
                strWhere = "PD_ENDFLAG"
            Case ("PONOGUBN")
                strWhere = "PD_PONOGROUP"
            Case ("USEFLAG")
                strWhere = "PD_USEFLAG"
        End Select


        SetConfig(strInfoXML)   '기본정보 설정

        '조회 필드 설정
        strSelFields = "CODE,CODE_NAME,SORT_SEQ"

        'SQL문 생성
        strSubWhere = "SELECT '' CODE,'전체' CODE_NAME,0 SORT_SEQ UNION ALL "

        strFormat = strSubWhere & " SELECT {0} " & _
                    "FROM SC_CODE " & _
                    "WHERE CLASS_CODE = '" & strWhere & "' " & _
                    "ORDER BY SORT_SEQ "

        With mobjSCGLConfig
            strSQL = String.Format(strFormat, strSelFields)

            ''데이터 조회
            Try
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt)
                Return vntData
            Catch err As Exception
                Throw RaiseSysErr(err, CLASS_NAME & ".GetDataType")
            Finally
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

    ' =============== JOBNO 조회
    Public Function SelectRtn(ByVal strInfoXML As String, _
                              ByRef intRowCnt As Integer, _
                              ByRef intColCnt As Integer, _
                              ByVal strFROM As String, _
                              ByVal strTO As String, _
                              ByVal strCLIENTCODE As String, _
                              ByVal strCLIENTNAME As String, _
                              ByVal strENDFLAG As String, _
                              ByVal strSEARCH As String, _
                              ByVal strJOBTYPE As String, _
                              ByVal strEMPNO As String, _
                              ByVal strEMPNAME As String) As String

        Dim strCols As String         '컬럼변수
        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2, Con3, Con4, Con5, Con6, Con7

        SetConfig(strInfoXML) '기본정보 Setting

        With mobjSCGLConfig '기본정보 Config 개체
            Try
                If strFROM <> "" And strTO <> "" Then
                    Con1 = String.Format(" AND (A.REQDAY BETWEEN '{0}' AND  '{1}')", strFROM, strTO)
                End If
                If strFROM <> "" And strTO = "" Then
                    Con1 = String.Format(" AND (A.REQDAY >= '{0}')", strFROM)
                End If
                If strFROM = "" And strTO <> "" Then
                    Con1 = String.Format(" AND (A.REQDAY <= '{0}')", strTO)
                End If

                If strSEARCH = "1" Then
                    If strCLIENTCODE <> "" Then Con2 = String.Format(" AND (CASE ISNULL(B.CLIENTCODE,'') WHEN '' THEN C.CLIENTCODE ELSE B.CLIENTCODE END = '{0}')", strCLIENTCODE)
                Else
                    If strCLIENTCODE <> "" Then Con2 = String.Format(" AND (A.JOBNO = '{0}')", strCLIENTCODE)
                End If

                If strSEARCH = "1" Then
                    If strCLIENTNAME <> "" Then Con3 = String.Format(" AND (DBO.SC_GET_HIGHCUSTNAME_FUN(CASE ISNULL(B.CLIENTCODE,'') WHEN '' THEN C.CLIENTCODE ELSE B.CLIENTCODE END) like '%{0}%')", strCLIENTNAME)
                Else
                    If strCLIENTNAME <> "" Then Con3 = String.Format(" AND (A.JOBNAME like '%{0}%')", strCLIENTNAME)
                End If

                If strENDFLAG <> "" Then Con4 = String.Format(" AND (CASE ISNULL(B.ENDFLAG,'') WHEN '' THEN A.ENDFLAG ELSE B.ENDFLAG END = '{0}')", strENDFLAG)
                If strJOBTYPE <> "" Then Con5 = String.Format(" AND (A.JOBGUBN = '{0}')", strJOBTYPE)

                If strEMPNO <> "" Then Con6 = String.Format(" AND (A.EMPNO = '{0}')", strEMPNO)
                If strEMPNAME <> "" Then Con7 = String.Format(" AND (DBO.SC_EMPNAME_FUN(A.EMPNO) LIKE '%{0}%')", strEMPNAME)

                strWhere = BuildFields(" ", Con1, Con2, Con3, Con4, Con5, Con6, Con7)

                strFormat = " SELECT "
                strFormat = strFormat & " CASE ISNULL(CASE ISNULL(B.JOBNO,'') WHEN '' THEN A.CHECK_POINT ELSE B.CHECK_POINT END,'') WHEN '' THEN 0 ELSE 1 END AS CHK ,"
                strFormat = strFormat & " A.REQDAY,"
                strFormat = strFormat & " CASE ISNULL(B.ENDFLAG,'') WHEN '' THEN A.ENDFLAG ELSE B.ENDFLAG END AS ENDFLAG,"
                strFormat = strFormat & " DBO.MD_GETPUBNAME_FUN(CASE ISNULL(B.ENDFLAG,'') WHEN '' THEN A.ENDFLAG ELSE B.ENDFLAG END ) ENDFLAGNAME,"
                strFormat = strFormat & " REPLACE(C.PROJECTNM, CHAR(9), '  ') PROJECTNM, "
                strFormat = strFormat & " REPLACE(A.JOBNAME, CHAR(9), '  ') JOBNAME, A.JOBNO, "
                strFormat = strFormat & " CASE WHEN ISNULL(B.PREESTNO,'') = '' THEN"
                strFormat = strFormat & " (SELECT TOP 1 PREHDR.PREESTNO FROM PD_PREEST_HDR PREHDR WHERE A.JOBNO = PREHDR.JOBNO ORDER BY PREESTNO ASC)"
                strFormat = strFormat & " ELSE B.PREESTNO END AS PREESTNO,"
                strFormat = strFormat & " CASE ISNULL(B.SEQ, 0) WHEN 0 THEN 1"
                strFormat = strFormat & " ELSE B.SEQ END SEQ,"
                strFormat = strFormat & " DBO.SC_GET_HIGHCUSTNAME_FUN(CASE ISNULL(B.CLIENTCODE,'') WHEN '' THEN C.CLIENTCODE ELSE B.CLIENTCODE END) CLIENTNAME,"
                strFormat = strFormat & " DBO.SC_GET_CUSTNAME_FUN(CASE ISNULL(B.TIMCODE,'') WHEN '' THEN C.TIMCODE ELSE B.TIMCODE END) TIMNAME,"
                strFormat = strFormat & " DBO.MD_GETPUBNAME_FUN(A.JOBGUBN) JOBGUBNNAME,"
                strFormat = strFormat & " DBO.MD_GETPUBNAME_FUN(A.CREPART) JOBPARTNAME,"
                strFormat = strFormat & " ISNULL(B.DIVAMT,0) DIVAMT,"
                strFormat = strFormat & " CASE B.CONFIRMFLAG WHEN '4' THEN B.ADJAMT ELSE 0 END AS ADJAMT,"
                strFormat = strFormat & " DBO.PD_JOBNODEPT_DEPTNM_FUN(A.JOBNO) DEPTNAME,"
                strFormat = strFormat & " DBO.PD_JOBNODEPT_EMPNM_FUN(A.JOBNO) EMPNAME,"
                strFormat = strFormat & " DBO.PD_JOBNODEPT_EMPCNT_FUN(A.JOBNO) EMPCNT,"
                strFormat = strFormat & " DBO.SC_EMPNAME_FUN(A.EMPNO) CPEMPNAME,"
                strFormat = strFormat & " DBO.PD_TAXNO_DEMANDDAY_FUN(B.TAXYEARMON,B.TAXNO) DEMANDYEARMON,"
                strFormat = strFormat & " (SELECT top 1 EXEDTL.ADJDAY FROM PD_EXE_DTL EXEDTL WHERE A.JOBNO = EXEDTL.JOBNO and isnull(adjday,'') <> '' order by seq) AS ADJDAY,"
                strFormat = strFormat & " CASE DBO.PD_GET_JOBNO_CONTRACTCNT_FUN(A.JOBNO) "
                strFormat = strFormat & " WHEN 0 THEN '' "
                strFormat = strFormat & " ELSE CAST(DBO.PD_GET_JOBNO_CONTRACTCNT_FUN(A.JOBNO) AS VARCHAR(15))"
                strFormat = strFormat & " END AS CONTRACTNO,"
                strFormat = strFormat & " A.SETYEARMON,"
                strFormat = strFormat & " CASE ISNULL(B.JOBNO,'') WHEN '' THEN replace(A.CHECK_POINT,char(13)+char(10),'★')"
                strFormat = strFormat & " ELSE replace(B.CHECK_POINT,char(13)+char(10),'★') END AS CHECK_POINT,"
                strFormat = strFormat & " CASE ISNULL(B.JOBNO,'') WHEN '' THEN 0"
                strFormat = strFormat & " ELSE 1 END AS JOBNO_DIVAMTFLAG,"
                strFormat = strFormat & " DENSE_RANK() OVER (ORDER BY A.REQDAY DESC,A.JOBNO DESC,A.PROJECTNO) AS RANKJOB,"
                strFormat = strFormat & " CASE ISNULL(B.JOBNAME,'') WHEN '' THEN REPLACE(A.JOBNAME, CHAR(9), '  ') ELSE REPLACE(B.JOBNAME, CHAR(9), '  ') END AS PRIJOBNAME,"
                strFormat = strFormat & " A.JOBGUBN,"
                strFormat = strFormat & " CASE ISNULL(B.SUBSEQ,'') WHEN '' THEN C.SUBSEQ"
                strFormat = strFormat & " ELSE B.SUBSEQ END AS SUBSEQ,"
                strFormat = strFormat & " DBO.SC_GET_SUBSEQNAME_FUN(CASE ISNULL(B.SUBSEQ,'') WHEN '' THEN C.SUBSEQ ELSE B.SUBSEQ END) AS SUBSEQNAME,"
                strFormat = strFormat & " CASE ISNULL(B.CLIENTCODE,'') WHEN '' THEN C.CLIENTCODE"
                strFormat = strFormat & " ELSE B.CLIENTCODE END AS CLIENTCODE,"
                strFormat = strFormat & " CASE ISNULL(B.TIMCODE,'') WHEN '' THEN C.TIMCODE"
                strFormat = strFormat & " ELSE B.TIMCODE END AS TIMCODE,"
                strFormat = strFormat & " DBO.PD_COMMITION_FUN(CASE ISNULL(B.CLIENTCODE,'') WHEN '' THEN C.CLIENTCODE ELSE B.CLIENTCODE END) COMMITIONVALUE,"
                strFormat = strFormat & " case isnull(d.amt,0) when 0 then 0 else (isnull(d.amt,0) - isnull(e.adjamt,0)) /isnull(d.amt,0) *100 end as RATE,"
                strFormat = strFormat & " (isnull(d.amt,0) - isnull(e.adjamt,0)) INCOM"
                strFormat = strFormat & " FROM PD_JOBNO A "
                strFormat = strFormat & " INNER JOIN PD_PONO C ON A.PROJECTNO = C.PROJECTNO"
                strFormat = strFormat & " LEFT JOIN PD_DIVAMT B ON A.JOBNO = B.JOBNO"
                strFormat = strFormat & " LEFT JOIN ("
                strFormat = strFormat & " 	select jobno, isnull(sum(amt),0) amt "
                strFormat = strFormat & " 	from pd_tax_dtl "
                strFormat = strFormat & " 	where isnull(attr10,0) <> 999999	"
                strFormat = strFormat & " 	group by jobno "
                strFormat = strFormat & " ) d on a.jobno = d.jobno"
                strFormat = strFormat & " LEFT JOIN ( "
                strFormat = strFormat & " 	select jobno,  isnull(sum(adjamt),0) adjamt "
                strFormat = strFormat & " 	from pd_exe_dtl "
                strFormat = strFormat & " 	where 1=1 "
                strFormat = strFormat & " 	group by jobno "
                strFormat = strFormat & " ) e on a.jobno = e.jobno"
                strFormat = strFormat & " WHERE 1=1 {0}"
                strFormat = strFormat & " ORDER BY A.REQDAY DESC, A.JOBNO DESC, SEQ ASC"


                strSQL = String.Format(strFormat, strWhere)

                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)

                vntData = .mobjSCGLSql.SQLSelectStr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

    ' =============== ProcessRtn  
    Public Function ProcessRtn(ByVal strInfoXML As String, _
                               ByVal vntData As Object, _
                               ByVal strCHKPOINT As String) As Object

        Dim intRtn As Integer
        Dim i, intColCnt, intRows As Integer
        Dim strFLAG
        Dim strCHECK_POINT
        Dim strJOBNO
        Dim strPREESTNO, dblSEQ

        SetConfig(strInfoXML)
        With mobjSCGLConfig
            Try
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                .mobjSCGLSql.SQLBeginTrans()
                If IsArray(vntData) Then
                    '''사용할 Entity 개체생성(Config 정보를 넘겨생성)
                    mobjcePD_JOBNO = New cePD_JOBNO(mobjSCGLConfig)
                    mobjcePD_DIVAMT = New cePD_DIVAMT(mobjSCGLConfig)

                    '''vntData의 컬럼수, 로우수를 변수입력
                    intColCnt = UBound(vntData, 1) : intRows = UBound(vntData, 2)
                    For i = 1 To intRows
                        strFLAG = GetElement(vntData, "JOBNO_DIVAMTFLAG", intColCnt, i, OPTIONAL_STR)
                        strCHECK_POINT = GetElement(vntData, "CHECK_POINT", intColCnt, i, OPTIONAL_STR)
                        'CHK 가 된경우라면 마지막에 입력한 값을 전체적으로 업뎃 아니라면 SettextBinding 된 값을 저장
                        '1일때는 pd_divamt ,,  0일때는 pd_jobno에 업데이트
                        If GetElement(vntData, "CHK", intColCnt, i, OPTIONAL_STR) = 1 Then
                            If strFLAG = 0 Then
                                strJOBNO = GetElement(vntData, "JOBNO", intColCnt, i, OPTIONAL_STR)
                                intRtn = mobjcePD_JOBNO.Update_CHECK_POINT(strJOBNO, strCHKPOINT)
                            Else
                                strPREESTNO = GetElement(vntData, "PREESTNO", intColCnt, i, OPTIONAL_STR)
                                dblSEQ = GetElement(vntData, "SEQ", intColCnt, i, OPTIONAL_STR)
                                intRtn = mobjcePD_DIVAMT.Update_CHECK_POINT(strPREESTNO, dblSEQ, strCHKPOINT)
                            End If
                        Else
                            If strFLAG = 0 Then
                                strJOBNO = GetElement(vntData, "JOBNO", intColCnt, i, OPTIONAL_STR)
                                intRtn = mobjcePD_JOBNO.Update_CHECK_POINT(strJOBNO, strCHECK_POINT)
                            Else
                                strPREESTNO = GetElement(vntData, "PREESTNO", intColCnt, i, OPTIONAL_STR)
                                dblSEQ = GetElement(vntData, "SEQ", intColCnt, i, OPTIONAL_STR)
                                intRtn = mobjcePD_DIVAMT.Update_CHECK_POINT(strPREESTNO, dblSEQ, strCHECK_POINT)
                            End If
                        End If
                    Next
                End If
                .mobjSCGLSql.SQLCommitTrans()
                Return intRows
            Catch err As Exception
                .mobjSCGLSql.SQLRollbackTrans()
                Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn")
            Finally
                .mobjSCGLSql.SQLDisconnect()
                mobjcePD_JOBNO.Dispose()
                mobjcePD_DIVAMT.Dispose()
            End Try
        End With
    End Function

    ' =============== JOBNO 조회
    Public Function SelectRtn_Status(ByVal strInfoXML As String, _
                                     ByRef intRowCnt As Integer, _
                                     ByRef intColCnt As Integer, _
                                     ByVal strFROM As String, _
                                     ByVal strTO As String, _
                                     ByVal strCLIENTCODE As String, _
                                     ByVal strCLIENTNAME As String, _
                                     ByVal strFLAG As String, _
                                     ByVal strSEARCH As String) As Object

        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2, Con3, Con4

        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            Try
                If strFROM <> "" And strTO <> "" Then
                    Con1 = String.Format(" AND (Substring(REQDAY,1,6) BETWEEN '{0}' AND  '{1}')", strFROM, strTO)
                End If
                If strFROM <> "" And strTO = "" Then
                    Con1 = String.Format(" AND (Substring(REQDAY,1,6) >= '{0}')", strFROM)
                End If
                If strFROM = "" And strTO <> "" Then
                    Con1 = String.Format(" AND (Substring(REQDAY,1,6) <= '{0}')", strTO)
                End If

                If strSEARCH = "1" Then
                    If strCLIENTCODE <> "" Then Con2 = String.Format(" AND (CLIENTCODE = '{0}')", strCLIENTCODE)
                Else
                    If strCLIENTCODE <> "" Then Con2 = String.Format(" AND (JOBNO = '{0}')", strCLIENTCODE)
                End If

                If strSEARCH = "1" Then
                    If strCLIENTNAME <> "" Then Con3 = String.Format(" AND (CLIENTNAME like '%{0}%')", strCLIENTNAME)
                Else
                    If strCLIENTNAME <> "" Then Con3 = String.Format(" AND (JOBNAME like '%{0}%')", strCLIENTNAME)
                End If

                If strFLAG <> "" Then Con4 = String.Format(" AND (CONFIRM = '{0}')", strFLAG)

                strWhere = BuildFields(" ", Con1, Con2, Con3, Con4)

                strFormat = "SELECT "
                strFormat = strFormat & " REQDAY, JOBNO, "
                strFormat = strFormat & " SEQ, JOBNAME, "
                strFormat = strFormat & " CLIENTCODE,CLIENTNAME, "
                strFormat = strFormat & " JOBGUBN,CONFIRM,MEMO, "
                strFormat = strFormat & " TRANS,TAX,VOCH, "
                strFormat = strFormat & " EMPNAME,DEPTNAME, "
                strFormat = strFormat & " MANAGER,EMPNO,DEPTCD, "
                strFormat = strFormat & " DENSE_RANK() OVER (ORDER BY REQDAY DESC,JOBNO DESC) AS RANKJOB, "
                strFormat = strFormat & " PREESTNO, "
                strFormat = strFormat & " PRIJOBNAME, "
                strFormat = strFormat & " PROJECTNM, "
                strFormat = strFormat & " JOBGUBNCODE, "
                strFormat = strFormat & " TIMCODE, "
                strFormat = strFormat & " SUBSEQ "
                strFormat = strFormat & " FROM V_PDSTATUS  "
                strFormat = strFormat & " WHERE 1=1 {0} "
                strFormat = strFormat & " ORDER BY RANKJOB "

                strSQL = String.Format(strFormat, strWhere)

                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_Status")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

    ' =============== JOBNO 조회
    Public Function SelectRtn_Mine(ByVal strInfoXML As String, _
                                   ByRef intRowCnt As Integer, _
                                   ByRef intColCnt As Integer, _
                                   ByVal strUSERDEPT As String, _
                                   ByVal strMANAGER As String) As Object

        Dim strCols As String         '컬럼변수
        Dim strWhere As String       'Where조건 변수
        Dim strFormat As String      'SQL Format 변수
        Dim strSQL As String          'SQL 변수
        Dim vntData As Object        'Array Return 변수(Array 를사용할 때 선언)
        Dim strXMLData As String    'XML  Return 변수(XML  을 사용할 때 선언)
        Dim Con1, Con2, Con3, Con4


        SetConfig(strInfoXML) '기본정보 Setting
        With mobjSCGLConfig '기본정보 Config 개체
            Try

                strCols = "REQDAY,"
                strCols = strCols & " JOBNO, SEQ, JOBNAME, "
                strCols = strCols & " CLIENTCODE, CLIENTNAME, "
                strCols = strCols & " JOBGUBN, CONFIRM,MEMO, "
                strCols = strCols & " TRANS, TAX, VOCH,EMPNAME, DEPTNAME, "
                strCols = strCols & " MANAGER, EMPNO, DEPTCD, "
                strCols = strCols & " DENSE_RANK() OVER (ORDER BY REQDAY DESC,JOBNO DESC) AS RANKJOB, "
                strCols = strCols & " PREESTNO, PRIJOBNAME, "
                strCols = strCols & " PROJECTNM, JOBGUBNCODE, "
                strCols = strCols & " TIMCODE, SUBSEQ "

                Con1 = String.Format(" AND (DEPTCD = '{0}')", strUSERDEPT)

                strWhere = BuildFields(" ", Con1, Con2, Con3, Con4)

                If strMANAGER = "Y" Then
                    strFormat = "SELECT {0} FROM V_PDSTATUS WHERE 1=1 ORDER BY RANKJOB"
                Else
                    strFormat = "SELECT {0} FROM V_PDSTATUS WHERE 1=1 {1} ORDER BY RANKJOB"
                End If

                strSQL = String.Format(strFormat, strCols, strWhere)
                ' DB 접속
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)
                Return vntData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_Status")
            Finally
                ' DB 접속 종료
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

#End Region

#Region "GROUP BLOCK : Entity Function Section"

#End Region
End Class
