'****************************************************************************************
'Generated By: MakeSFAR V.2.0.0 - 컨트롤 클래스 메이커
'시스템구분    : 솔루션명 /시스템명/Server Control Class
'실행   환경    : COM+ Service Server Package
'프로그램명    : ccMDCMDEPTMST.vb
'기         능    : - 기능을 명시 합니다.
'특이  사항     : - 특이사항에 대해 표현
'                     -
'----------------------------------------------------------------------------------------
'HISTORY    :1) 
'            2) 
'****************************************************************************************

Imports System.Xml                  ' XML처리
Imports SCGLControl                 ' ControlClass의 Base Class
Imports SCGLUtil.cbSCGLConfig       ' ConfigurationClass
Imports SCGLUtil.cbSCGLErr          '오류처리 클래스
Imports SCGLUtil.cbSCGLXml          'XML처리 클래스
Imports SCGLUtil.cbSCGLUtil         '기타유틸리티 클래스
Imports eMDCO                       '엔터티 추가

' 엔티티 클래스 사용시 해당 엔티티 클래스의 프로젝트를 참조한 후 Imports 하십시요. 
' Imports 엔티티프로젝트

Public Class ccMDCOVOCH
    Inherits ccControl
#Region "GROUP BLOCK : 전역 또는 모듈레벨의 변수/상수 선언"
    Private CLASS_NAME = "ccMDCOVOCH"                  '자신의 클래스명
    Private mobjSC_VOCHNO As eMDCO.ceSC_VOCHNO
#End Region

#Region "GROUP BLOCK : 외부에비공개(채번 생성과 설정 로직)"

    '=================== (채번)전표 조회 로직
    Public Function SelectRtnVOCHNORMS(ByVal strInfoXML As String, _
                                       ByRef intRowCnt As Integer, _
                                       ByRef intColCnt As Integer, _
                                       ByVal strPOSTINGDATE As String, _
                                       ByVal strMEDFLAG As String, _
                                       ByVal strTAXYEARMON As String, _
                                       ByVal strTAXNO As String) As Object
        '여기부터 단순조회
        Dim strSQL, strRtn As String
        Dim strYEAR, strMON As String
        Dim vntData

        With mobjSCGLConfig '기본정보 Config 개체
            Try
                SetConfig(strInfoXML)   '기본정보 설정

                strYEAR = Mid(strPOSTINGDATE, 1, 4)
                strMON = Mid(strPOSTINGDATE, 5, 2)

                strSQL = strSQL & " SELECT "
                strSQL = strSQL & " VOCHNO "
                strSQL = strSQL & " FROM SC_VOCHNO"
                strSQL = strSQL & " WHERE YEAR = '" & strYEAR & "'"
                strSQL = strSQL & " AND MON = '" & strMON & "'"
                strSQL = strSQL & " AND TAXYEARMON = '" & strTAXYEARMON & "'"
                strSQL = strSQL & " AND TAXNO = '" & strTAXNO & "'"
                strSQL = strSQL & " AND MEDFLAG = '" & strMEDFLAG & "'"
                strSQL = strSQL & " AND ERR_YN = 'N'"
                strSQL = strSQL & " ORDER BY SEQ DESC "

                strSQL = String.Format(strSQL)

                .mobjSCGLSql.SQLConnect(.DBConnStr)

                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , True)

                Return vntData
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtnVOCHNORMS")
            Finally
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
        '여기까지 단순조회
    End Function

    Public Function InsertRtn_VOCHNO(ByVal strInfoXML As String, _
                                     ByVal strPOSTINGDATE As String, _
                                     ByVal strMEDFLAG As String, _
                                     ByVal strTAXYEARMON As String, _
                                     ByVal strTAXNO As String, _
                                     ByVal strGROUP As String, _
                                     ByVal strTYPE As String) As Integer

        Dim intRtn As Integer
        Dim i, intColCnt, intRows As Integer
        Dim strYEAR, strMON, strVOCHNOSEQ, strVOCHNO, strGROUPSEQ

        SetConfig(strInfoXML)
        With mobjSCGLConfig
            Try
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                .mobjSCGLSql.SQLBeginTrans()

                '''사용할 Entity 개체생성(Config 정보를 넘겨생성)
                mobjSC_VOCHNO = New ceSC_VOCHNO(mobjSCGLConfig)

                '전표 전기일을 년/ 월로 나눠 전표 번호를 생성 (key 가 된다.)
                If strPOSTINGDATE <> "" Then
                    strYEAR = Mid(strPOSTINGDATE, 1, 4)
                    strMON = Mid(strPOSTINGDATE, 5, 2)
                End If

                '전표번호 순번을 생성
                strVOCHNOSEQ = SelectRtn_VOCHNOSEQ(strYEAR, strMON)

                '채번을 설정(전표번호 생성 R(1) + 전기월(2) + 전표유형(1) + 전표번호 순번 6자리)
                strVOCHNO = SelectRtn_VOCHNO(strYEAR, strMON, strTYPE)

                'GROUP 시퀸스 생성(한꺼번에 전표를 넘길경우 하나가 에러가 발생하면 모두 에러 처리 위한 KEY)
                '한번에 넘긴 전표번호는 일련의 정렬된 전표 채번을 가져야 한다.
                strGROUPSEQ = SelectRtn_GROUPSEQ(strYEAR, strMON, strGROUP)

                intRtn = InsertRtn(strYEAR, strMON, strVOCHNOSEQ, strGROUPSEQ, strVOCHNO, strMEDFLAG, strTAXYEARMON, strTAXNO)

                .mobjSCGLSql.SQLCommitTrans()

                Return intRtn

            Catch err As Exception
                .mobjSCGLSql.SQLRollbackTrans()
                Throw RaiseSysErr(err, CLASS_NAME & ".InsertRtn_VOCHNO")
            Finally
                .mobjSCGLSql.SQLDisconnect()
                mobjSC_VOCHNO.Dispose()
            End Try
        End With
    End Function
    '=================== (채번)전표 번호순번
    Public Function SelectRtn_VOCHNOSEQ(ByVal strYEAR As String, _
                                        ByVal strMON As String) As String
        '여기부터 단순조회
        Dim strSQL, strFormat, strRtn As String

        With mobjSCGLConfig '기본정보 Config 개체
            Try
                strSQL = "  SELECT "
                strSQL = strSQL & " ISNULL(MAX(VOCHSEQ),0)+1 VOCHNOSEQ "
                strSQL = strSQL & " FROM SC_VOCHNO "
                strSQL = strSQL & " WHERE YEAR = '" & strYEAR & "'"
                strSQL = strSQL & " AND MON = '" & strMON & "' "

                strRtn = .mobjSCGLSql.SQLSelectOneScalar(strSQL)

                Return strRtn
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_VOCHNOSEQ")
            Finally
            End Try
        End With
        '여기까지 단순조회
    End Function
    '=================== (채번)전표 번호 생성 로직(10)
    Public Function SelectRtn_VOCHNO(ByVal strYEAR As String, _
                                     ByVal strMON As String, _
                                     ByVal strTYPE As String) As String
        '여기부터 단순조회
        Dim strSQL, strFormat, strRtn As String

        With mobjSCGLConfig '기본정보 Config 개체
            Try

                '위수탁 전표 번호 채번
                If strTYPE = "7" Then

                    strSQL = "  SELECT "
                    strSQL = strSQL & " 'F' + '" & strMON & "' + '7' + DBO.LPAD(ISNULL(MAX(VOCHSEQ),0)+1,6,'0') VOCHNO "
                    strSQL = strSQL & " FROM SC_VOCHNO "
                    strSQL = strSQL & " WHERE YEAR = '" & strYEAR & "'"
                    strSQL = strSQL & " AND MON = '" & strMON & "' "

                    '매출 전표 번호 채번
                ElseIf strTYPE = "1" Then

                    strSQL = "  SELECT "
                    strSQL = strSQL & " 'F' + '" & strMON & "' + '1' + DBO.LPAD(ISNULL(MAX(VOCHSEQ),0)+1,6,'0') VOCHNO "
                    strSQL = strSQL & " FROM SC_VOCHNO "
                    strSQL = strSQL & " WHERE YEAR = '" & strYEAR & "'"
                    strSQL = strSQL & " AND MON = '" & strMON & "' "

                    '매입 전표 번호 채번
                ElseIf strTYPE = "4" Then

                    strSQL = "  SELECT "
                    strSQL = strSQL & " 'F' + '" & strMON & "' + '4' + DBO.LPAD(ISNULL(MAX(VOCHSEQ),0)+1,6,'0') VOCHNO "
                    strSQL = strSQL & " FROM SC_VOCHNO "
                    strSQL = strSQL & " WHERE YEAR = '" & strYEAR & "'"
                    strSQL = strSQL & " AND MON = '" & strMON & "' "

                End If

                strRtn = .mobjSCGLSql.SQLSelectOneScalar(strSQL)

                Return strRtn
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_VOCHNO")
            Finally
            End Try
        End With
        '여기까지 단순조회
    End Function
    '===================그룹 시퀸스 생성
    Public Function SelectRtn_GROUPSEQ(ByVal strYEAR As String, _
                                       ByVal strMON As String, _
                                       ByVal strGROUP As String) As String
        '여기부터 단순조회
        Dim strSQL, strFormat, strRtn As String

        With mobjSCGLConfig '기본정보 Config 개체
            Try
                If strGROUP = True Then
                    strSQL = strSQL & " SELECT "
                    strSQL = strSQL & " ISNULL(MAX(GROUPSEQ),1) + 1 "
                    strSQL = strSQL & " FROM SC_VOCHNO"
                    'strSQL = strSQL & " WHERE YEAR = '" & strYEAR & "'"
                    'strSQL = strSQL & " AND MON = '" & strMON & "'"

                Else
                    strSQL = strSQL & " SELECT "
                    strSQL = strSQL & " ISNULL(MAX(GROUPSEQ),1)"
                    strSQL = strSQL & " FROM SC_VOCHNO"
                    'strSQL = strSQL & " WHERE YEAR = '" & strYEAR & "'"
                    'strSQL = strSQL & " AND MON = '" & strMON & "'"
                End If

                strRtn = .mobjSCGLSql.SQLSelectOneScalar(strSQL)

                Return strRtn
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_GROUPSEQ")
            Finally
            End Try
        End With
        '여기까지 단순조회
    End Function

#End Region

    'strYEAR, strMON, strGROUPSEQ, strVOCHNO, strMEDFLAG, strTAXYEARMON,strTAXNO
#Region "GROUP BLOCK : 외부에 비공개 Method"
    Private Function InsertRtn(ByVal strYEAR As String, _
                               ByVal strMON As String, _
                               ByVal strVOCHNOSEQ As String, _
                               ByVal strGROUPSEQ As String, _
                               ByVal strVOCHNO As String, _
                               ByVal strMEDFLAG As String, _
                               ByVal strTAXYEARMON As String, _
                               ByVal strTAXNO As String) As Integer

        Dim intRtn As Integer
        intRtn = mobjSC_VOCHNO.InsertDo( _
                                       "F", _
                                       strYEAR, _
                                       strMON, _
                                       strVOCHNOSEQ, _
                                       strGROUPSEQ, _
                                       strVOCHNO, _
                                       strMEDFLAG, _
                                       strTAXYEARMON, _
                                       strTAXNO, _
                                       "N")

        Return intRtn
    End Function

    Private Function DeleteRtn(ByVal vntData As Object, _
                               ByVal intColCnt As Integer, _
                               ByVal intRow As Integer) As Integer

        Dim intRtn As Integer

        intRtn = mobjSC_VOCHNO.DeleteDo(GetElement(vntData, "SEQ", intColCnt, intRow))

        Return intRtn
    End Function

#End Region
End Class