'****************************************************************************************
'Generated By: JNF
'시스템구분 : RMS/SC/Server Entity Class
'실행  환경 : GAC(Global Assembly Cache)
'프로그램명 : ceSC_FEE_MST.vb ( SC_FEE_MST Entity 처리 Class)
'기      능 : SC_FEE_MST Entity에 대해Insert/Update/Delete/Select를 처리
'             - 부모엔티티 객체인 SCGLUtil.ceEntity를 상속
'----------------------------------------------------------------------------------------
'HISTORY    :1) 2009-08-20 오후 06:18 By Making Entity Bean
'****************************************************************************************
Imports SCGLUtil.cbSCGLUtil     '공통 유틸리티 객체
Imports SCGLUtil.cbSCGLErr      '공통 오류처리 객체
Imports SCGLEntity              '엔티티 객체의 부모 객체

Public Class ceSC_CUST_SAP
    Inherits ceEntity

#Region "GROUP BLOCk : 전역 또는 모듈레벨의 변수/상수 선언"
    Private Const CLASS_NAME = "ceSC_CUST_SAP"    '자신의 클래스명
#End Region

#Region "GROUP BLOCk : 외부에 공개 Method"
#Region "SQL Insert/Update/Delete/Select"

    '*****************************************************************
    '입력 : strSQL = SQL 문
    '반환 : 처리건수
    '기능 : 해당 Entity에 Insert 처리
    '*****************************************************************
    Public Function InsertDo(ByVal strSAUPNO As String, _
            Optional ByVal strNAME1 As String = OPTIONAL_STR, _
            Optional ByVal strCNAME As String = OPTIONAL_STR, _
            Optional ByVal strORT01 As String = OPTIONAL_STR, _
            Optional ByVal strSTRAS As String = OPTIONAL_STR, _
            Optional ByVal strPSTLZ As String = OPTIONAL_STR, _
            Optional ByVal strTELF1 As String = OPTIONAL_STR, _
            Optional ByVal strCEO As String = OPTIONAL_STR, _
            Optional ByVal strJ_1KFTBUS As String = OPTIONAL_STR, _
            Optional ByVal strJ_1KFTIND As String = OPTIONAL_STR, _
            Optional ByVal strREGIO As String = OPTIONAL_STR, _
            Optional ByVal strMCOD1 As String = OPTIONAL_STR, _
            Optional ByVal strCRTDAY As String = OPTIONAL_STR, _
            Optional ByVal strCRTWHO As String = OPTIONAL_STR, _
            Optional ByVal strNAME2 As String = OPTIONAL_STR)

        Dim strSQL As String
        Dim strFields As New System.Text.StringBuilder
        Dim strValues As New System.Text.StringBuilder
        Dim strNOW As String '데이트형의 처리는 변수를 받아 텍스트로 처리 한다.. 
        strNOW = Now
        Try
            BuildNameValues(",", "SAUPNO", strSAUPNO, strFields, strValues)
            BuildNameValues(",", "NAME1", strNAME1, strFields, strValues)
            BuildNameValues(",", "CNAME", strCNAME, strFields, strValues)
            BuildNameValues(",", "ORT01", strORT01, strFields, strValues)
            BuildNameValues(",", "STRAS", strSTRAS, strFields, strValues)
            BuildNameValues(",", "PSTLZ", strPSTLZ, strFields, strValues)
            BuildNameValues(",", "TELF1", strTELF1, strFields, strValues)
            BuildNameValues(",", "CEO", strCEO, strFields, strValues)
            BuildNameValues(",", "J_1KFTBUS", strJ_1KFTBUS, strFields, strValues)
            BuildNameValues(",", "J_1KFTIND", strJ_1KFTIND, strFields, strValues)
            BuildNameValues(",", "REGIO", strREGIO, strFields, strValues)
            BuildNameValues(",", "MCOD1", strMCOD1, strFields, strValues)
            BuildNameValues(",", "CRTDAY", strCRTDAY, strFields, strValues)
            BuildNameValues(",", "CRTWHO", strCRTWHO, strFields, strValues)
            BuildNameValues(",", "NAME2", strNAME2, strFields, strValues)


            strSQL = String.Format("INSERT INTO {0} ({1}) VALUES({2})", EntityName, strFields, strValues)

            Return ProcEntity(strSQL)
        Catch err As Exception
            Throw RaiseSysErr(err, CLASS_NAME & ".InsertDo")
        End Try
    End Function
#End Region

#Region "객체 생성/해제"
    '*****************************************************************
    '입력 : strInfoXML = 공통기본정보에 대한 XML
    'objSCGLSql = DB 처리 객체 인스턴싱 변수    '반환 : 없음
    '기능 : DB 처리를 위한 공통기본정보 설정
    '*****************************************************************
    Public Sub New(Optional ByVal objSCGLConfig As SCGLUtil.cbSCGLConfig = Nothing, Optional ByVal strInfoXML As String = "")
        MyBase.SetConfig(objSCGLConfig, strInfoXML)
        MyBase.EntityName = "SC_CUST_SAP"     'Entity Name 설정
    End Sub

    '해제 기능은 Base Class에서 구현되어 있음
#End Region
#End Region

End Class







