'****************************************************************************************
'Generated By :::BELLWORLD Making Entity Bean Ver1.0:::
'시스템구분 : SFAR/시스템명/Server단 Entity Base Component
'실행  환경 : COM+ Service Server Package
'프로그램명 : ccSCEXCOM.vb (Table한글명 Entity 처리 Class)
'기      능 : Table한글명(영문명) Entity에 대해Insert/Update/Delete/Select를 처리
'특이  사항 : -특이사항에 대해 표현
'             -
'----------------------------------------------------------------------------------------
'HISTORY    :1) 2003-06-19 오후 2:35:59 By 작성자
'            2) 2003-06-19 오후 2:35:59 By 작성자 : 변경 내용 설명
'****************************************************************************************

Imports System.Xml                  'XML처리
Imports SCGLControl                 'ControlClass의 Base Class
Imports SCGLUtil.cbSCGLConfig       'ConfigurationClass
Imports SCGLUtil.cbSCGLErr          '오류처리클래스
Imports SCGLUtil.cbSCGLXml          'XML처리클래스
Imports SCGLUtil.cbSCGLUtil         '기타유틸리티 클래스
Imports eMDCO

Public Class ccMDETELECEXCOM
    Inherits ccControl

#Region "GROUP BLOCk : 전역 또는 모듈레벨의 변수/상수 선언"
    Private CLASS_NAME = "ccMDETELECEXCOM"         '자신의클래스명
    Dim mobjceSC_USER_COL As eMDCO.ceSC_USER_COL
    Dim mobjceSC_USER_TAB As eMDCO.ceSC_USER_TAB
    Private mobjceMD_ELECTRIC_PREMATTER As eMDCO.ceMD_ELECTRIC_PREMATTER
    'Private Const .DBConnStr = "Provider=SQLOLEDB;Data Source=10.110.10.86;Initial Catalog=MCDEV;DSN=MCDEV;UID=devadmin;Pwd=password" '커넥션Setting
#End Region

#Region "GROUP BLOCk : Property 선언"
#End Region

#Region "GROUP BLOCk : Event 선언"

#End Region

#Region "GROUP BLOCk : 외부에 공개 Method"
    ' =============== SelectRtnSample Code
    Public Function SelectRtn(ByVal strInfoXML As String, _
                              ByRef intRowCnt As Integer, _
                              ByRef intColCnt As Integer, _
                              ByVal strCOL_NAME As String, _
                              ByVal strYEARMON As String) As Object     'XML  데이터 조회시

        Dim strSQL As String
        Dim strFormet, strSelFields, strWhere As String
        Dim strChkDate As String = ""
        Dim vntData As Object
        Dim intRtn

        With mobjSCGLConfig
            Try
                SetConfig(strInfoXML)   '기본정보 설정

                strSelFields = strCOL_NAME.Replace("|", ",")

                strFormet = "select {0} from MD_ELECTRIC_MEDIUM_TEMP WHERE YEARMON = '" & strYEARMON & "'"

                strSQL = String.Format(strFormet, strSelFields)

                .mobjSCGLSql.SQLConnect(.DBConnStr)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt)

                'MD_BOOKING_MEDIUM_TEMP 의 내용을 조회해온후 TEMP테이블의 내용을 삭제한다.
                .mobjSCGLSql.SQLBeginTrans()
                mobjceSC_USER_COL = New ceSC_USER_COL(mobjSCGLConfig)
                .mobjSCGLSql.SQLCommitTrans()

                Return vntData

            Catch err As Exception
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn")
            Finally
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function


    Public Function getTABCOLINFO(ByVal strInfoXml As String, _
                                  ByRef intRowCnt As Integer, _
                                  ByRef intColCnt As Integer, _
                                  ByVal dblTAB_ID As Double) As Object

        SetConfig(strInfoXml)   '모든Public 함수의 처음오는 기본정보 설정

        Dim vntData As Object     '''xmlData String
        Dim strFields As String   '''{0}번째 필드명
        Dim strKeys As String     '''{1}번째조건절
        Dim strFormat As String   '''Format을 맞추어 주는 String
        Dim strSQL As String      '''SQL 문을 만들어 주는 String

        ''''{0} 번째는 필드명으로한다.
        strFields = " A.TAB_ID, A.COL_NAME, A.COL_USER_NAME, A.COL_USE_YN, A.COL_DEFAULT_VALUE, A.COL_DATA_TYPE, A.COL_DATA_LENGTH, A.COL_COLUMN_ID, A.COL_NULLABLE "
        ''''{1} 번째는 WHERE 조건으로 한다.
        strKeys = BuildFields("AND", _
          GetFieldNameValue("A.TAB_ID", dblTAB_ID))
        ''''{1} 이후 또는 전에 필수적으로 들어가야할 SQL문장을 추가주거나 ORDER BY 절을 넣어준다.
        strFormat = "SELECT {0} FROM SC_USER_COL A " & _
           "WHERE {1} AND A.COL_USE_YN=1 ORDER BY A.COL_COLUMN_ID"
        ''''strSQL 문을 만들어 준다.
        strSQL = String.Format(strFormat, strFields, strKeys)
        With mobjSCGLConfig
            Try
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt, , False)
                Return vntData
            Catch err As Exception
                Throw RaiseSysErr(err, CLASS_NAME & ".getTABCOLINFO")
            Finally
                .mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

    '코드 체크 데이터 Validation
    Public Function DataValidation(ByVal strInfoXML As String, _
                                   ByVal vntData As Object, _
                                   ByVal strCOL_NAME As String, _
                                   ByVal intColCnt As String, _
                                   ByRef intRows As Integer, _
                                   ByRef strERR As String, _
                                   ByRef strCUSTCODE As String, _
                                   ByRef strMEDCODE As String, _
                                   ByRef strREALMEDCODE As String, _
                                   ByRef strCLIENTSUBCODE As String, _
                                   ByRef strEXCLIENTCODE As String, _
                                   ByRef strYEARMON As String) As Integer

        Dim strSQL As String
        Dim strFormet, strSelFields, strWhere As String
        Dim strChkDate As String = ""
        Dim i
        Dim strArray
        Dim intNo
        Dim Rowcnt, Colcnt
        Dim codechk
        Dim strINPUT_MEDCODE
        Dim strMedAndReal
        Dim strCOL_NAME2
        Dim strSTD
        Dim strMATTERNAME
        Dim strCNT

        strCOL_NAME2 = "INPUT_CLIENTCODE | INPUT_MEDCODE | CLIENTSUBCODE | EXCLIENTCODE | STD"

        DataValidation = False
        strArray = strCOL_NAME2.Split("|")
        intNo = UBound(strArray)

        For i = 0 To intNo
            If Replace(strArray(i), " ", "") = "INPUT_CLIENTCODE" Then
                Rowcnt = 0
                Colcnt = 0
                strCUSTCODE = DataValidation_Code(Rowcnt, Colcnt, GetElement(vntData, "INPUT_CLIENTCODE", intColCnt, intRows), "CUST")

                If strCUSTCODE = "" Then
                    strERR = "광고주코드오류"
                    Exit Function
                Else
                End If
            ElseIf Replace(strArray(i), " ", "") = "INPUT_MEDCODE" Then
                Rowcnt = 0
                Colcnt = 0
                strINPUT_MEDCODE = GetElement(vntData, "INPUT_MEDCODE", intColCnt, intRows) & GetElement(vntData, "INPUT_MEDFLAG", intColCnt, intRows) & GetElement(vntData, "INPUT_AREAFLAG", intColCnt, intRows)
                strMedAndReal = DataValidation_Code(Rowcnt, Colcnt, strINPUT_MEDCODE, "MED")
                If Rowcnt = 0 Then
                    strERR = "매체사코드오류"
                    Exit Function
                Else
                    If IsArray(strMedAndReal) Then
                        strERR = ""
                        strMEDCODE = strMedAndReal(0, 0)
                        strREALMEDCODE = strMedAndReal(1, 0)
                    End If
                End If
            ElseIf Replace(strArray(i), " ", "") = "CLIENTSUBCODE" Then
                Rowcnt = 0
                Colcnt = 0
                If GetElement(vntData, "CLIENTSUBCODE", intColCnt, intRows) <> "" Then
                    strCLIENTSUBCODE = DataValidation_CLIENTSUBCode(Rowcnt, Colcnt, GetElement(vntData, "CLIENTSUBCODE", intColCnt, intRows), strCUSTCODE, "CLIENTSUB")

                    If strCLIENTSUBCODE = "" Then
                        strERR = "사업부 오류"
                        Exit Function
                    Else
                    End If
                End If
            ElseIf Replace(strArray(i), " ", "") = "EXCLIENTCODE" Then
                Rowcnt = 0
                Colcnt = 0
                If GetElement(vntData, "EXCLIENTCODE", intColCnt, intRows) <> "" Then
                    strEXCLIENTCODE = DataValidation_Code(Rowcnt, Colcnt, GetElement(vntData, "EXCLIENTCODE", intColCnt, intRows), "EXCLIENT")

                    If strEXCLIENTCODE = "" Then
                        strERR = "제작사오류"
                        Exit Function
                    Else
                    End If
                End If
            ElseIf Replace(strArray(i), " ", "") = "STD" Then
                Rowcnt = 0
                Colcnt = 0

                If GetElement(vntData, "STD", intColCnt, intRows) <> "" And GetElement(vntData, "MATTERNAME", intColCnt, intRows) <> "" Then

                    strSTD = GetElement(vntData, "STD", intColCnt, intRows)
                    strMATTERNAME = GetElement(vntData, "MATTERNAME", intColCnt, intRows)

                    strCNT = DataValidation_BrandCode(strInfoXML, Rowcnt, Colcnt, strCUSTCODE, strSTD, strMATTERNAME, strYEARMON)
                End If
            End If
        Next
        DataValidation = True
    End Function

    '광고주와 매체코드 코드 체크
    Public Function DataValidation_Code(ByRef intRowCnt As Integer, _
                                        ByRef intColCnt As Integer, _
                                        ByVal strCODE As String, _
                                        ByVal strFLAG As String) As Object   'XML  데이터 조회시

        Dim strSQL As String
        Dim strFormet, strSelFields, strWhere As String
        Dim strChkDate As String = ""
        Dim vntData As Object
        Dim strCUSTCODE

        With mobjSCGLConfig
            Try
                'SetConfig(strInfoXML)   '기본정보 설정
                If strFLAG = "CUST" Then
                    If strCODE <> "" Then strSQL = "select HIGHCUSTCODE From SC_CUST_HDR WHERE 1=1 AND MEDFLAG = 'A' AND ISNULL(USE_FLAG,0) = 1 AND KOBACOCUSTCODE = '" & strCODE & "'"
                    strCUSTCODE = .mobjSCGLSql.SQLSelectOneScalar(strSQL)
                    Return strCUSTCODE
                ElseIf strFLAG = "MED" Then
                    If strCODE <> "" Then strSQL = "select CUSTCODE, HIGHCUSTCODE From SC_CUST_DTL WHERE 1=1 AND MEDFLAG = 'B' AND ISNULL(USE_FLAG,0) = 1 AND (KOBACOMEDCODE = '" & strCODE & "' OR SBSMEDCODE = '" & strCODE & "' ) "
                    vntData = .mobjSCGLSql.SQLSelectArr(strSQL, intRowCnt, intColCnt)
                    Return vntData
                ElseIf strFLAG = "EXCLIENT" Then
                    If strCODE <> "" Then strSQL = "select HIGHCUSTCODE From SC_CUST_HDR WHERE 1=1 AND MEDFLAG in('G','K') AND ISNULL(USE_FLAG,0) = 1 AND CUSTNAME = '" & strCODE & "'"
                    strCUSTCODE = .mobjSCGLSql.SQLSelectOneScalar(strSQL)
                    Return strCUSTCODE
                ElseIf strFLAG = "CLIENTSUB" Then
                    If strCODE <> "" Then strSQL = "select CUSTCODE From SC_CUST_DTL WHERE 1=1 AND MEDFLAG = 'A' AND ISNULL(USE_FLAG,0) = 1 AND ISNULL(GBNFLAG,0) = 1 AND CUSTNAME = '" & strCODE & "'"
                    strCUSTCODE = .mobjSCGLSql.SQLSelectOneScalar(strSQL)
                    Return strCUSTCODE
                End If

            Catch err As Exception
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn")
            Finally
                '.mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

    Public Function DataValidation_CLIENTSUBCode(ByRef intRowCnt As Integer, _
                                                 ByRef intColCnt As Integer, _
                                                 ByVal strCODE As String, _
                                                 ByVal strCUSTCODE As String, _
                                                 ByVal strFLAG As String) As Object   'XML  데이터 조회시

        Dim strSQL As String
        Dim strFormet, strSelFields, strWhere As String
        Dim strChkDate As String = ""
        Dim vntData As Object
        Dim strCLIENTSUBCODE

        With mobjSCGLConfig
            Try
                'SetConfig(strInfoXML)   '기본정보 설정
                If strFLAG = "CLIENTSUB" Then
                    If strCODE <> "" Then
                        strSQL = strSQL & " SELECT  CUSTCODE"
                        strSQL = strSQL & " FROM SC_CUST_DTL"
                        strSQL = strSQL & " WHERE 1=1 "
                        strSQL = strSQL & " AND CUSTNAME = '" & strCODE & "'"
                        strSQL = strSQL & " AND HIGHCUSTCODE = '" & strCUSTCODE & "'"
                        strSQL = strSQL & " AND USE_FLAG = '1' AND MEDFLAG = 'A' AND GBNFLAG = '1' "

                        strCLIENTSUBCODE = .mobjSCGLSql.SQLSelectOneScalar(strSQL)
                    End If
                    Return strCLIENTSUBCODE
                End If

            Catch err As Exception
                Throw RaiseSysErr(err, CLASS_NAME & ".DataValidation_CLIENTSUBCode")
            Finally
                '.mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

    '브랜드 코드 체크
    Public Function DataValidation_BrandCode(ByVal strInfoXML As String, _
                                             ByRef intRowCnt As Integer, _
                                             ByRef intColCnt As Integer, _
                                             ByVal strCUSTCODE As String, _
                                             ByVal strSTD As String, _
                                             ByVal strMATTERNAME As String, _
                                             ByVal strYEARMON As String) As Object   'XML  데이터 조회시 

        Dim strSQL As String
        Dim strFormet, strSelFields, strWhere As String
        Dim strChkDate As String = ""
        Dim vntData As Object
        Dim strCNT
        Dim strCNT2

        With mobjSCGLConfig
            Try
                'SetConfig(strInfoXML)   '기본정보 설정

                If strSTD <> "" Then strSQL = "select COUNT(*) From SC_SUBSEQ_DTL WHERE isnull(dept_cd,'') <> '10000041' AND CUSTCODE = '" & strCUSTCODE & "' AND SEQNAME = '" & strSTD & "'"
                strCNT = .mobjSCGLSql.SQLSelectOneScalar(strSQL)

                If strCNT <= 0 Then
                    ProcessRtn_NEWSUBSEQ(strInfoXML, strCUSTCODE, strSTD, strYEARMON)
                End If

                If strMATTERNAME <> "" Then strSQL = "select COUNT(*) From MD_MATTER_MST WHERE MEDFLAG IN('A', 'A2') AND CUSTCODE = '" & strCUSTCODE & "' AND MATTER = '" & strMATTERNAME & "'"
                strCNT2 = .mobjSCGLSql.SQLSelectOneScalar(strSQL)

                If strCNT2 <= 0 Then
                    ProcessRtn_NEWMATTER(strInfoXML, strCUSTCODE, strMATTERNAME, strYEARMON)
                End If

                Return strCNT

            Catch err As Exception
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn")
            Finally
                '.mobjSCGLSql.SQLDisconnect()
            End Try
        End With
    End Function

    Public Function ProcessRtn_NEWSUBSEQ(ByVal strInfoXML As String, _
                                          ByVal strCUSTCODE As String, _
                                          ByVal strSTD As String, _
                                          ByVal strYEARMON As String) As Object

        Dim intRtn, intColCnt, intRows, i As Integer
        Dim strSQL As String
        Dim strSEQNO
        Dim strYEAR
        Dim strNOW As String '데이트형의 처리는 변수를 받아 텍스트로 처리 한다.. 

        strNOW = Now
        With mobjSCGLConfig '기본정보 Config 개체
            Try
                SetConfig(strInfoXML)   '기본정보 설정

                strYEAR = Mid(strYEARMON, 3, 2)

                strSEQNO = Get_NewSeqNo(strYEAR)

                strSQL = " INSERT INTO SC_SUBSEQ_DTL(SEQNO, SEQNAME, HIGHSEQNO, CUSTCODE, CLIENTSUBCODE, TIMCODE,DEPT_CD, MEMO, ATTR01, CUSER, CDATE, UUSER, UDATE)"
                strSQL = strSQL & " VALUES ("
                strSQL = strSQL & "  '" & strSEQNO & "', '" & strSTD & "', '','" & strCUSTCODE & "', '', '', '' , '','R', '" & .WRKUSR & "', '" & strNOW & "', '" & .WRKUSR & "', '" & strNOW & "')"

                mobjSCGLConfig.mobjSCGLSql.SQLDo(strSQL)

                Return intRows

            Catch err As Exception
                mobjSCGLConfig.mobjSCGLSql.SQLRollbackTrans()
                Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn::" & i & " 번째 로우에서 에러가 발생")
            Finally
            End Try
        End With
    End Function

    Public Function ProcessRtn_NEWMATTER(ByVal strInfoXML As String, _
                                         ByVal strCUSTCODE As String, _
                                         ByVal strMATTERNAME As String, _
                                         ByVal strYEARMON As String) As Object

        Dim intRtn, intColCnt, intRows, i As Integer
        Dim strSQL As String
        Dim strMATTERCODE
        Dim strYEAR
        Dim strNOW As String '데이트형의 처리는 변수를 받아 텍스트로 처리 한다.. 

        strNOW = Now

        SetConfig(strInfoXML)   '기본정보 설정
        With mobjSCGLConfig '기본정보 Config 개체
            Try

                strYEAR = Mid(strYEARMON, 3, 2)

                strMATTERCODE = Get_NewMatterCode(strYEAR)

                strSQL = " INSERT INTO DBO.MD_MATTER_MST(MATTERCODE, MATTER, CUSTCODE, SUBSEQ, EXCLIENTCODE, MEDFLAG, ATTR02, CUSER, CDATE, UUSER, UDATE)"
                strSQL = strSQL & " VALUES ("
                strSQL = strSQL & "  '" & strMATTERCODE & "', '" & strMATTERNAME & "', '" & strCUSTCODE & "', '', '', 'A', 'R', '" & .WRKUSR & "', '" & strNOW & "', '" & .WRKUSR & "', '" & strNOW & "')"

                mobjSCGLConfig.mobjSCGLSql.SQLDo(strSQL)

                Return intRows

            Catch err As Exception
                mobjSCGLConfig.mobjSCGLSql.SQLRollbackTrans()
                Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn::" & i & " 번째 로우에서 에러가 발생")
            Finally
            End Try
        End With
    End Function

    Public Function Get_NewSeqNo(ByVal strYEAR As String) As String
        Dim strSQL, strFormat, strRtn As String

        With mobjSCGLConfig '기본정보 Config 개체
            Try
                strSQL = "select 'S' +'" & strYEAR & "' + DBO.LPAD(ISNULL(MAX(CAST(SUBSTRING(SEQNO,4,5) AS NUMERIC(5,0))),0)+1,5,'0') From SC_SUBSEQ_DTL "
                strRtn = .mobjSCGLSql.SQLSelectOneScalar(strSQL)
                Return strRtn
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".Get_NewSeqNo")
            End Try
        End With
    End Function

    Public Function Get_NewMatterCode(ByVal strYEAR As String) As String
        Dim strSQL, strFormat, strRtn As String

        With mobjSCGLConfig '기본정보 Config 개체
            Try
                strSQL = "select 'M' +'" & strYEAR & "' + DBO.LPAD(ISNULL(MAX(CAST(SUBSTRING(MATTERCODE,4,5) AS NUMERIC(5,0))),0)+1,5,'0') From MD_MATTER_MST "
                strRtn = .mobjSCGLSql.SQLSelectOneScalar(strSQL)
                Return strRtn
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".Get_NewMatterCode")
            End Try
        End With
    End Function

    '저장로직 
    Public Function ProcessRtn(ByVal strInfoXML As String, _
                               ByVal vntData As Object, _
                               ByVal strCOL_NAME As String, _
                               ByRef blnIDs As Boolean, _
                               ByRef strYEARMON As String) As Integer
        Dim dblSEQ As Double
        Dim strERR
        Dim intRtn, intColCnt, intRows, i As Integer
        Dim strCUSTCODE, strMEDCODE, strREALMEDCODE
        Dim strSUBSEQ, strDEPT_CD, strADLOCALFLAG, strWEEK
        Dim strCLIENTSUBCODE
        Dim strEXCLIENTCODE

        Try
            SetConfig(strInfoXML)   '기본정보 설정
            With mobjSCGLConfig
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                .mobjSCGLSql.SQLBeginTrans()

                intColCnt = UBound(vntData, 1) : intRows = UBound(vntData, 2)

                For i = 1 To intRows
                    strCUSTCODE = ""
                    strMEDCODE = ""
                    strREALMEDCODE = ""
                    strSUBSEQ = ""
                    strDEPT_CD = ""
                    strCLIENTSUBCODE = ""
                    strEXCLIENTCODE = ""

                    If DataValidation(strInfoXML, vntData, strCOL_NAME, intColCnt, i, strERR, strCUSTCODE, strMEDCODE, strREALMEDCODE, strCLIENTSUBCODE, strEXCLIENTCODE, strYEARMON) = False Then
                        intRtn = InsertRtn_TEMP(vntData, "MD_ELECTRIC_MEDIUM_TEMP", strCOL_NAME, intColCnt, i, strERR, strYEARMON)
                    Else
                        dblSEQ = SelectRtn_SEQ(strYEARMON)

                        '지역을 세팅한다.
                        If GetElement(vntData, "ADLOCALFLAG", intColCnt, intRows) <> "" Then
                            If Len(GetElement(vntData, "ADLOCALFLAG", intColCnt, intRows)) = 40 Then
                                strADLOCALFLAG = "전국"
                            ElseIf Len(GetElement(vntData, "ADLOCALFLAG", intColCnt, intRows)) = 2 Then
                                strADLOCALFLAG = GetElement(vntData, "ADLOCALFLAG", intColCnt, intRows)
                            Else
                                strADLOCALFLAG = Mid(GetElement(vntData, "ADLOCALFLAG", intColCnt, intRows), 1, 2) & " 외"
                            End If
                        Else
                            strADLOCALFLAG = ""
                        End If

                        intRtn = InsertRtn(vntData, "MD_ELECTRIC_MEDIUM", strCOL_NAME, intColCnt, i, strYEARMON, dblSEQ, strCUSTCODE, strMEDCODE, strREALMEDCODE, strCLIENTSUBCODE, strEXCLIENTCODE, strADLOCALFLAG)
                    End If
                Next
                .mobjSCGLSql.SQLCommitTrans()
                Return intRows
            End With
        Catch err As Exception
            mobjSCGLConfig.mobjSCGLSql.SQLRollbackTrans()
            Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn::" & i & " 번째 로우에서 에러가 발생")
        Finally
        End Try
    End Function


    Public Function BatchCODE(ByVal strInfoXML As String, _
                              ByVal strYEARMON As String) As Integer

        Dim intRtn, intColCnt, intRows, i As Integer

        Dim strINSERTSQL As String
        Dim strMATTERINSERT As String
        Dim strCLIENTSUBCODESQL As String
        With mobjSCGLConfig
            Try
                SetConfig(strInfoXML)   '기본정보 설정

                .mobjSCGLSql.SQLConnect(.DBConnStr)
                .mobjSCGLSql.SQLBeginTrans()

                'intColCnt = UBound(vntData, 1) : intRows = UBound(vntData, 2)

                strCLIENTSUBCODESQL = " UPDATE MD_ELECTRIC_MEDIUM SET CLIENTCODE = DATA.HIGHCUSTCODE"
                strCLIENTSUBCODESQL = strCLIENTSUBCODESQL & " FROM ("
                strCLIENTSUBCODESQL = strCLIENTSUBCODESQL & " SELECT A.CLIENTCODE,B.HIGHCUSTCODE FROM MD_ELECTRIC_MEDIUM A "
                strCLIENTSUBCODESQL = strCLIENTSUBCODESQL & " LEFT JOIN SC_CUST_TEMP B ON A.CLIENTCODE= B.CUSTCODE"
                strCLIENTSUBCODESQL = strCLIENTSUBCODESQL & " WHERE YEARMON = '" & strYEARMON & "' "
                strCLIENTSUBCODESQL = strCLIENTSUBCODESQL & " AND (ISNULL(B.DEMANDFLAG,'') = '' OR ISNULL(B.DEMANDFLAG,'') =0)"
                strCLIENTSUBCODESQL = strCLIENTSUBCODESQL & " GROUP BY A.CLIENTCODE,B.HIGHCUSTCODE"
                strCLIENTSUBCODESQL = strCLIENTSUBCODESQL & " ) DATA"
                strCLIENTSUBCODESQL = strCLIENTSUBCODESQL & " WHERE MD_ELECTRIC_MEDIUM.CLIENTCODE = DATA.CLIENTCODE"
                strCLIENTSUBCODESQL = strCLIENTSUBCODESQL & " AND MD_ELECTRIC_MEDIUM.YEARMON = '" & strYEARMON & "' "

                mobjSCGLConfig.mobjSCGLSql.SQLDo(strCLIENTSUBCODESQL)

                strINSERTSQL = "insert into sc_jobcust (seqno,seqname,custcode)"
                strINSERTSQL = strINSERTSQL & " select "
                strINSERTSQL = strINSERTSQL & " dbo.lpad(maxdata.maxnum+seqno,6,'0') as seqno,"
                strINSERTSQL = strINSERTSQL & " subseqname as seqname, "
                strINSERTSQL = strINSERTSQL & " clientcode as custcode"
                strINSERTSQL = strINSERTSQL & " from"
                strINSERTSQL = strINSERTSQL & " ("
                strINSERTSQL = strINSERTSQL & " 	select ROW_NUMBER() OVER(ORDER BY clientcode) AS seqno, "
                strINSERTSQL = strINSERTSQL & " 	clientcode,subseqname"
                strINSERTSQL = strINSERTSQL & " 	from"
                strINSERTSQL = strINSERTSQL & " 	("
                strINSERTSQL = strINSERTSQL & " 		select clientcode,std subseqname "
                strINSERTSQL = strINSERTSQL & " 		from md_electric_medium"
                strINSERTSQL = strINSERTSQL & " 		where not exists	"
                strINSERTSQL = strINSERTSQL & " 		("
                strINSERTSQL = strINSERTSQL & " 			select custcode,seqname"
                strINSERTSQL = strINSERTSQL & " 			from"
                strINSERTSQL = strINSERTSQL & " 				("
                strINSERTSQL = strINSERTSQL & " 				select custcode,seqname"
                strINSERTSQL = strINSERTSQL & " 				from sc_jobcust"
                strINSERTSQL = strINSERTSQL & " 				where isnull(deptcd,'') <> '10000041'"
                strINSERTSQL = strINSERTSQL & " 				group by custcode,seqname"
                strINSERTSQL = strINSERTSQL & " 				) b "
                strINSERTSQL = strINSERTSQL & " 			where md_electric_medium.clientcode = b.custcode "
                strINSERTSQL = strINSERTSQL & " 			and md_electric_medium.std = b.seqname"
                strINSERTSQL = strINSERTSQL & " 		) and md_electric_medium.yearmon = '" & strYEARMON & "' "
                strINSERTSQL = strINSERTSQL & " 		  and isnull(md_electric_medium.sponsor,'N') = 'N'"
                strINSERTSQL = strINSERTSQL & " 	) data"
                strINSERTSQL = strINSERTSQL & " 	group by clientcode,subseqname"
                strINSERTSQL = strINSERTSQL & " ) enddata cross join (select max(cast(seqno as int)) as maxnum from sc_jobcust) maxdata"

                mobjSCGLConfig.mobjSCGLSql.SQLDo(strCLIENTSUBCODESQL)

                strMATTERINSERT = "INSERT INTO MD_ELECTRIC_MATTER"
                strMATTERINSERT = strMATTERINSERT & " (MATTER,CUSTCODE,SEQNO, EXCLIENTCODE)"
                strMATTERINSERT = strMATTERINSERT & "  select"
                strMATTERINSERT = strMATTERINSERT & "  matter,custcode,seqno, exclientcode"
                strMATTERINSERT = strMATTERINSERT & "  from"
                strMATTERINSERT = strMATTERINSERT & "  ("
                strMATTERINSERT = strMATTERINSERT & "  	select "
                strMATTERINSERT = strMATTERINSERT & "  	progname matter,"
                strMATTERINSERT = strMATTERINSERT & "  	clientcode as custcode,"
                strMATTERINSERT = strMATTERINSERT & "  	dbo.SC_JOBCUSTCODE2_FUN(clientcode,std) seqno, exclientcode"
                strMATTERINSERT = strMATTERINSERT & "  	from md_electric_medium"
                strMATTERINSERT = strMATTERINSERT & " 	where yearmon = '" & strYEARMON & "' "
                strMATTERINSERT = strMATTERINSERT & "     and isnull(sponsor,'N') = 'N'"
                strMATTERINSERT = strMATTERINSERT & "  	group by progname,clientcode,std, exclientcode"
                strMATTERINSERT = strMATTERINSERT & "  ) a "
                strMATTERINSERT = strMATTERINSERT & "  where not exists"
                strMATTERINSERT = strMATTERINSERT & "  ("
                strMATTERINSERT = strMATTERINSERT & "  			select matter,custcode,seqno"
                strMATTERINSERT = strMATTERINSERT & "  			from"
                strMATTERINSERT = strMATTERINSERT & "  				("
                strMATTERINSERT = strMATTERINSERT & "  				select matter,custcode,seqno"
                strMATTERINSERT = strMATTERINSERT & "  				from md_electric_matter"
                strMATTERINSERT = strMATTERINSERT & "  				) b "
                strMATTERINSERT = strMATTERINSERT & "  			where a.matter = b.matter "
                strMATTERINSERT = strMATTERINSERT & "  			and a.custcode = b.custcode"
                strMATTERINSERT = strMATTERINSERT & "  			and a.seqno = b.seqno"
                strMATTERINSERT = strMATTERINSERT & "  )"

                mobjSCGLConfig.mobjSCGLSql.SQLDo(strCLIENTSUBCODESQL)

                .mobjSCGLSql.SQLCommitTrans()

                Return intRows

            Catch err As Exception
                mobjSCGLConfig.mobjSCGLSql.SQLRollbackTrans()
                Throw RaiseSysErr(err, CLASS_NAME & ".ProcessRtn::" & i & " 번째 로우에서 에러가 발생")
            Finally
                .mobjSCGLSql.SQLDisconnect()
                mobjceMD_ELECTRIC_PREMATTER.Dispose()
            End Try
        End With
    End Function


    'SEQ생성
    Public Function SelectRtn_SEQ(ByRef strYEARMON As String) As String
        Dim strSQL, strFormat, strRtn As String
        With mobjSCGLConfig '기본정보 Config 개체
            Try
                ' ------ Array 데이터 조회 (True 일때 헤더정보 포함 조회(Sheet Data Binding 할 경우 사용), False 일때 데이터만 조회)
                strSQL = "select ISNULL(Max(SEQ),0) +1 From MD_ELECTRIC_MEDIUM WHERE YEARMON = '" & strYEARMON & "'"
                strRtn = .mobjSCGLSql.SQLSelectOneScalar(strSQL)
                Return strRtn
            Catch err As Exception
                ' 오류 전송
                Throw RaiseSysErr(err, CLASS_NAME & ".SelectRtn_SEQ")
            Finally
            End Try
        End With
        '여기까지 단순조회
    End Function

    '임시테이블에 오류데이터 투입 
    Private Function InsertRtn_TEMP(ByVal vntData As Object, _
                                    ByVal strTAB_NAME As String, _
                                    ByVal strCOL_NAME As String, _
                                    ByVal intCol As Integer, _
                                    ByVal intRow As Integer, _
                                    ByVal strERR As String, _
                                    ByVal strYEARMON As String) As Integer

        Dim strSQL As String
        Dim strFields As String
        Dim strTempValue As String
        Dim strValues As String
        Dim strArray
        Dim intNo
        Dim strBldValues As New System.Text.StringBuilder

        Dim i As Integer
        Try
            strArray = strCOL_NAME.Split("|")
            intNo = UBound(strArray)

            For i = 1 To intCol
                If vntData(i, intRow).ToString = "" Then
                    strTempValue = "NULL"
                Else
                    strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                End If
                If strERR <> "" And i = intCol Then
                    strTempValue = "'" & strERR & "'"
                End If

                strBldValues.Append(strTempValue & ",")
            Next

            strCOL_NAME = strCOL_NAME & "|YEARMON"
            strFields = strCOL_NAME.Replace("|", ",").TrimEnd(",")
            strValues = strBldValues.ToString.TrimEnd(",")
            strValues = strValues & ",'" & strYEARMON & "'"
            strSQL = String.Format("INSERT INTO {0} ({1}) VALUES({2})", strTAB_NAME, strFields, strValues)
            mobjSCGLConfig.mobjSCGLSql.SQLDo(strSQL)
        Catch err As Exception
            Throw RaiseSysErr(err, CLASS_NAME & strTAB_NAME & ".InsertDo")
        End Try
    End Function

    '데이터 투입
    Private Function InsertRtn(ByVal vntData As Object, _
                               ByVal strTAB_NAME As String, _
                               ByVal strCOL_NAME As String, _
                               ByVal intCol As Integer, _
                               ByVal intRow As Integer, _
                               ByVal strYEARMON As String, _
                               ByVal dblSEQ As Double, _
                               ByVal strCUSTCODE As String, _
                               ByVal strMEDCODE As String, _
                               ByVal strREALMEDCODE As String, _
                               ByVal strCLIENTSUBCODE As String, _
                               ByVal strEXCLIENTCODE As String, _
                               ByVal strADLOCALFLAG As String) As Integer

        Dim strSQL As String
        Dim strFields As String
        Dim strTempValue As String
        Dim strValues As String
        Dim strINPUT_CLIENTCODE, strINPUT_MEDCODE
        Dim strGETMEDCODE As Object
        Dim intcolcnt, introwcnt
        Dim intNo
        Dim strArray
        Dim strUSERINFO
        Dim strBRDMON
        Dim strBRDTUE
        Dim strBRDWED
        Dim strBRDTHU
        Dim strBRDFRI
        Dim strBRDSAT
        Dim strBRDSUN
        Dim strBldValues As New System.Text.StringBuilder

        Dim i As Integer
        Try
            strArray = strCOL_NAME.Split("|")
            intNo = UBound(strArray)

            For i = 1 To intCol
                If vntData(i, intRow).ToString = "" Then
                    strTempValue = "NULL"
                Else
                    Select Case Trim(strArray(i - 1).ToString)
                        Case "MEDGUBUN"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "REGIONGUBUN"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "CLIENTSUBCODE"
                            strTempValue = "'" & strCLIENTSUBCODE & "'"
                        Case "STD"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "EXCLIENTCODE"
                            strTempValue = "'" & strEXCLIENTCODE & "'"
                        Case "MATTERNAME"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "INPUT_MEDNAME"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "PROGRAM"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "INPUT_WEEK"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "TYPHOUR"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "BRDSTTIME"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "BRDEDTIME"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "ROLLSTDATE"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "-", "") & "'"
                        Case "ROLLEDDATE"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "-", "") & "'"
                        Case "TBRDSTDATE"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "-", "") & "'"
                        Case "TBRDEDDATE"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "-", "") & "'"
                        Case "CMLAN"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "CNT"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "PRICE"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "AMT"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "BRDDIV"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                        Case "ADSTOCFLAG"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "-", "") & "'"
                        Case "INPUT_AREAFLAGNAME"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "-", "") & "'"
                        Case "ADLOCALFLAG"
                            strTempValue = "'" & strADLOCALFLAG & "'"
                        Case "INPUT_CLIENTCODE"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "-", "") & "'"
                        Case "INPUT_MEDCODE"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "-", "") & "'"
                        Case "INPUT_MEDFLAG"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "-", "") & "'"
                        Case "INPUT_AREAFLAG"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "-", "") & "'"
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "-", "") & "'"
                        Case "ATTR01"
                            strTempValue = "''"
                        Case Else
                            strTempValue = "'" & Replace(vntData(i, intRow).ToString, "'", "''") & "'"
                    End Select
                End If
                strBldValues.Append(strTempValue & ",")
            Next

            '입력자EMPNO, 입력날자, 수정자EMPNO, 수정날자를 알맞는 형식으로 바꿔주기 위함..TO_DATE 때면에..
            Dim strFields2 As New System.Text.StringBuilder
            Dim strValues2 As New System.Text.StringBuilder
            Dim strNOW As String '데이트형의 처리는 변수를 받아 텍스트로 처리 한다.. 
            strNOW = Now
            BuildNameValues(",", "CUSER", mobjSCGLConfig.WRKUSR, strFields2, strValues2)
            BuildNameValues(",", "CDATE", strNOW, strFields2, strValues2)
            BuildNameValues(",", "UUSER", mobjSCGLConfig.WRKUSR, strFields2, strValues2)
            BuildNameValues(",", "UDATE", strNOW, strFields2, strValues2)

            strUSERINFO = String.Format("{0}", strValues2)
            Dim strWEEK
            Dim strINPUT_WEEK

            strWEEK = ""
            strWEEK = GetElement(vntData, "INPUT_WEEK", intCol, intRow)

            strBRDMON = GetWeek(strWEEK, intcolcnt, intRow, "MON")
            strBRDTUE = GetWeek(strWEEK, intcolcnt, intRow, "TUE")
            strBRDWED = GetWeek(strWEEK, intcolcnt, intRow, "WED")
            strBRDTHU = GetWeek(strWEEK, intcolcnt, intRow, "THU")
            strBRDFRI = GetWeek(strWEEK, intcolcnt, intRow, "FRI")
            strBRDSAT = GetWeek(strWEEK, intcolcnt, intRow, "SAT")
            strBRDSUN = GetWeek(strWEEK, intcolcnt, intRow, "SUN")


            strCOL_NAME = strCOL_NAME & "|YEARMON|SEQ|CLIENTCODE|MEDCODE|REAL_MED_CODE|BRDMON|BRDTUE|BRDWED|BRDTHU|BRDFRI|BRDSAT|BRDSUN|TRU_TAX_FLAG|COMMI_TAX_FLAG|SPONSOR|VOCH_TYPE|CUSER|CDATE|UUSER|UDATE"
            strFields = strCOL_NAME.Replace("|", ",").TrimEnd(",")
            strValues = strBldValues.ToString.TrimEnd(",")
            strValues = strValues & ",'" & strYEARMON & "'," & dblSEQ & ",'" & strCUSTCODE & "','" & strMEDCODE & "','" & strREALMEDCODE & "','" & strBRDMON & "','" & strBRDTUE & "','" & strBRDWED & "','" & strBRDTHU & "','" & strBRDFRI & "','" & strBRDSAT & "','" & strBRDSUN & "', 'Y','Y','N','0' " & "," & strUSERINFO
            strSQL = String.Format("INSERT INTO {0} ({1}) VALUES({2})", strTAB_NAME, strFields, strValues)
            mobjSCGLConfig.mobjSCGLSql.SQLDo(strSQL)
        Catch err As Exception
            Throw RaiseSysErr(err, CLASS_NAME & strTAB_NAME & ".InsertDo")
        End Try
    End Function



    '요일 구분에 따른 플레그 생성
    Private Function GetWeek(ByVal strWEEKLIST As String, _
                             ByVal intCol As Integer, _
                             ByVal intRow As Integer, _
                             ByVal strFLAG As String) As String

        Dim strSQL As String
        Dim strWEEK As String
        Dim i

        Try
            If strFLAG = "MON" Then
                If InStr(strWEEKLIST, "월") <> 0 Then
                    strWEEK = "1"
                Else
                    strWEEK = "0"
                End If
            End If
            If strFLAG = "TUE" Then
                If InStr(strWEEKLIST, "화") <> 0 Then
                    strWEEK = "1"
                Else
                    strWEEK = "0"
                End If
            End If
            If strFLAG = "WED" Then
                If InStr(strWEEKLIST, "수") <> 0 Then
                    strWEEK = "1"
                Else
                    strWEEK = "0"
                End If
            End If
            If strFLAG = "THU" Then
                If InStr(strWEEKLIST, "목") <> 0 Then
                    strWEEK = "1"
                Else
                    strWEEK = "0"
                End If
            End If
            If strFLAG = "FRI" Then
                If InStr(strWEEKLIST, "금") <> 0 Then
                    strWEEK = "1"
                Else
                    strWEEK = "0"
                End If
            End If
            If strFLAG = "SAT" Then
                If InStr(strWEEKLIST, "토") <> 0 Then
                    strWEEK = "1"
                Else
                    strWEEK = "0"
                End If
            End If
            If strFLAG = "SUN" Then
                If InStr(strWEEKLIST, "일") <> 0 Then
                    strWEEK = "1"
                Else
                    strWEEK = "0"
                End If
            End If

            Return strWEEK
        Catch err As Exception
            Throw RaiseSysErr(err, CLASS_NAME & ".GetWeek")
        End Try
    End Function


    '임시테이블 삭제
    Public Function Delete_Temp_Rtn(ByVal strInfoXML As String, ByVal strYEARMON As String) As Integer   '데이터 DELETE

        Dim strSQL As String
        Dim strFormet, strWhere As String
        Dim intRtn

        SetConfig(strInfoXML)    '기본정보 Setting
        With mobjSCGLConfig    '기본정보 Config 개체
            Try
                mobjceSC_USER_COL = New ceSC_USER_COL(mobjSCGLConfig)

                strFormet = "DELETE FROM {0} WHERE YEARMON = '" & strYEARMON & "'"
                strSQL = String.Format(strFormet, "MD_ELECTRIC_MEDIUM_TEMP")
                ' DB 접속 및 트랜잭션 시작
                .mobjSCGLSql.SQLConnect(.DBConnStr)
                .mobjSCGLSql.SQLBeginTrans()
                ' 엔티티 오브젝트의 Delete 메소드 호출
                intRtn = mobjceSC_USER_COL.DeleteDo_TEMP(strSQL)
                ' 트랜잭션 Commit
                .mobjSCGLSql.SQLCommitTrans()
                Return intRtn
            Catch err As Exception
                '트랜잭션 RollBack 및 오류 전송
                .mobjSCGLSql.SQLRollbackTrans()
                Throw RaiseSysErr(err, CLASS_NAME & "Delete_Temp_Rtn")
            Finally
                'DB접속 종료
                .mobjSCGLSql.SQLDisconnect()
                '사용한 Entity(개체Dispose)
                mobjceSC_USER_COL.Dispose()
            End Try
        End With
    End Function
#End Region
End Class
