		<!-- SpreadSheet/Control ActiveX COM -->
		<OBJECT id="mobjSCGLSpr" style="VISIBILITY: hidden; POSITION: absolute; TOP: 0px" height="0" width="0" classid="CLSID:28CD31BB-F003-4745-B2B4-2267981FA895" VIEWASTEXT>
		</OBJECT>
		<OBJECT id="mobjSCGLCtl" style="VISIBILITY: hidden; POSITION: absolute; TOP: 0px" height="0" width="0" classid="CLSID:DE7D60C0-32B6-43CE-B402-50BFB4ED2B70" VIEWASTEXT>
		</OBJECT>
		<!-- RDS.DataSpace -->
		<OBJECT id="ADS" style="VISIBILITY: hidden; POSITION: absolute; TOP: 0px" height="1" width="1" classid="clsid:BD96C556-65A3-11D0-983A-00C04FC29E36" VIEWASTEXT>
		</OBJECT>
		<!-- Farpoint SpreadSheet License :spr32x60.ocx -->
		<OBJECT CLASSID="clsid:5220cb21-c88d-11cf-b347-00aa00a28331" 
			id="Microsoft_Licensed_Class_Manager_1_0">
			<PARAM NAME="LPKPath" VALUE="/SFARDev/SC/Setup/fpSpread60.lpk">
		</OBJECT>  
